### ISSUE TITLE
Feature:  Want to add a feature to go on home page when Click on Recode Hive logo 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#100]
### Is your feature request related to a problem? Please describe.

When user will click on the logo so the user must route to the home page 

![image](https://github.com/user-attachments/assets/6daa6dc1-71a7-4540-be33-2f52c494b5f8)

**Comment by sanjay-kv** [comment]
https://recodehive.com/

redirect them to here: https://recodehive.com/github-tutorials/
