### ISSUE TITLE
ADD Active state to Navbar items to show on which page we are 

### ISSUE THREAD

**Issue by shubhagarwal1** [recodehive/awesome-github-profiles#1000]
Before:
<img width="1438" alt="Screenshot 2024-10-21 at 9 15 31 AM" src="https://github.com/user-attachments/assets/a24555c2-1b7d-4b13-9eb6-0837a378cee5">

After:
<img width="1434" alt="Screenshot 2024-10-21 at 9 15 57 AM" src="https://github.com/user-attachments/assets/79a18b9f-525f-43ce-966c-b1369bf782b6">

**Comment by sanjay-kv** [comment]
that image is not loaded properly. and thanks for the #1000 issue.

**Comment by shubhagarwal1** [comment]
@sanjay-kv, Sir i have updated the image ref.
