### ISSUE TITLE
Add detail to Event Page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#101]
https://recodehive.github.io/awesome-github-profiles/events.html

Video 1: https://www.youtube.com/watch?v=AtoVNe1mVUA&t=792s

Video 2: https://www.youtube.com/watch?v=Rm2lT9j6VxQ&t=522s

Video 3: Mention its upcoming event

**Comment by Asymtode712** [comment]
@sanjay-kv I would like to work on this

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir can i work
