### ISSUE TITLE
Add Profile: heizshubham

### ISSUE THREAD

**Issue by heizshubham** [recodehive/awesome-github-profiles#1012]
A pull request should be created from this issue if not kindly ping @dinxsh

**Comment by sanjay-kv** [comment]
@HimangshuSharma01  Could you cross check all add profile issues, and if this already added to the website could you help me close the issues. I will also do the same from my end. 
I could see there is more issues on this.

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01  Could you cross check all add profile issues, and if this already added to the website could you help me close the issues. I will also do the same from my end. 
> I could see there is more issues on this.

Yes sir I will do it
