### ISSUE TITLE
Add Profile: amanver45

### ISSUE THREAD

**Issue by amanver45** [recodehive/awesome-github-profiles#1015]
Add My Profle
Add My Profle : amanver45 : https://github.com/amanver45
@sanjay-kv @dinxsh

**Comment by dinxsh** [comment]
hi @HimangshuSharma01 are you adding these images manually? any reason to mark this issue as completed? please do let me know Im working getting the bot back together it'll be up and running soon, thanks! 😸

**Comment by HimangshuSharma01** [comment]
-![Screenshot_20241024_031046.jpg](https://github.com/user-attachments/assets/c0ab4ea1-bcf1-4895-ab39-0be2084a670a)

I was asked to do so did I make any mistake?

**Comment by HimangshuSharma01** [comment]
> -![Screenshot_20241024_031046.jpg](https://github.com/user-attachments/assets/c0ab4ea1-bcf1-4895-ab39-0be2084a670a)
> 
> I was asked to do so did I make any mistake? @dinxsh

**Comment by amanver45** [comment]
@dinxsh  @HimangshuSharma01  my profile is not added

**Comment by sanjay-kv** [comment]
@dinxsh 

sorry i forgot to update... all the pending profiles I scraped and added to the src file.
