### ISSUE TITLE
X ( Twitter ) logo don't showing

### ISSUE THREAD

**Issue by Hemraj-7** [recodehive/awesome-github-profiles#1023]
X ( Twitter ) logo don't showing. it want to change color for showing

![Screenshot 2024-10-22 134859](https://github.com/user-attachments/assets/07d6eb86-ed15-4038-8466-e166e6cf72ca)

Assign me this issue I'll fix this

**Comment by laxmikandivalasa** [comment]
I'd like work on this issue too!!

**Comment by sanjay-kv** [comment]
this is already fixed isnt it?

**Comment by laxmikandivalasa** [comment]
no...it isn't displaying

**Comment by Hemraj-7** [comment]
> this is already fixed isnt it?

Nope, it is not display

**Comment by ChimeraElixir** [comment]
i Would like to work on it as my first contribution please assign me this
