### ISSUE TITLE
Home page navigation

### ISSUE THREAD

**Issue by saumyayadav25** [recodehive/awesome-github-profiles#1025]
There is no option in navbar to get back to home page in any of the pages.
It can be implemented for better navigation from other pages to home page also.

<img width="1440" alt="Screenshot 2024-10-22 at 5 17 30 PM" src="https://github.com/user-attachments/assets/7062af25-ab87-4ae5-82e2-fe8c8123ee92">

**Comment by sanjay-kv** [comment]
actually there is

**Comment by saumyayadav25** [comment]
> actually there is

okay, if it's there, you may close this issue 😄
if any implementation is required u can let me know
