### ISSUE TITLE
Add home page in the nav bar for easy navigation

### ISSUE THREAD

**Issue by laxmikandivalasa** [recodehive/awesome-github-profiles#1027]
![image](https://github.com/user-attachments/assets/ec66683d-1c8b-4099-9f4d-c23b023f9323)
if there is a home page in nav bar it would be easy for people to navigate to the  profiles page

I'd like to work on this
can you assign this to me??

**Comment by sanjay-kv** [comment]
we basically click on the recodehive on the left top to redirect the home page.
