### ISSUE TITLE
Enhance the UI of the footer section

### ISSUE THREAD

**Issue by T-Fathima** [recodehive/awesome-github-profiles#1028]
I would like to propose to enhance the UI of the footer section by aligning it's sections properly for better user-experience and readability.
![image](https://github.com/user-attachments/assets/ea167ae4-512d-47c7-a562-6d7d78628b8a)
I would like to work on it.
Please assign me this issue under gssoc-ext and hacktoberfest.

**Comment by sanjay-kv** [comment]
any sample? for my ref?
