### ISSUE TITLE
Link update to the side social button. 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#103]
- [ ] can we rearrange button like, facebook, GitHub, Linkedin, Twitter, Youtube

facebook: https://www.facebook.com/recodehive
GitHub: https://github.com/recodehive
Linkedin: https://www.linkedin.com/in/sanjay-k-v/
Twitter: https://twitter.com/sanjay_kv_
Youtube: https://www.youtube.com/@RecodeHive

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work

**Comment by thevijayshankersharma** [comment]
@Ayushmaanagarwal1211 If you don't mind, should I do this task?

**Comment by Ayushmaanagarwal1211** [comment]
@thevijayshankersharma srry bro actually i already created a pr
