### ISSUE TITLE
Adding a button in the Navigation bar for the Awesome GitHub Profile READMEs (Homepage)

### ISSUE THREAD

**Issue by lakshyagrg23** [recodehive/awesome-github-profiles#1041]
There is no option to access the Awesome GitHub Profile READMEs page in the Navigation bar. There is no way to access that page other than clicking the icon of the website, which is rather unintuitive. I can add a button for it in the Navigation bar, so please assign it to me.

![Screenshot 2024-10-23 195807](https://github.com/user-attachments/assets/9dd1c8bf-e50b-4d83-a109-9d8c5b038334)
![Screenshot 2024-10-23 195831](https://github.com/user-attachments/assets/9b35398a-1d99-441f-90e1-088e06d2a837)

**Comment by sanjay-kv** [comment]
recodehive logo act as home button
