### ISSUE TITLE
Manage the file structure

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#106]
I know we moving fast with the dev, but when we code we have to make sure file structure , readability, 

![image](https://github.com/user-attachments/assets/ca561d0d-fb71-4a49-81d2-4f15366117c2)

the above is not good standard of creating files. 

can we push all the page files to a folder called `pages`

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work on that

**Comment by Asymtode712** [comment]
@sanjay-kv I have fixed this issue in PR #184 you may close it

**Comment by sanjay-kv** [comment]
can u do this on main branch

**Comment by Asymtode712** [comment]
@sanjay-kv I have raised #185 for the same
