### ISSUE TITLE
Bug: Inconsistent Navigation Menu Options

### ISSUE THREAD

**Issue by yehiarasheed** [recodehive/awesome-github-profiles#1068]
### Description

Upon working on issue #757 and fixing it in PR #1066, I noticed that the Navigation menu Blog.html page is not correctly ordered, unlike the homepage and the Events Page where the Navigation Menu maintains a certain order of Pages.

#### Homepage
![image](https://github.com/user-attachments/assets/bc59c903-ffac-47b0-9181-a9a17e559b6e)
#### Events Page
![image](https://github.com/user-attachments/assets/a2f7f516-48d8-42eb-b318-2d1e46d0a475)
#### Blogs page
![image](https://github.com/user-attachments/assets/3cb563fd-5133-47d2-8760-242faec17578)

### Solution
My proposed solution is that for me to reorder the sections in the Navigation menu of the Blogs page to match the order found in the other pages. Please Assign me to the issue so that I could start working on it.

**Comment by yehiarasheed** [comment]
@sanjay-kv, I've solved this issue along with another issue in the same PR, I didn't know that if you make multiple commits with one open PR it adds all commits to that PR, can we increase the level of the PR so that it includes both issues? The PR is #1066

**Comment by sanjay-kv** [comment]
increased level to level3
