### ISSUE TITLE
GitHub Profile Summary: Display Assigned Issues, Raised PRs, and Merged PRs

### ISSUE THREAD

**Issue by shubhagarwal1** [recodehive/awesome-github-profiles#1072]
Description:  As a GitHub user, it would be highly beneficial to have a feature that allows users to quickly view their assigned issues, raised pull requests (PRs), and merged PRs in one place.  This feature could:  	•	Provide a streamlined dashboard where users can enter any GitHub username. 	•	Automatically display all assigned issues, open PRs, and merged PRs for that user. 	•	Enhance visibility for users managing multiple repositories by offering a single view of their activities.

**Comment by sanjay-kv** [comment]
I was planned it like we already have login page. so when user login they should be able to see the summary

**Comment by shubhagarwal1** [comment]
> I was planned it like we already have login page. so when user login they should be able to see the summary

Understood
