### ISSUE TITLE
social media icon is not visible and improvement in the design of the home page 

### ISSUE THREAD

**Issue by Bhupendrakumar20** [recodehive/awesome-github-profiles#1076]
home page has sufficient amount of change kindly go through it :

1. the Styling make require some hover effect over each profile section 
2. header section require some marginal changes with proper theme design colors 
3. background color to the header icon sections make it more attractive 
4. X icon is not visible to users 

![Screenshot_25-10-2024_1523_recodehive github io](https://github.com/user-attachments/assets/93a15507-7698-44d3-84fb-21440819b1ef)

kindly check the issue and kindly assigned this task to me under labels

**Comment by Bhupendrakumar20** [comment]
@sanjay-kv  kindly assigned this issue to me

**Comment by sanjay-kv** [comment]
this is hapnned due to stopped deployment I will redeploy
