### ISSUE TITLE
 Please deploy the code again on the URL so that all the changes done in the past week are visible 

### ISSUE THREAD

**Issue by saksham-1304** [recodehive/awesome-github-profiles#1095]
# Issue

@sanjay-kv  Please deploy the code again on the URL so that the changes made in the last week are visible on the website

## Image 
![image](https://github.com/user-attachments/assets/43475fd3-2f51-4a48-97c4-d6872664b16e)

**Comment by sanjay-kv** [comment]
I assigned to maintainer @dinxsh
