### ISSUE TITLE
Missing X Icon on Website

### ISSUE THREAD

**Issue by Snehshishdutta** [recodehive/awesome-github-profiles#1096]
Hi @sanjay-kv ,
 I noticed that the Twitter icon is currently not visible on the website. This may affect users' ability to connect with your Twitter account easily.
![Screenshot 2024-10-26 085302](https://github.com/user-attachments/assets/dd14344b-306a-46c4-94a5-33365b750af5)

 I can assist in correcting this issue. 
![Screenshot 2024-10-26 092016](https://github.com/user-attachments/assets/cb8feed5-e31e-42fb-821d-9644934b68fa)
Can u please assign this issue to me under gssoc-ext and hacktoberfest accepted label?

**Comment by sanjay-kv** [comment]
its already fixed. 
@dinxsh can we redeploy the github pages. i think the same issue been raising because the changes is not reflecting properly. 
do you know which vercel account been used for this?
