### ISSUE TITLE
Bug Issue with Theme: 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#11]
Toggle Button will do

**Comment by thevijayshankersharma** [comment]
![image](https://github.com/user-attachments/assets/aca6d859-3792-4666-b745-29f494374a26)


![image](https://github.com/user-attachments/assets/026d843c-1e3b-4f30-98ec-f59bc3f844be)

**Comment by nishant0708** [comment]
Can I work on this?

**Comment by sanjay-kv** [comment]
Yes Nishant

**Comment by thevijayshankersharma** [comment]
@sanjay-kv I have already made that. How can I raise the PR for it.

**Comment by sanjay-kv** [comment]
@thevijayshankersharma are you talking about dark mode?

**Comment by sanjay-kv** [comment]
@nishant0708 
I need more changes in the website, like im planning to make it public to everyone and get additional points when they add their profile. 
before that im looking it to make more UI friendly and add more features. 

I will also raise issue when i find something interesting. can you also look for the same in simillar website and raise an issue, once we both like can add contributions.

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma are you talking about dark mode?

Yes

**Comment by nishant0708** [comment]
hey @sanjay-kv for sure .

**Comment by sanjay-kv** [comment]
@nishant0708 hows the background scroll function going on

**Comment by nishant0708** [comment]
hey @sanjay-kv  actually Code and every thing is working fine we are just facing issue to make it work with allcontributors bot
![Screenshot 2024-08-03 003601](https://github.com/user-attachments/assets/59d8afbf-d02f-4c3d-abe6-aabdcb1394ba)
Like js function is working fine 

But this Action bot while taking ss is giving this Error 
![Screenshot 2024-08-03 032242](https://github.com/user-attachments/assets/e9621ca2-ca5c-4665-bfb9-20261fa01df3)

so @dinxsh is Looking into it and trying to fix this error .

**Comment by sanjay-kv** [comment]
sure. thanks for letting me know.

**Comment by nishant0708** [comment]
hey @sanjay-kv sir one more things the points of this repo is not getting count on the leaderboard
