### ISSUE TITLE
Add Profile: Ranj8521Kumar

### ISSUE THREAD

**Issue by Ranj8521Kumar** [recodehive/awesome-github-profiles#1111]
Please add my github profie @sanjay-kv 

![image](https://github.com/user-attachments/assets/e874bb45-a668-4192-b3f3-e7e8c7448511)

**Comment by WednesdaySP** [comment]
Hey @Ranj8521Kumar, could you please tell me how you took the complete image of your git profile at once? I'm unable to do so. Your help would be greatly appreciated.

**Comment by Ranj8521Kumar** [comment]
Add this extension to your browser @WednesdaySP for taking full page screenshot:
![image](https://github.com/user-attachments/assets/860a59bf-db6d-4a73-a21e-9e09f1e0df86)

**Comment by WednesdaySP** [comment]
@Ranj8521Kumar thank you for the help :)

**Comment by Ranj8521Kumar** [comment]
Please add my profile @sanjay-kv
