### ISSUE TITLE
change the dark theme to lighter shade of black.

### ISSUE THREAD

**Issue by rishika105** [recodehive/awesome-github-profiles#1113]
I think most of the dark themes use a shade that will also be suitable for your eyes but this dark is carbon black which is irritating the eye. I think changing the dark color to a typical dark theme of any other website.

**Comment by sanjay-kv** [comment]
can i see a sample

**Comment by rishika105** [comment]
I have changed in one page you can see. 
![Screenshot (859)](https://github.com/user-attachments/assets/d31472f0-8944-4bb2-9274-b099137a9057)
![Screenshot (858)](https://github.com/user-attachments/assets/15349d70-339d-4fe2-8d4a-cb6d7e07c312)

**Comment by rishika105** [comment]
Can you tell which shade you would like the second one or third one? @sanjay-kv
