### ISSUE TITLE
UI Changes in "CONTACT US" form

### ISSUE THREAD

**Issue by Mrunali01** [recodehive/awesome-github-profiles#1114]
Placeholders are missing and the text is not visible in dark mode due to its font color.

<img width="935" alt="recordhive1" src="https://github.com/user-attachments/assets/1679426f-3900-464d-a848-1ab817c7cf8c">

Please assign this issue to me @sanjay-kv  under the label gssoc-extd

**Comment by sanjay-kv** [comment]
naah this dosent look good., existing one will do

**Comment by Mrunali01** [comment]
The screenshot attached is the existing one :)
I raised an issue to make changes in that.

**Comment by Mrunali01** [comment]
please add labels gssoc-extd and level
