### ISSUE TITLE
Twitter Logo is Not Visible In Both Mode

### ISSUE THREAD

**Issue by Hemraj-7** [recodehive/awesome-github-profiles#1117]
X ( Twitter ) Logo is Not Visible In Both white  mode and dark mode.

check this
![Screenshot 2024-10-27 162412](https://github.com/user-attachments/assets/66f0764e-eec3-4386-8b30-a7374221f053)
![Screenshot 2024-10-27 162434](https://github.com/user-attachments/assets/0667c9c5-b943-4865-9ce3-ae770cf691c8)

Assign me this issue @sanjay-kv 
Thank You!

**Comment by sanjay-kv** [comment]
this is already sassigned
