### ISSUE TITLE
Adding Background To the Website

### ISSUE THREAD

**Issue by AshmitaBarthwal** [recodehive/awesome-github-profiles#1123]
https://github.com/user-attachments/assets/0f8adc6f-16bf-49ab-b0e7-2524865600b2

**Comment by AshmitaBarthwal** [comment]
Uploading Screen Recording 2024-10-27 222001.mp4…

**Comment by AshmitaBarthwal** [comment]
https://github.com/user-attachments/assets/9551aa7f-c181-465f-84aa-f76eb31f0158

**Comment by AshmitaBarthwal** [comment]
@sanjay-kv  Please assaign this issue to me.

**Comment by sanjay-kv** [comment]
this is not in planned req
