### ISSUE TITLE
Feature:  Enhanced Social Media Icons with Hover Animation

### ISSUE THREAD

**Issue by thevijayshankersharma** [recodehive/awesome-github-profiles#114]
### Is your feature request related to a problem? Please describe.

The current social media icons lack visual appeal and do not adapt well to different themes, making them less engaging for users. In particular, there is no hover effect to highlight interaction, and the icons do not adjust for dark mode, which may result in poor visibility and readability.

### Describe the solution you'd like

Implement a stylish hover effect for social media icons where the background color animates from the bottom up, and the icon color changes to white on hover. The design should include dark mode support to ensure that the icons remain clear and visually appealing in both light and dark environments.

### Describe alternatives you've considered

Static Icons: Keep the icons without any hover effects or dark mode adjustments. This would be a simpler solution but would not enhance user interaction or aesthetics.
Basic Hover Effects: Use simpler hover effects without background animations or dark mode support. This would be less engaging but easier to implement.
Pre-built Icon Libraries: Utilize icon libraries with built-in dark mode and hover effects. However, this might limit customization and might not align with specific design requirements.

### Additional context

https://github.com/user-attachments/assets/f9434c9f-a0a7-488f-a73e-8ba0f5cedcd1

**Comment by sanjay-kv** [comment]
bring in more ideas
