### ISSUE TITLE
Dark theme button is not working in index page

### ISSUE THREAD

**Issue by Ananya-vastare** [recodehive/awesome-github-profiles#1144]
![Change3](https://github.com/user-attachments/assets/829b45aa-da37-4fe7-a3bc-05765161270c)
I would like to fix this bug please assign this issue to me

**Comment by Ananya-vastare** [comment]
@sanjay-kv please assign this issue to me

**Comment by sanjay-kv** [comment]
have to put on hold, i can see its working for me.
