### ISSUE TITLE
Add button like google and facbook in sign in page and  login page 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [recodehive/awesome-github-profiles#1155]
![Screenshot (454)](https://github.com/user-attachments/assets/65e1dc60-17f3-429e-984f-5ab9ae7853fa)

- benefits:
- 
proved User Experience: Users can quickly sign in with a single click, avoiding the need to remember another password. This makes onboarding faster and easier.

Enhanced Security: Google and Facebook handle authentication, reducing the need for you to store sensitive passwords. OAuth 2.0 protocols are secure and help protect against common vulnerabilities like phishing and brute-force attacks.

Increased Registration Rates: Social logins tend to have higher sign-up and login rates because they minimize barriers. Users are more likely to complete the registration process if it’s convenient.

**Comment by RahulPrasadYadav** [comment]
@sanjay-kv please assign the issue ....  today is last day

**Comment by sanjay-kv** [comment]
sorry rahul, we only planning to use github here
