### ISSUE TITLE
Removal of the preloader 

### ISSUE THREAD

**Issue by HimangshuSharma01** [recodehive/awesome-github-profiles#1160]

**Comment by HimangshuSharma01** [comment]
@sanjay-kv sir can we add skeleton loading instead of that?

**Comment by sanjay-kv** [comment]
i think we can remove the pre loading, as I analysed the page load time is 99% faster comparing to other pages

**Comment by HimangshuSharma01** [comment]
> i think we can remove the pre loading, as I analysed the page load time is 99% faster comparing to other pages

okay sir
