### ISSUE TITLE
Social Links Enhancement

### ISSUE THREAD

**Issue by sachinggsingh** [recodehive/awesome-github-profiles#1174]
**By the Current Deployed site it's not clear but it seems to be the icon of X**
![Screenshot 2024-10-31 231509](https://github.com/user-attachments/assets/1054d8ba-78d5-44bb-a873-01d55b1c8da2)

It's not visible

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by sanjay-kv** [comment]
its already fixed. some deployment issue cause this
