### ISSUE TITLE
Home screen Enhancement 

### ISSUE THREAD

**Issue by sachinggsingh** [recodehive/awesome-github-profiles#1175]
**The Heart shaped Icon on the home screen beside the mic is not visible completely**
![Screenshot 2024-10-31 231437](https://github.com/user-attachments/assets/980e40ff-f599-43b7-9820-33909158819d)
 
A part of it seems like to be sliced to me as a Viewer

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by sanjay-kv** [comment]
its already fixed
