### ISSUE TITLE
Visitor count over lapping

### ISSUE THREAD

**Issue by JomanaMahmoud** [recodehive/awesome-github-profiles#1183]
![image](https://github.com/user-attachments/assets/da6c6cbb-3d08-4da6-ad3e-2d101e21eb89)
i want to make it under the footer not overlapping

**Comment by JomanaMahmoud** [comment]
the visitor count was removed entirely, do you have anything else i can work on instead of this issue as it doesnt make sense now @sanjay-kv

**Comment by sanjay-kv** [comment]
there are few open issue, and i will open few issues today.
