### ISSUE TITLE
Change the list to very few

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#12]
In the below image : 

We only Keep, Badge, Minimalist, Dynamic, Icons, Backgrounds, GIFS, Gamefy, Code Fit in one line. 
![image](https://github.com/user-attachments/assets/c30662af-1fbc-4025-a1e9-cca864a75b03)

**Comment by thevijayshankersharma** [comment]
@sanjay-kv How exactly can I contribute?


![image](https://github.com/user-attachments/assets/bcd16406-5e32-4ea3-b32d-65c5e940da0f)

**Comment by sanjay-kv** [comment]
I dont get your question, its a normal opensource project, same issue and PR procedure

**Comment by nishant0708** [comment]
Can i work on this  @sanjay-kv ??

**Comment by thevijayshankersharma** [comment]
@sanjay-kv  Shall i raise PR for this for nishant will do it ??

**Comment by sanjay-kv** [comment]
okay. nishant will do it. @thevijayshankersharma you can find some way to improve the website and raise new issue, i will assign to you

**Comment by thevijayshankersharma** [comment]
> okay. nishant will do it. @thevijayshankersharma you can find some way to improve the website and raise new issue, i will assign to you


So should i raise for enhancing the toggle. like adding the sun and moon picture in it. 

![image](https://github.com/user-attachments/assets/fc93a8ab-ec50-432a-82fa-2c6ee1dc8817)


OR this 

![image](https://github.com/user-attachments/assets/dc0b9e3d-7751-4459-a5ba-15c7d0949e76)


![image](https://github.com/user-attachments/assets/7d6593ea-fca3-41a4-b6bc-e5e0c0aba25c)

**Comment by sanjay-kv** [comment]
the first 2 picture look good.

**Comment by sanjay-kv** [comment]
you can add
