### ISSUE TITLE
➕Add Hamburger to the website and Make it Responsive

### ISSUE THREAD

**Issue by aslams2020** [recodehive/awesome-github-profiles#120]
Hey @sanjay-kv 

I **want to add a hamburger menu** to the website because the **current navbar is causing responsiveness issues.** 
The navbar is not adjusting correctly on smaller screens and is **extending beyond the viewport body.**

Implementing a hamburger menu **will help in making the navigation more responsive** and user-friendly on mobile devices.

![image](https://github.com/user-attachments/assets/ef07409c-1d55-4972-a2f7-21b04326c053)

Could you please assign me with this?
thankyou!

**Comment by sanjay-kv** [comment]
How this going @aslams2020

**Comment by aslams2020** [comment]
@sanjay-kv Was Completing Other repos tasks,will do this today itself..
