### ISSUE TITLE
Issues in Footer Logo and Submit Button and Hover effect

### ISSUE THREAD

**Issue by rupeshv2121** [recodehive/awesome-github-profiles#1206]
Website logo size is too small.
Submit button width too large.
No hover effect on save blog options.

@sanjay-kv 
pls assign me under label gssoc-ext, hacktoberfest-accepted

![Screenshot 2024-11-03 205034](https://github.com/user-attachments/assets/a2d421fc-a333-4662-9c72-51bd4a02b477)
![Screenshot 2024-11-03 205259](https://github.com/user-attachments/assets/5c8b1387-d887-4c34-955c-e74edba0ad19)
![Screenshot 2024-11-03 205437](https://github.com/user-attachments/assets/10e3a114-8429-4b40-936e-e49539c9bbce)

**Comment by rupeshv2121** [comment]
![image](https://github.com/user-attachments/assets/e8ffbb21-102e-45d6-bc72-424445c38b68)
@sanjay-kv sir i'm not able to start website correctly , can you pls help to do it. So that i can work asap

**Comment by sanjay-kv** [comment]
dont change theme

**Comment by rupeshv2121** [comment]
@sanjay-kv sir i do not change the theme when I run on my machine it is showing this that's why I am telling

**Comment by rupeshv2121** [comment]
Pls open the PR
