### ISSUE TITLE
Enhance Navbar UI

### ISSUE THREAD

**Issue by tatheer-fathima** [recodehive/awesome-github-profiles#1223]
The current navbar UI could benefit from improvements to make it more visually appealing and user-friendly.
![image](https://github.com/user-attachments/assets/75ed2c1d-73d3-4506-aa59-d89a602866b5)
I would like work on the Enhancement of the navbar.
@sanjay-kv Please assign it to me under level 2 
Thank you.

**Comment by sanjay-kv** [comment]
any sample?

**Comment by nihalaniharsh** [comment]
Could you please assign the issue to me ? I' am eager to drive in and make a meaningful impact .Thankyou for considering my request!"
