### ISSUE TITLE
Add proper hover effects on footer of Compare page

### ISSUE THREAD

**Issue by ShudarsanRegmi** [recodehive/awesome-github-profiles#1241]
![image](https://github.com/user-attachments/assets/f3f41f51-4c58-4b5c-9ee0-76df1659273b)
The hover effect on these icons isn't very attractive. I want to modify it so that when someone hovers over an icon, it changes to the original color of the respective social site's logo.

**Comment by hardikguptaofficialgit** [comment]
Assign me this task !
