### ISSUE TITLE
Bug : Website is not working . 

### ISSUE THREAD

**Issue by sumitdashrathgupta** [recodehive/awesome-github-profiles#1246]
![Capture](https://github.com/user-attachments/assets/b0489917-95bb-47c5-9b79-faba10cba50d)

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/awesome-github-profiles/issues/1245

check this out

**Comment by sanjay-kv** [comment]
I think changing server port doesnt help , kindly see #1245
