### ISSUE TITLE
Feature: Implement Profile Comparison Feature

### ISSUE THREAD

**Issue by MastanSayyad** [recodehive/awesome-github-profiles#125]
Hey @sanjay-kv 

I've got an idea, We can implement a feature that allows users to compare two or more profiles side-by-side based on various metrics such as contributions, stars, followers, etc. This will help users to better analyze and compare profiles directly on the Recode Hive website.

We can give it  a try!

**Comment by sanjay-kv** [comment]
these seems awesome, 
you can work on it, we can create a new nav bar tab called compare for this,

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir can i work on this

**Comment by MastanSayyad** [comment]
> @sanjay-kv sir can i work on this

Hey @Ayushmaanagarwal1211 I'm working on it right now, Let me try it first, if I'm unable to do it, I'll surely inform you!

**Comment by Ayushmaanagarwal1211** [comment]
@MastanSayyad ok bro

**Comment by MastanSayyad** [comment]
@Ayushmaanagarwal1211 You can take on this task, as I'm busy resolving some complex Errors of Faild checks of a Contributor regarding postman challenge and @sanjay-kv might need the development of this website asap, so go ahead! @sanjay-kv you can assign this issue to @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
@MastanSayyad Ok bro

**Comment by MastanSayyad** [comment]
@Ayushmaanagarwal1211 Thanks, let me know if you need any assistance in scripts or anything!

**Comment by sanjay-kv** [comment]
thanks for helping people with the postman @MastanSayyad really appreciated it.
