### ISSUE TITLE
feat:Social icons Enhancement in the Compare Page

### ISSUE THREAD

**Issue by likitha-kapu** [recodehive/awesome-github-profiles#1250]
The Social icons in the compare page have no change in colour effect :
![Screenshot 2024-11-07 101708](https://github.com/user-attachments/assets/f98bae03-d3b8-4bf9-97d4-4b1d4ab229b6)

However those of the other pages have a change in colour.This creates a mismatch and causes different visual effects to the user.
![Screenshot 2024-11-07 101625](https://github.com/user-attachments/assets/f1a9b2b3-c222-47c8-acb4-a2d7fda6a2c1)

**Comment by likitha-kapu** [comment]
@sanjay-kv please assign me this task

**Comment by sanjay-kv** [comment]
I think this is already raised and merged.
