### ISSUE TITLE
Revamp:  improving responsiveness, design harmony and overall enhancement for footer

### ISSUE THREAD

**Issue by ShudarsanRegmi** [recodehive/awesome-github-profiles#1256]
I want to make following changes:
- fix the squezed logo on footer
- ehnance the responsiveness
- enhance the design harmony
- optimize overall footer

**Comment by sanjay-kv** [comment]
can you check why site showing dangerous when open deployment link

**Comment by ShudarsanRegmi** [comment]
@sanjay-kv  Sir, this seems to be a protection provided by google chrome to block phishing sites. So, our website is marked dangerous by google chrome only and not by any other browsers. 
This seems to be a famous problem. Many people have encountered this on their clone projects like facebook clone, netflix clone,etc.[1] 
I've found a solution in stackoverflow that we've need to verfiy the ownersnhip in google search console.[2]
We've to verify the ownership of the file by uplaoding html file in google search console. [3]
![image](https://github.com/user-attachments/assets/fd288ab1-b5ca-4c54-84f4-fb4ce8ba379d)

- [1] [Discussion on github community](https://github.com/orgs/community/discussions/30261)
- [2] [Stackoveflow answer](https://stackoverflow.com/questions/70807000/static-html-css-site-deployed-using-github-pages-getting-marked-as-dangerous-by)
- [3] [Google Search Console](https://search.google.com/search-console/welcome)

**Comment by sanjay-kv** [comment]
could you check any code creating this issue, it wasn't there before unless merge of few recent PR
