### ISSUE TITLE
Feature:  Want to create Faq's page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#127]
### Is your feature request related to a problem? Please describe.

Sir i am thinking of creating the FAQ's page similar to the gssoc website 

![image](https://github.com/user-attachments/assets/2e356e63-770c-4c98-a615-61de6a8ce76e)

**Comment by sanjay-kv** [comment]
Naah we will skip it will add in explore section

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir so should i add these accordions below explore section

**Comment by sanjay-kv** [comment]
No

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir so i am leaving this for now
