### ISSUE TITLE
Remove this GitHub Stats from all the pages. and menu bar

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#1282]
![image](https://github.com/user-attachments/assets/152587cb-f847-428d-bf7f-6ac57b4799e6)

**Comment by sanjay-kv** [comment]
make sure to delete the code base for this as well

**Comment by yashksaini-coder** [comment]
> make sure to delete the code base for this as well

Got it sir, @sanjay-kv
