### ISSUE TITLE
The alignment in the github badge page under certificate changed

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#1286]
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/2ff4cd18-fd12-4851-9f02-613c5c8f52c0">

we should put it back how it was before

**Comment by medss19** [comment]
![image](https://github.com/user-attachments/assets/c8f0d49b-171f-4405-ae71-26ee34c72101)
The alignment seems alright now.

**Comment by sanjay-kv** [comment]
Thanks for letting me know @medss19 

i have seen you started lately contributing to this repository. I would like to say thanks by providing free github profile review. 

https://topmate.io/sanjaykv/1135910

use code: recodehive 
to get it free.
