### ISSUE TITLE
Add Scroll Down Progress Bar to The Recodehive Website

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [recodehive/awesome-github-profiles#131]
Hey @sanjay-kv 

I would like to add a scroll down progress bar to the website

![image](https://github.com/user-attachments/assets/718fabfa-8acf-4788-babc-7f7d3f811212)

Could you please assign this issue to me

**Comment by sanjay-kv** [comment]
already raised

**Comment by RadhikaMalpani1702** [comment]
@sanjay-kv I have checked scroll down progress bar is not raised by anyone the vertical scroll bar is already raised please check and assign this issue to me

**Comment by sanjay-kv** [comment]
I saw that, that would be unnecessary, so we wont be doing it . Sorry, you can find some good idea and raise issue again,
