### ISSUE TITLE
Bug in Signup page (not visible)

### ISSUE THREAD

**Issue by medss19** [recodehive/awesome-github-profiles#1316]
![image](https://github.com/user-attachments/assets/03c6d87e-62e9-4a0f-9f48-90f8627729d2)
before (original code right now)

![image](https://github.com/user-attachments/assets/c1a3fd5c-3ae9-47f4-9825-bfe8d033a855)
after I tried searching up for the signup box using inspect!

**Comment by sanjay-kv** [comment]
Just wanna check are you part of swoc ? @medss19

**Comment by medss19** [comment]
> Just wanna check are you part of swoc ? @medss19

No sir, I haven't applied for SWOC yet, but now that you've mentioned it, I'm considering applying. I recently started exploring open-source projects.

**Comment by sanjay-kv** [comment]
@medss19 thats awesome, i suggest you to apply it, because I can see that your contribution is also good. 
i will help as much as I can in terms of sponsorship and other technical helps.
