### ISSUE TITLE
Style the Vertical Scroll Bar 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [recodehive/awesome-github-profiles#132]
Hey @sanjay-kv 

I would like to style the vertical scroll bar match to the website design theme that is black and white shade 

![image](https://github.com/user-attachments/assets/da3159b5-4d32-40fd-91a3-b3a8956764e6)

Could you please assign this issue to me

**Comment by sanjay-kv** [comment]
already raised this issue
