### ISSUE TITLE
404 - Page Not Found: Missing CODE_OF_CONDUCT.md in gh-pages branch

### ISSUE THREAD

**Issue by AtharvaDomale** [recodehive/awesome-github-profiles#1329]
I encountered a 404 error when trying to access the CODE_OF_CONDUCT.md file. It seems that the file is missing from the gh-pages branch of the awesome-github-profiles repository.

**Comment by sanjay-kv** [comment]
Hi @AtharvaDomale I have assigned this issue to you

**Comment by AtharvaDomale** [comment]
Hi @sanjay-kv, thank you for assigning me this issue. I would like to work on resolving it. I will investigate and restore the missing CODE_OF_CONDUCT.md file in the gh-pages branch. Please let me know if there are any specific requirements for this task.

**Comment by sanjay-kv** [comment]
nothing spesfic you can use the default one.

**Comment by AtharvaDomale** [comment]
Hi @sanjay-kv , please review this PR at your convenience.
