### ISSUE TITLE
Feature:  Want to add the awesome count for each people where peoples can like the profile 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#147]
### Is your feature request related to a problem? Please describe.

Sir i am thinking of adding a feature where people can like the profile if he likes that profile i think with this new user can find and see the best profiles from many profiles 
It will help user to filter out best profiles

**Comment by thevijayshankersharma** [comment]
@sanjay-kv its looking like this 

![image](https://github.com/user-attachments/assets/50cb48e1-ae92-4c4b-8103-57af8de7af24)

**Comment by nishant0708** [comment]
Hey @sanjay-kv sir is loading still there ? Can you send me current rules of realtime database and console for any error.

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/97845752-953f-4020-857a-ffea9a55d5bf)


for me its nothing @nishant0708

**Comment by nishant0708** [comment]
Uhh got that wait i will do that from my end @sanjay-kv

**Comment by sanjay-kv** [comment]
@Ayushmaanagarwal1211 

we can make it new like a instgram simillar like and count near to the view count. This is for people who liked the profile

**Comment by Ayushmaanagarwal1211** [comment]
Yes sir i can make it like instagram but as for now we don't have any authentication for user so that i can handle one like per user  so i will make it like that where user can only do one like per session for now after that if we implement auth then i will change it according to that

**Comment by sanjay-kv** [comment]
sure that works

**Comment by sanjay-kv** [comment]
you can focus on other small task for now, as this I assume will take some time, if you need fireflow access let me know

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir
