### ISSUE TITLE
Feature:  Want to add a filter feature according to the number of views per profile 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#148]
### Is your feature request related to a problem? Please describe.

With this feature user can sort the profiles on the basis of views 

Sir if you want this feature please assign me i will do that after merging nishant's views pr

**Comment by sanjay-kv** [comment]
Making this pending, its a good feature, once the view count is working fine I will update

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/c932b5f7-4504-4fac-a5cf-b587a435ad70)

make sure changes go to gh-page, rather main branch
add a fltter button drop down, 
>most viewed

**Comment by Ayushmaanagarwal1211** [comment]
Ok Sir
