### ISSUE TITLE
Bug:  "Recode Hive" Text Not Visible in Dark Mode on blog + link fix

### ISSUE THREAD

**Issue by thevijayshankersharma** [recodehive/awesome-github-profiles#149]
### Describe the Error

The text "Recode Hive" in the navigation bar on blog.html becomes invisible when dark mode is activated. This issue is likely due to inadequate color contrast between the text and the dark background, making it difficult or impossible to read.

### Expected behavior

The text "Recode Hive" should be clearly visible and easily readable in both light and dark modes. The color of the text should have sufficient contrast against the background to ensure readability in all themes.

### Additional context

![image](https://github.com/user-attachments/assets/a9b9abc0-9dbe-45b4-991b-0e038d989fe8)

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/31c9194d-4df6-4582-83f6-72df4da7430b)


[Uploading RecodeHive Details.pdf…]()
also the blog page link need to correct.
