### ISSUE TITLE
Error: Sidebar links are not working

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#152]
### Describe the Error

facebook: https://www.facebook.com/recodehive
GitHub: https://github.com/recodehive
Linkedin: https://www.linkedin.com/in/sanjay-k-v/
Twitter: https://twitter.com/sanjay_kv_
Youtube: https://www.youtube.com/@RecodeHive

### Additional context
![image](https://github.com/user-attachments/assets/2a071530-eddd-4904-aceb-69bb033da9fb)

**Comment by thevijayshankersharma** [comment]
I would like to do this

**Comment by thevijayshankersharma** [comment]
@sanjay-kv where do you want all these changes  ??

I mean there is already links for it in main branch. Do you want to add links in gh-pages branch.

**Comment by sanjay-kv** [comment]
https://recodehive.github.io/awesome-github-profiles/#

I mean on the deplaoyed page I think its gh page
