### ISSUE TITLE
Error: Dark Mode them is not consistent when enable

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#153]
### Describe the Error

Darkmode keeps turning off when navigating between multiple pages. 

### Expected behavior

When turn on darkmode it should be enabled throughout the session until user turn it off, it should be for single page

### Additional context

![image](https://github.com/user-attachments/assets/7d9cdde2-3251-4b84-87fe-503c2fed020e)

**Comment by thevijayshankersharma** [comment]
I will do this.

**Comment by nishant0708** [comment]
hey @thevijayshankersharma it is also fixed by pr #161  . so sorry for that man Actually these were present in main branch and website was deployed from gh-pages i hope you get it

**Comment by thevijayshankersharma** [comment]
@nishant0708 No worries.

**Comment by sanjay-kv** [comment]
I was wondering why i cant see those changes.
