### ISSUE TITLE
Error: Event page not appearing as expected.

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#156]
### Describe the Error

There should be banner on the event page on the video link listed. 

### Expected behavior

refer what video to add over here. 
https://github.com/recodehive/awesome-github-profiles/issues/101

### Additional context

https://recodehive.github.io/awesome-github-profiles/events.html

![image](https://github.com/user-attachments/assets/e705a70c-8d83-488a-b96d-d9524970c112)

**Comment by nishant0708** [comment]
hey @sanjay-kv can i work on this?

**Comment by nishant0708** [comment]
https://github.com/user-attachments/assets/8c0f9f79-8ef1-4ca8-9566-12453e0b1574

hey @sanjay-kv sir do you want like this ? or it should be image only?
