### ISSUE TITLE
Need a page for Tools 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#157]
![image](https://github.com/user-attachments/assets/53a0ae07-789f-4a5b-b7d4-7e4d26a1f91e)

Now you can see tools is already done 

make an empty page box style.
![image](https://github.com/user-attachments/assets/21edeba2-6a81-4eb1-ac28-353d77bf2c01)

**Comment by nishant0708** [comment]
hey @sanjay-kv can i work on this?

**Comment by sanjay-kv** [comment]
Yes, I saw u requested 3 assigns u can start working on it I will assign after 1 hr . 

Also mention on respective issue u got assigned .
