### ISSUE TITLE
Error:  GitHub Page not working as expected. 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#158]
### Describe the Error

The image is not loading properly

### Additional context
![image](https://github.com/user-attachments/assets/98b7cc3d-5817-4ce2-a75e-437a1b27ece8)

**Comment by nishant0708** [comment]
hey @sanjay-kv fixed that Now

**Comment by nishant0708** [comment]
see pr #161 + please replace this firebase config with yours as soon as possible in gh-pages branch -> retreiveprofile.js

**Comment by nishant0708** [comment]
Hey @sanjay-kv sir please replace firebase config and let me know.. when done thanks

**Comment by sanjay-kv** [comment]
can i connect with you discuss few more things.

**Comment by sanjay-kv** [comment]
https://meet.google.com/axe-ioda-ukym @nishant0708

**Comment by nishant0708** [comment]
Hey sir this meeting I'd is showing no such meeting
