### ISSUE TITLE
Change Text: "Learn GitHub from Scratch"

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#164]
![image](https://github.com/user-attachments/assets/9757019f-e9f0-41f4-a290-f46ad7a827be)

and over bottom add Now take the certification. 
![image](https://github.com/user-attachments/assets/2681b9b4-74d2-4b4c-88c1-a5024e091161)

![image](https://github.com/user-attachments/assets/e7e2d2fb-94c2-4e23-98fb-909481152047)

watch this video
https://www.loom.com/share/8a0c5995f01f40cf8b01baea5138e6eb?sid=5e1d860c-0ee7-4962-9955-c9e65cb82f89

**Comment by Ayushmaanagarwal1211** [comment]
Sir i want to work

**Comment by sanjay-kv** [comment]
can you take this as priority, im planning to launch it on tonights live

**Comment by sanjay-kv** [comment]
there will be more issue coming on this

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv yes sir i almost completed it i will raise pr within 1hr
