### ISSUE TITLE
Remove listing

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#165]
![image](https://github.com/user-attachments/assets/e065c238-692f-4d95-8470-0a22d28046d0)

remove all the highlighted part thats not relevant

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work and sir actually i am not able to see the highlighted part can you please send image again

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i am not able to see the highlighted part can you please send image again with highlighted part

**Comment by sanjay-kv** [comment]
@Ayushmaanagarwal1211 its the entire area in image. the whole thing you see on the image

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir
