### ISSUE TITLE
Create a help Page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#168]
https://webflow.com/made-in-webflow/website/How-it-works-Scroll-into-view

a simple flow like this. I will add content in next issue

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work but i am completing previous task first

**Comment by Asymtode712** [comment]
@Ayushmaanagarwal1211 please complete #106 one too cuz it won't take much time and is important at the moment too as the no of files in that branch are increasing

**Comment by Ayushmaanagarwal1211** [comment]
ok bro will do

**Comment by sanjay-kv** [comment]
@Asymtode712 if you are available can you take some priority work, it doesn't matter whom I assigned to , just take over and finish it, 
+ priority @Ayushmaanagarwal1211 did two recent push those changes went to main page branch, can you push that to gh-page branch

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv ooh srry sir i don't see that i pushed to main  i will push my changes to gh pages from now 
@Asymtode712 Bro if you are free please do that
or i will do that after this

**Comment by Ayushmaanagarwal1211** [comment]
> @sanjay-kv ooh srry sir i  forgot  push the code to the  gh-pages branch i will push my changes to gh pages from now @Asymtode712 Bro if you are free please do that or i will do that after this

**Comment by sanjay-kv** [comment]
nw

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/user-attachments/assets/8df3ca99-ecc8-4999-8a2e-e12199821f5c

@sanjay-kv sir can you please check it

**Comment by sanjay-kv** [comment]
yes. you can PR this to gh-page. i will add the contents to it. 

could you link that to the contact us page as well.

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir i will link this page to content page then will raise pr
