### ISSUE TITLE
Stretched badge views

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#180]
![image](https://github.com/user-attachments/assets/d4b437f8-04b3-41f8-a53d-265b42be49b7)

this should be unique. on laptop view is stretched
https://recodehive.github.io/awesome-github-profiles/githubbadge.html
https://recodehive.github.io/awesome-github-profiles/blog.html

change to be done on both the above view

**Comment by Asymtode712** [comment]
@sanjay-kv I would like to work on this issue

**Comment by sanjay-kv** [comment]
bro could you work on the all open issues as well. as I mentioned before all are priority work

**Comment by sanjay-kv** [comment]
you do fast you get points

**Comment by Asymtode712** [comment]
@sanjay-kv I fix this thing fastly within next 20 mins.....I didn't touched the help page issue as Aayushmaan has built it and has been working on it so it would be unfair for me to grab his job and take up the points which are meant for him
