### ISSUE TITLE
Can we restore the deleted one back 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#181]
https://github.com/recodehive/awesome-github-profiles/pull/171/files

https://recodehive.github.io/awesome-github-profiles/githubbadge.html

**Comment by Asymtode712** [comment]
@sanjay-kv I want to fix this

**Comment by sanjay-kv** [comment]
@Asymtode712 

once you restored 
![image](https://github.com/user-attachments/assets/052a0920-e0c7-4240-96d4-72d9d478b57d)
i only need to remove the highlighted one. 

I created an issue before but I think the user misunderstood and done PRhttps://github.com/recodehive/awesome-github-profiles/issues/165

**Comment by Asymtode712** [comment]
@sanjay-kv Sure sir

**Comment by Asymtode712** [comment]
@sanjay-kv you mean it like this right?


https://github.com/user-attachments/assets/18f331d3-f1a7-4750-9d5d-ad3f60f239ef

**Comment by sanjay-kv** [comment]
yes

**Comment by Asymtode712** [comment]
@sanjay-kv Okay so I am raising a PR now with multiple fixes:

- Removing the main branch content from gh-page
- Proper file structure
- And resolving this issue

**Comment by Asymtode712** [comment]
@sanjay-kv This can be closed now....
