### ISSUE TITLE
pop up page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#183]
![GitHub Profile Review](https://github.com/user-attachments/assets/74135dcd-c650-403f-91c4-093cf20133e1)

https://recodehive.github.io/awesome-github-profiles/blog.html

when they reach last page of the blog page create a pop up : with the above banner which redirect them to 
https://topmate.io/sanjaykv/1135910

similar to the gssoc one

**Comment by Ayushmaanagarwal1211** [comment]
Sir can i work on that

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/user-attachments/assets/9c2d05e2-4bb6-40ed-b80c-e86591d0cec9

sir can you please check

**Comment by yashwanths814** [comment]
https://github.com/all-contributors please add @yashwanths814 for review
