### ISSUE TITLE
Add Profile: Vansh Chaurasiya

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#196]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![screencapture-github-vansh-codes-2024-08-08-01_30_53](https://github.com/user-attachments/assets/c9aab3fc-47bf-493e-ac4f-c39b2d7aa6c1)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [X] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by sanjay-kv** [comment]
@all-contributors add @vansh-codes for review

**Comment by vansh-codes** [comment]
> @all-contributors add @vansh-codes for review

Thank you sir for selecting my Profile 😊
