### ISSUE TITLE
Error: Tools Option in Header Not Working

### ISSUE THREAD

**Issue by HimanshuGitCode** [recodehive/awesome-github-profiles#206]
### Describe the Error
The "Tools" option in the header of the RecodeHive Awesome GitHub Profiles website is not functioning. When clicking on the "Tools" link, nothing happens, and no page or dropdown menu is displayed.

### Expected behavior

When clicking on the "Tools" option in the header, I expect it to either redirect to a new page with tools-related content or display a dropdown menu with various tool options.

### Additional context

1. The issue occurs on the homepage as well as other pages of the website.
2. I have tried accessing the website on different browsers and devices, and the issue persists.
3. Link to the website: [RecodeHive Awesome GitHub Profiles](https://recodehive.github.io/awesome-github-profiles/index.html)

![Screenshot (1256)](https://github.com/user-attachments/assets/8ae12d06-5b80-4ee8-940a-b4641b1e2523)

**Comment by sanjay-kv** [comment]
Could you check any tool related page is already existing if not can you create one.

**Comment by HimanshuGitCode** [comment]
Working on this I will rase PR as soon as possible.
