### ISSUE TITLE
Error: "Add Profile" Button in Header Not Working

### ISSUE THREAD

**Issue by HimanshuGitCode** [recodehive/awesome-github-profiles#207]
### Describe the Error

The "Add Profile" button in the header of the RecodeHive Awesome GitHub Profiles website is not functioning. When clicking on the "Add Profile" button, nothing happens, and no action is triggered.

### Expected behavior
When clicking on the "Add Profile" button in the header, I expect it to either redirect to a new page where users can submit their profiles or open a form or modal to add a profile.

### Additional context

1. The issue occurs on the homepage as well as other pages of the website.
2. I have tried accessing the website on different browsers and devices, and the issue persists.
3. Link to the website: [RecodeHive Awesome GitHub Profiles](https://recodehive.github.io/awesome-github-profiles/index.html)

![Screenshot (1257)](https://github.com/user-attachments/assets/a37192ee-8357-4601-8d52-3c5ddc250222)

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/awesome-github-profiles/issues/new?assignees=&labels=%E2%9E%95+profile&projects=&template=add_profile.md&title=Add+Profile%3A+


can you link to the above link.

**Comment by Asymtode712** [comment]
@HimanshuGitCode @sanjay-kv Actually I have already raised an issue regarding this #195 and will be raising a PR for it shortly
