### ISSUE TITLE
Feature: Reveal elements on scroll

### ISSUE THREAD

**Issue by Anjaliavv51** [recodehive/awesome-github-profiles#213]
### Is your feature request related to a problem? Please describe.
No

### Feature Description

Gradually displays content as the user scrolls down the page
Enhances user engagement and visual appeal
Customizable animation effects (fade in, slide in, etc.)

Feature will be add to all the pages.

**Comment by Anjaliavv51** [comment]
@sanjay-kv Sir can i work on that

**Comment by sanjay-kv** [comment]
I will put for pending this one.

**Comment by Anjaliavv51** [comment]
> I will put for pending this one.

Y sir?

**Comment by sanjay-kv** [comment]
can you provide a sample, what development look like

**Comment by Anjaliavv51** [comment]
> can you provide a sample, what development look like

Okay sir

**Comment by Anjaliavv51** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/b1a82dc7-267e-4721-bd2b-40498ca81b6b


Here is sample video sir @sanjay-kv

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir y this issue has been closed?

**Comment by sanjay-kv** [comment]
accidently did that

**Comment by Anjaliavv51** [comment]
> accidently did that

Okay sir

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir below json code has syntax errors below

![image](https://github.com/user-attachments/assets/7f052e90-a693-4828-ada0-74d625073405)

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir below json code has syntax errors below

![image](https://github.com/user-attachments/assets/7f052e90-a693-4828-ada0-74d625073405)


instead code should be like below

{
      "login": "Anjaliavv51",
      "name": "Lakshmi Pavananjali",
      "avatar_url": "https://avatars.githubusercontent.com/u/154777864?v=4",
      "profile": "https://bento.me/anjali-pamidi",
      "contributions": [
        "review"
      ]
    },{
      "login": "Skb08",
      "name": "Suraj Kumar Behera",
      "avatar_url": "https://avatars.githubusercontent.com/u/113046759?v=4",
      "profile": "https://github.com/Skb08",
      "contributions": [
        "review"
      ]
    },
    {
      "login": "ratnesh-maurya",
      "name": "Ratnesh Maurya",
      "avatar_url": "https://avatars.githubusercontent.com/u/85143283?v=4",
      "profile": "https://g.dev/ratnesh",
      "contributions": [
        "review"
      ]
    },
    {
      "login": "yashwanths814",
      "name": "Yashwanth S",
      "avatar_url": "https://avatars.githubusercontent.com/u/123622523?v=4",
      "profile": "https://linktr.ee/yashwanths814",
      "contributions": [
        "review"
      ]
    }
  ],

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir


instead code should be like below

{
      "login": "Anjaliavv51",
      "name": "Lakshmi Pavananjali",
      "avatar_url": "https://avatars.githubusercontent.com/u/154777864?v=4",
      "profile": "https://bento.me/anjali-pamidi",
      "contributions": [
        "review"
      ]
    },{
      "login": "Skb08",
      "name": "Suraj Kumar Behera",
      "avatar_url": "https://avatars.githubusercontent.com/u/113046759?v=4",
      "profile": "https://github.com/Skb08",
      "contributions": [
        "review"
      ]
    },
    {
      "login": "ratnesh-maurya",
      "name": "Ratnesh Maurya",
      "avatar_url": "https://avatars.githubusercontent.com/u/85143283?v=4",
      "profile": "https://g.dev/ratnesh",
      "contributions": [
        "review"
      ]
    },
    {
      "login": "yashwanths814",
      "name": "Yashwanth S",
      "avatar_url": "https://avatars.githubusercontent.com/u/123622523?v=4",
      "profile": "https://linktr.ee/yashwanths814",
      "contributions": [
        "review"
      ]
    }
  ],
