### ISSUE TITLE
Add Profile: Meet Jain 

### ISSUE THREAD

**Issue by Meetjain1** [recodehive/awesome-github-profiles#214]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

![screencapture-github-Meetjain1-2024-08-08-00_20_01](https://github.com/user-attachments/assets/e4c0fd5d-57ee-4367-a175-84b7bd8916ef)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by nishant0708** [comment]
@Meetjain1 please add ""@all-contributors please add @<username> for review"" this comment

**Comment by Meetjain1** [comment]
@all-contributors please add @Meetjain1 for review
