### ISSUE TITLE
Feature: Create Seperate html css and js files

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#22]
Create Seperate html css and js files so that code can be more readable

**Comment by sanjay-kv** [comment]
doable.

**Comment by sanjay-kv** [comment]
https://zzetao.github.io/awesome-github-profile/

right now i copied the code base from here, we will eventually modify everything, but i liked the idea of scrolling profile instead of dispalying user dp . 
can we implement that?

**Comment by nishant0708** [comment]
@sanjay-kv yes its doable but we need to ask contributor for ss of their profile 

https://vosovyapar.com/

![image](https://github.com/user-attachments/assets/0012458f-c689-470a-8f12-6c8e3db024d6)
Checkout these template its similar but not gif

**Comment by sanjay-kv** [comment]
I will merge one my Profile after sometime, thats a long screenshot, see thats working or not.

**Comment by nishant0708** [comment]
yaa okay @sanjay-kv
