### ISSUE TITLE
Feature:  Want to add video in the event page as in GSSOC website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#222]
### Is your feature request related to a problem? Please describe.

I want to add a video placeholder as in gssoc website 

![image](https://github.com/user-attachments/assets/67c8f949-6277-4c7f-a949-c25acb0e3453)

**Comment by nishant0708** [comment]
hey @Ayushmaanagarwal1211 it is already assigned it to me ...so can you please close issue .

**Comment by Ayushmaanagarwal1211** [comment]
Ok bro
