### ISSUE TITLE
Error:  Extra scroll in popup

### ISSUE THREAD

**Issue by hars-21** [recodehive/awesome-github-profiles#229]
### Describe the Error

Under learn page, when we scroll to bottom a popup appears and it has separate scrollbar.

### Expected behavior

The scrollbar can be removed and align the popup in the center.

### Additional context

![Screen Shot 2024-08-08 at 4 09 28 PM](https://github.com/user-attachments/assets/d66de7cb-4dfd-442e-84ad-c87c9fdde8bc)

@sanjay-kv Please assign me under Gssoc 24

**Comment by hars-21** [comment]
@sanjay-kv Why this was closed

**Comment by sanjay-kv** [comment]
My bad you can work on it.
