### ISSUE TITLE
Error:  visibility in dark mode

### ISSUE THREAD

**Issue by hars-21** [recodehive/awesome-github-profiles#230]
### Describe the Error

In the github badge page, the headings are not visible in dark mode. 

### Expected behavior

The headings and all the text should be clear and visible. 

### Additional context

![Screen Shot 2024-08-08 at 4 10 42 PM](https://github.com/user-attachments/assets/fa0f88c2-a956-43bb-abda-336f66b42add)
![Screen Shot 2024-08-08 at 4 10 47 PM](https://github.com/user-attachments/assets/8aa40c23-5b30-4dcc-9098-42826a754d32)
![Screen Shot 2024-08-08 at 4 10 52 PM](https://github.com/user-attachments/assets/d94751be-352f-4f7a-acfa-0c540aac3d86)
![Screen Shot 2024-08-08 at 4 10 57 PM](https://github.com/user-attachments/assets/b9209fb0-3a59-4891-a554-7d57fd4b019e)

@sanjay-kv Please assign it to me under gssoc

**Comment by hars-21** [comment]
@sanjay-kv I was working on it. Why it was closed

**Comment by sanjay-kv** [comment]
My bad. you can continue working on it.
