### ISSUE TITLE
Feature:  Want to add a tilt effect on the image where user can interact with the image 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#232]
### Is your feature request related to a problem? Please describe.

I want to add a tilt effect on the image which makes website more attractive 

![image](https://github.com/user-attachments/assets/3eaec221-f7a1-49ee-8281-9d614a74eea7)

**Comment by sanjay-kv** [comment]
Good UI feature idea
