### ISSUE TITLE
Feature: Add a Preloader Across all the pages 

### ISSUE THREAD

**Issue by MastanSayyad** [recodehive/awesome-github-profiles#238]
Hey @sanjay-kv 

I would like to add preloaders across all the pages to make user loading more interactive, engaging and improve user experience
-  The preloader will be displayed before the main content is fully loaded, ensuring that users see a loading animation or graphic instead of a blank or incomplete page

### Here are some of my work samples for your reference:

https://github.com/user-attachments/assets/bfb66807-51ff-4c40-9092-1b9fa0138305

https://github.com/user-attachments/assets/59e674d7-88cb-4bca-9765-291e99467f68

https://github.com/user-attachments/assets/c33f2566-4b43-47d3-88d2-d48226da13df

### Context 
I will create much more simpler preloader which will match to the websites theme

**Comment by sanjay-kv** [comment]
Dont work on this , @MastanSayyad As the loading speed is really high i dont think we might need this.
