### ISSUE TITLE
Compare Feature not working

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#241]
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/520d3a2f-dc2d-4091-9ba2-9278c3a745b4">

**Comment by nishant0708** [comment]
Hey @sanjay-kv sir can I try it?

**Comment by sanjay-kv** [comment]
Yes please

**Comment by dinxsh** [comment]
![image](https://github.com/user-attachments/assets/7548e5f3-1664-44f0-9d3d-1c73b51cbbda)
@nishant0708 could you have a look

**Comment by vansh-codes** [comment]
Hello @sanjay-kv sir, I can help fixing this issue

**Comment by sanjay-kv** [comment]
@vansh-codes this is great, i will be sponsor you soon. 

try check gh-pages, there is the place you need to make commits

**Comment by vansh-codes** [comment]
> @vansh-codes this is great, i will be sponsor you soon. 
> 
> try check gh-pages, there is the place you need to make commits
> 
> ![image](https://github.com/user-attachments/assets/ef1c256c-e75d-4c0a-9632-e2e7bea012b0)
> you can do this from the above website: https://github-compare-rho.vercel.app/
> 

You are saying to display this kind of graph? Dod i get it right?

**Comment by sanjay-kv** [comment]
ignore the image "BRO sanjay Do yu...." we don't need that this graph helps

**Comment by sanjay-kv** [comment]
you need PAT, i can create one and give to you now

**Comment by vansh-codes** [comment]
Yes that would be great! 
Also do tick this check boxes
![image](https://github.com/user-attachments/assets/3ffbc24c-0313-4962-8693-b173f0c56a76)

To clear you once again, your PAT would get public because it needs to be added here in the code ⬇️ 
![image](https://github.com/user-attachments/assets/1507b6bc-c282-45c9-aa53-b579298687d3)
