### ISSUE TITLE
Can we replace the navbar position: Add Profile appear after the GitHub BAdge

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#243]
<img width="712" alt="image" src="https://github.com/user-attachments/assets/c5d8351f-5f9c-417c-9f3a-f028b7fbc6b3">

**Comment by Ayushmaanagarwal1211** [comment]
Sir I want to work

**Comment by hars-21** [comment]
Please assign it to me

**Comment by sanjay-kv** [comment]
@Ayushmaanagarwal1211 i made a mistake 

It should be after GitHub badge. can you make these changes and do pr. 

Sorry about that.

**Comment by Ayushmaanagarwal1211** [comment]
Yes sir i am doing placing add profile after github badge
