### ISSUE TITLE
Event PAge

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#246]
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/0e585e77-407d-46fc-afea-c070a60a3a18">

Event page links are wrong, use the below links. 
Video 1: https://www.youtube.com/watch?v=AtoVNe1mVUA&t=792s

Video 2: https://www.youtube.com/watch?v=Rm2lT9j6VxQ&t=522s

Video 3: https://www.youtube.com/watch?v=rNF66FCLmYM

+ can we use this transition?
https://recodehive.github.io/awesome-github-profiles/pages/help.html

<img width="319" alt="image" src="https://github.com/user-attachments/assets/e053cb2e-bdc3-4855-b2dd-098c88b4a602">
add this as well.

**Comment by Ayushmaanagarwal1211** [comment]
Sir I want to work
