### ISSUE TITLE
Feature:  Want to add toast notification for any event 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#259]
### Is your feature request related to a problem? Please describe.

I want to add a toast notification for any event like when user likes the profile so we can show toast or saves the blog 

https://github.com/user-attachments/assets/a4087f4f-2a90-415b-892f-f9bd63a06c71

**Comment by sanjay-kv** [comment]
cany see your video

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/user-attachments/assets/8df159f9-5d67-4099-a3fb-8c0310a44490

@sanjay-kv sir this type of toast

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/5858318b-140c-494e-b76f-8dda68d64c7d)
video not available

**Comment by Ayushmaanagarwal1211** [comment]
![image](https://github.com/user-attachments/assets/d50f07ca-8f67-4bd4-b1b9-5633267ac50d)
@sanjay-kv sir their may be any problem but i am talking about this type of toast

**Comment by sanjay-kv** [comment]
You can do it

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir
