### ISSUE TITLE
Feature: I want to add loading animation on gtihub profiles when they loads.

### ISSUE THREAD

**Issue by vishanurag** [recodehive/awesome-github-profiles#268]
### Is your feature request related to a problem? Please describe.
- Currently when the profile screenshot images loads, it loads from top to bottom.
- This does not give a good user-experience to the user.

### Describe the solution you'd like
- I want to add loading animation on gtihub profiles when they loads.
- After the images loads then the loading animation will be removed.

## Currently:

https://github.com/user-attachments/assets/2960837c-c9d6-4860-97c4-ac0eb1cdf44a

## Loading Feature:

https://github.com/user-attachments/assets/75b94115-2a98-4ae5-b1c4-51620179b11f

@sanjay-kv @dinxsh please assign this issue to me.

**Comment by sanjay-kv** [comment]
do you have anyother animation option

**Comment by vishanurag** [comment]
We can use other animations like these:

Loading 1:

https://github.com/user-attachments/assets/7ccd23aa-edd6-4ff1-9340-1452a29958a8

Loading 2:

https://github.com/user-attachments/assets/cc4192b1-7f77-481b-ac3c-cc7ab78cc0d2

Loading 3:

https://github.com/user-attachments/assets/3594309d-eda9-4390-8c3a-28f3379afad8


Loading 4:

![_______](https://github.com/user-attachments/assets/992bf41e-15fe-4e7a-a0f4-833d49fa0a4d)



<br><hr>

I think Loading-3 might be a good fit for our website since it matches with the website's colours

**Comment by vishanurag** [comment]
> do you have anyother animation option

@sanjay-kv sir 3rd one  (Loading 3) is looking a good fit according to me.

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/c60f3152-40a2-4109-bdf8-eed212ea696b)
this works

**Comment by vishanurag** [comment]
> ![image](https://private-user-images.githubusercontent.com/30715153/356699167-c60f3152-40a2-4109-bdf8-eed212ea696b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjU2MjAsIm5iZiI6MTcyMzIyNTMyMCwicGF0aCI6Ii8zMDcxNTE1My8zNTY2OTkxNjctYzYwZjMxNTItNDBhMi00MTA5LWJkZjgtZWVkMjEyZWE2OTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNmVkZDc5ODVjZWRmZjA0YzhmZjk1ZjVkZDBmMjIyMWM4YmI5YThhYjJkNjAzZmRmZDRmZjFkMDRhYTdhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSmOqfwDG5Gf36ECeVEXNDytsw8efLcfkzra7c0qBhA) this works

Ok I will add this animation.
