### ISSUE TITLE
Feature: Want to create a feature to unsave the blog 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#275]
### Is your feature request related to a problem? Please describe.

I have created a feature for save the blog but now i want to create a feature for unsave the blog so that if user don't want that blog so it should be unsaved

**Comment by dinxsh** [comment]
so delete a blog?

**Comment by Ayushmaanagarwal1211** [comment]
> so delete a blog?

@dinxsh can say but deleting a blog from read later page not from main page
