### ISSUE TITLE
Feature: Want to add cursor pointer for dark mode icon 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#277]
### Is your feature request related to a problem? Please describe.

I want to add the cursor pointer for the dark mode icon 

![image](https://github.com/user-attachments/assets/4c309f72-cdea-49b2-a3a5-04498e241524)

**Comment by dinxsh** [comment]
what cursor @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/user-attachments/assets/0bd3343d-8871-4bd9-963c-864ac6c18b44

@dinxsh please see the video like when i am hovering on other link then the mouse cursor i changing to the hand shape but on hovering on mode icon it will not change .
