### ISSUE TITLE
Feature: Want to make scrollable profile image where 

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#30]
![Screenshot 2024-08-01 090305](https://github.com/user-attachments/assets/bc50a43b-d4fb-4cd1-840c-499bf0b13459)
something like this

**Comment by nishant0708** [comment]
hey @sanjay-kv sir we can also maintain the count of visits to that particular profile . if you like this idea then let me know

**Comment by sanjay-kv** [comment]
Mate, thats awesome, 
in future we can sort based on views as well

**Comment by nishant0708** [comment]
> Mate, thats awesome, in future we can sort based on views as well

yaa then i will  figure out how to store visitor count.

**Comment by nishant0708** [comment]
https://github.com/user-attachments/assets/1f038b6c-f9f9-4def-a28e-3e8a59c7cea2

hey @sanjay-kv sir i have made it but for this we have to store SS of user profile in screenshot folder with login name of user and then add a field in raw json as  Screenshot  which will have path of image 

i Saw you have Created Some function in main for taking screenshot but i guess its not working 

So what should we do this for this screenshot path thing let me know

**Comment by nishant0708** [comment]
hey @dinxsh  @sanjay-kv sir please checkout above comment as well and let me know how can we store that screenshots of user

**Comment by sanjay-kv** [comment]
@nishant0708 The above one is good, but is there anyway we automate this process. I hope there is nothing manual should be done from our side, 

When many users add their profile in the future, if we follow manual process it would be tiring. 
We can go ahead with the above idea.

**Comment by nishant0708** [comment]
> @nishant0708 The above one is good, but is there anyway we automate this process. I hope there is nothing manual should be done from our side,
> 
> When many users add their profile in the future, if we follow manual process it would be tiring. We can go ahead with the above idea.

hey @sanjay-kv sir yaa i also wanted to that only but  allcontributor bot is making thing automated right so just let me know how can i configure its scripting

**Comment by sanjay-kv** [comment]
I'm tagging @dinxsh to help with scripting. As he done that part .

**Comment by dinxsh** [comment]
> > @nishant0708 The above one is good, but is there anyway we automate this process. I hope there is nothing manual should be done from our side,
> > When many users add their profile in the future, if we follow manual process it would be tiring. We can go ahead with the above idea.
> 
> hey @sanjay-kv sir yaa i also wanted to that only but allcontributor bot is making thing automated right so just let me know how can i configure its scripting

hi nishant, I've dm'd you on discord to explain further how you can seamlessly integrate the current script with your code!
