### ISSUE TITLE
Error: There are duplicate links present on navbar of exploremore page.

### ISSUE THREAD

**Issue by vishanurag** [recodehive/awesome-github-profiles#304]
### Describe the Error
- There are duplicate links present on navbar of exploremore page.

### Expected behavior
- These duplicate links need to be removed because they sometimes confuse user.

### Additional context

![image](https://github.com/user-attachments/assets/6e14d76c-773b-405d-85f3-100eea7edbb7)

@sanjay-kv @dinxsh please assign this issue to me.

**Comment by vishanurag** [comment]
@sanjay-kv sir please also assign this issue to me.

**Comment by dinxsh** [comment]
completed
