### ISSUE TITLE
Error in Popup

### ISSUE THREAD

**Issue by hars-21** [recodehive/awesome-github-profiles#305]
### Describe the Error

The popup in blogs page is not aligned

### Expected behavior

Alignment and remove animation from popup

### Additional context

![Screen Shot 2024-08-10 at 5 08 20 PM](https://github.com/user-attachments/assets/7c837b54-eddb-46ef-a378-9b0c639a27b8)
![Screen Shot 2024-08-10 at 5 08 23 PM](https://github.com/user-attachments/assets/79e1febb-44c6-491c-8ced-a41d98e37e58)
![Screen Shot 2024-08-10 at 5 08 25 PM](https://github.com/user-attachments/assets/293c4b42-0722-46b4-8a5d-2517b50d3fc0)

**Comment by sanjay-kv** [comment]
not required
