### ISSUE TITLE
Error: event timeline animation

### ISSUE THREAD

**Issue by hars-21** [recodehive/awesome-github-profiles#306]
### Describe the Error

The animation for events timeline is bugged

### Expected behavior

Fix the animation and remove those blue boxes

### Additional context

![Screen Shot 2024-08-10 at 5 10 20 PM](https://github.com/user-attachments/assets/b00eb5b8-049f-451e-960c-b0e6481ddb43)
![Screen Shot 2024-08-10 at 5 10 30 PM](https://github.com/user-attachments/assets/3a7c3090-f0a7-4e83-8c3b-ff847118dbe0)

**Comment by sanjay-kv** [comment]
are you working on this. 

I know gssoc is over im looking for collaborators rn. will be sponsering best one every fortnight.

**Comment by hars-21** [comment]
Hey @sanjay-kv , this issue has been resolved with #307 PR. As for contributing, I'm interested and want to contribute.
