### ISSUE TITLE
Feature: Want to highlight the Option when hovering 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#31]
### Is your feature request related to a problem? Please describe.

I want to highlight the option while hovering on the option 
Like i will change its background color to some dark so that it will looks like different from other options 

https://github.com/user-attachments/assets/fb86ded3-2aad-44f9-a7c9-5aff669ecba9

**Comment by sanjay-kv** [comment]
Make sure not to add high animation, a simple hovering animation will do.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv ok sir I will add basic hovering effect
