### ISSUE TITLE
Pallavi-star2002

### ISSUE THREAD

**Issue by Pallavi-star2002** [recodehive/awesome-github-profiles#317]
## Profile Submission

![github com_Pallavi-star2002(iPad Pro)](https://github.com/user-attachments/assets/6134d608-2069-4a5c-9e3b-f2b04857a5c3)

### Profile Category
Please select one or more categories for your profile:

- [x] Badge 🎖️
- [x] Minimalistic ✨
- [ ] Dynamic 🔄
- [x] Icons 🎯
- [x] Backgrounds 😎
- [ ] GIFS 🖼️
- [ ] Game Mode 🚀
- [x] Code 👨‍💻

### Next Steps

Once you've filled out the information, please comment below:

@all-contributors please add @Pallavi-star2002  for review

**Comment by sanjay-kv** [comment]
@all-contributors please add @Pallavi-star2002 for review
