### ISSUE TITLE
Add Profile: Hemashree M S

### ISSUE THREAD

**Issue by Hemashree21** [recodehive/awesome-github-profiles#323]
## Profile Submission

![image](https://github.com/user-attachments/assets/7fdbbd67-4642-4b01-aba4-247417d9e5c0)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

``@Hemashree21``

 ``@all-contributors please add @<username> for review``

**Comment by sanjay-kv** [comment]
you have to use go full page chrome extenstion to put long screenshot.
