### ISSUE TITLE
Add Profile: coder-writes 

### ISSUE THREAD

**Issue by coder-writes** [recodehive/awesome-github-profiles#324]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by sanjay-kv** [comment]
You have to paste the long screenshot of your profile.
