### ISSUE TITLE
Add Profile: prudhvi_232

### ISSUE THREAD

**Issue by Prudhvi-232** [recodehive/awesome-github-profiles#328]
## Profile Submission

![image](https://github.com/user-attachments/assets/e8c169be-393d-4657-bfbd-79b245a86869)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by Prudhvi-232** [comment]
@all-contributors please add @<username> for review

**Comment by Prudhvi-232** [comment]
@all-contributors please add @<prudhvi-232> for review

**Comment by Prudhvi-232** [comment]
@all-contributors please add @<Prudhvi-232> for review

**Comment by sanjay-kv** [comment]
Hi you need to use go full page extenstion and take a long screenshot to the issue. maybe you can do it again, i will help you with it.
