### ISSUE TITLE
Add Profile:  G Avineshwar 81 rank in GSSOC 2024

### ISSUE THREAD

**Issue by GAVINESHWAR** [recodehive/awesome-github-profiles#329]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

![image](https://github.com/user-attachments/assets/e5def247-d8f2-4927-aee9-3f48fdbd2a5f)

### Profile Category
Please select one or more categories for your profile:

- [X] <span class="tag">Badge 🎖️</span>
- [X] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [X] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [X] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [X] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

please add @GAVINESHWAR

**Comment by sanjay-kv** [comment]
You need to use Go full page chrome extention and do it with long screenshot.
