### ISSUE TITLE
Add Profile: Soumilgit

### ISSUE THREAD

**Issue by Soumilgit** [recodehive/awesome-github-profiles#331]
## Profile Submission

![Screenshot 2024-08-12 212145](https://github.com/user-attachments/assets/0f082f88-905a-4260-8deb-bf3f7778763f)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by Soumilgit** [comment]
@all-contributors please add @Soumilgit  for review

**Comment by sanjay-kv** [comment]
you need to use go full page chrom extension and add screenshot again
