### ISSUE TITLE
Add Profile: Sumiththota Profile

### ISSUE THREAD

**Issue by SumithThota** [recodehive/awesome-github-profiles#334]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![github com_SumithThota (3)](https://github.com/user-attachments/assets/88a8499e-db2a-4e45-a39d-2647168559ec)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [X] <span class="tag">Minimalistic ✨</span>
- [X] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [X] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [X] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

@Sumiththota

 ``@all-contributors please add @<username> for review``

**Comment by sanjay-kv** [comment]
@all-contributors please add @SumithThota for review
