### ISSUE TITLE
Add Profile: Krish3914

### ISSUE THREAD

**Issue by Krish3914** [recodehive/awesome-github-profiles#342]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![image](https://github.com/user-attachments/assets/2e806297-75c0-4307-85f5-87c58e7af691)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by sanjay-kv** [comment]
@all-contributors please add @Krish3914 for review

**Comment by Krish3914** [comment]
Thank you very much.
How can I access to that
