### ISSUE TITLE
Add Profile: Please Add my Profile on Recodehive.

### ISSUE THREAD

**Issue by vishal02527** [recodehive/awesome-github-profiles#354]
## Profile Submission

![Screenshot 2024-08-13 221750](https://github.com/user-attachments/assets/cd9c4760-f507-42fd-a590-96de11d12f77)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Code 👨‍💻</span>

@sanjay-kv Please add my profile into your database.

**Comment by sanjay-kv** [comment]
@all-contributor add @vishal02527 profile

**Comment by sanjay-kv** [comment]
you have to provide a long screenshot of your profile. use go full page chrom extension and resubmit it
