### ISSUE TITLE
Add Profile: Recodehive

### ISSUE THREAD

**Issue by harsh02mishra** [recodehive/awesome-github-profiles#356]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![harsh02mishra-Harsh-Mishra-](https://github.com/user-attachments/assets/d929b13d-839b-429e-9d73-7a00b13848da)

### Profile Category
Please select one or more categories for your profile:

- [X] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [X] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [X] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

@sanjay-kv please review it.

**Comment by sanjay-kv** [comment]
@all-contributors review @harsh02mishra

**Comment by sanjay-kv** [comment]
@all-contributors please add @harsh02mishra  for review
