### ISSUE TITLE
Refactor: Nav-links

### ISSUE THREAD

**Issue by hars-21** [recodehive/awesome-github-profiles#358]
### Describe the Error

There are some broken links in navbar in mobile view.
Also in events page, there are 2 links redirecting to same page.

### Expected behavior

Fix the broken links and removing repeated links

### Additional context

![Screen Shot 2024-08-14 at 9 30 31 PM](https://github.com/user-attachments/assets/c36413a5-2970-4691-8702-c0e59b207be3)
![Screen Shot 2024-08-14 at 9 31 02 PM](https://github.com/user-attachments/assets/dcdcb850-a736-47ed-a442-1d141c57e5c5)

**Comment by sanjay-kv** [comment]
This would be great addition
