### ISSUE TITLE
Add Profile: GarimaSingh0109

### ISSUE THREAD

**Issue by GarimaSingh0109** [recodehive/awesome-github-profiles#380]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by dinxsh** [comment]
@all-contributors please add @GarimaSingh0109  for review
