### ISSUE TITLE
Add Profile: Bhavishya2601

### ISSUE THREAD

**Issue by Bhavishya2601** [recodehive/awesome-github-profiles#382]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![Screenshot 2024-08-15 224444](https://github.com/user-attachments/assets/afd69315-a318-4c12-a21d-53c0757f5f32)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @bhavishya2601 for review``

**Comment by dinxsh** [comment]
@all-contributors please add @bhavishya2601 for review
