### ISSUE TITLE
Add Profile: VaibhavArora314

### ISSUE THREAD

**Issue by VaibhavArora314** [recodehive/awesome-github-profiles#385]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![image](https://github.com/user-attachments/assets/46fcd8ab-1f21-43e2-8f86-fe812b7e8862)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by VaibhavArora314** [comment]
@all-contributors please add @VaibhavArora314 for review

**Comment by sanjay-kv** [comment]
@VaibhavArora314 we need long screenshot for this, you can use go full page extension. and apply again.
