### ISSUE TITLE
Add Profile: tusquake

### ISSUE THREAD

**Issue by tusquake** [recodehive/awesome-github-profiles#408]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by tusquake** [comment]
@all-contributors please add @tusquake for review

**Comment by sanjay-kv** [comment]
your profile picture is missing, i recommend to add the ss of your profile and raise it again.
