### ISSUE TITLE
Add Profile: 

### ISSUE THREAD

**Issue by Yeasir0032** [recodehive/awesome-github-profiles#410]
## Profile Submission

![Screenshot_20240816_095027_Chrome.jpg](https://github.com/user-attachments/assets/1ff61049-7017-4c21-8700-dcf4c08b277b)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add  me  for review``

**Comment by dinxsh** [comment]
@all-contributors please add @Yeasir0032 for review
