### ISSUE TITLE
Add Profile: pooranjoyb

### ISSUE THREAD

**Issue by pooranjoyb** [recodehive/awesome-github-profiles#412]
## Profile Submission

Please paste a screenshot of your GitHub profile here.

![image](https://github.com/user-attachments/assets/20a791ec-8c95-408b-b2b1-b20c8315fc38)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by pooranjoyb** [comment]
@all-contributors please add @pooranjoyb for review

**Comment by sanjay-kv** [comment]
We need a long screenshot on the profile, try to use Go Fullpage option and try it again.
