### ISSUE TITLE
➕Feature: Adding Diagonal-Transitional Effect to "Each Profile Card"

### ISSUE THREAD

**Issue by aslams2020** [recodehive/awesome-github-profiles#42]
Hey @sanjay-kv 

I want to suggest a new feature for "Contributors" Page.

I Want **to add a "Diagonal-Transitional" Effect Styling to each card** of the Contributors. 
Which means On hovering on Every card, The card will display a Transitional Effect

**For ex.  Like this My prev Work-(I will follow better theme)** 

https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60

**Current Contributor Cards -** 

https://github.com/user-attachments/assets/21249085-46ea-4d81-a951-0c2fc916c9d5

As you can see.

Please Assign me this issue.

**Comment by sanjay-kv** [comment]
i like the transitions, could you share the link of the finveda website.

**Comment by aslams2020** [comment]
@sanjay-kv 
Here is the link : https://fin-veda.vercel.app/contributors.html

**Comment by sanjay-kv** [comment]
I will get back to you,
