### ISSUE TITLE
Add Profile: added varsani2520 github profile

### ISSUE THREAD

**Issue by Varsani2520** [recodehive/awesome-github-profiles#421]
## Profile Submission

![image](https://github.com/user-attachments/assets/4a2a4c37-d00b-454f-8a74-9d78cdd3b762)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

@Varsani2520

**Comment by Sanket-HP** [comment]
Hii... I wish to work on this project. Plase assigne to me.
