### ISSUE TITLE
Add Profile: + Adding 

### ISSUE THREAD

**Issue by SOMNATH0904** [recodehive/awesome-github-profiles#423]
## Profile Submission
![screencapture-github-somnath0904](https://github.com/user-attachments/assets/3d67472f-0dfe-4890-9483-d5a9b496ba91)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

'@all-contributors please add @somnath0904 for review'

**Comment by dinxsh** [comment]
https://github.com/all-contributors please add @SOMNATH0904 for review

**Comment by dinxsh** [comment]
@all-contributors please add @SOMNATH0904 for review
