### ISSUE TITLE
Add Profile: Mayureshd-18

### ISSUE THREAD

**Issue by Mayureshd-18** [recodehive/awesome-github-profiles#429]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![image](https://github.com/user-attachments/assets/deaf08d5-16ba-4051-a77d-40a731be12f3)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by Mayureshd-18** [comment]
@all-contributors please add @Mayureshd-18  for review

**Comment by dinxsh** [comment]
your screenshot is missing, kindly raise the PR again @Mayureshd-18

**Comment by Mayureshd-18** [comment]
@dinxsh how can i provide the screenshot of my whole profile?

**Comment by sanjay-kv** [comment]
use @Mayureshd-18 gofullpage extenstion
