### ISSUE TITLE
Add Profile

### ISSUE THREAD

**Issue by Krishi1211** [recodehive/awesome-github-profiles#436]
## Profile Submission
![image](https://github.com/user-attachments/assets/1cfb21a5-8adf-4062-b707-50367cabd1dd)

Please paste a screenshot of your GitHub profile here.

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by dinxsh** [comment]
@all-contributors please add @Krishi1211 for review
