### ISSUE TITLE
Error: Improvement in website's navbar

### ISSUE THREAD

**Issue by multiverseweb** [recodehive/awesome-github-profiles#445]
### Describe the Error

In the **`Events`** tab of website, the navbar does not contain '**`Add Profile`**' option.

### Expected behavior

The navbar should be the same across all tabs, therefore 'Add Profile' option should be added in Events tab.

### Additional context

None

**Comment by multiverseweb** [comment]
I can't find the file where changes are to be made.

**Comment by dinxsh** [comment]
all code for the website is on`gh-page` branch @multiverseweb
