### ISSUE TITLE
@ujjwalshriv3

### ISSUE THREAD

**Issue by ujjwalshriv3** [recodehive/awesome-github-profiles#461]
@ujjwalshriv3 

@ujjwalshriv3 already contributed before to review

_Originally posted by @allcontributors[bot] in https://github.com/recodehive/awesome-github-profiles/issues/455#issuecomment-2311684259_

why is happing all time bot is not raising my PR Automatically ? how could be merge my PR

![Screenshot 2024-08-24 130723](https://github.com/user-attachments/assets/794083ce-f2a5-4506-8250-9e86ac1fbf26)

**Comment by dinxsh** [comment]
ill look into it

**Comment by ujjwalshriv3** [comment]
Any update @dinxsh

**Comment by dinxsh** [comment]
added your profile

**Comment by ujjwalshriv3** [comment]
> added your profile

Thank you @dinxsh
