### ISSUE TITLE
Feature: Make different pages for all the profiles

### ISSUE THREAD

**Issue by naikmubashir** [recodehive/awesome-github-profiles#464]
### Is your feature request related to a problem? Please describe.
Kind of.

It just becomes so hectic to scroll through all the profiles in one page. Since the number of profiles are increasing and all the profiles are present on a single page

### Describe the solution you'd like

I would suggest adding more pages for just the profiles. 
For each page show only 20 profiles . Rest will be present on page 2,3,4.... which we can navigate via button present at buttom and  top of the profiles. eg.of buttons for pages: **Next Page** , **3** , **4** , **5** , **6**

**Comment by sanjay-kv** [comment]
This is something i was thinking about. you can do the implementation.

**Comment by dinxsh** [comment]
any update @naikmubashir? let me know if you need any help

**Comment by naikmubashir** [comment]
I'm having a hard time understanding the file structure of the project  as there is no particular src directory. Could you please enlighten me with which of the files i need to change or do i need to create an additional for it. @dinxsh

**Comment by sanjay-kv** [comment]
check in the gh-page branch

**Comment by naikmubashir** [comment]
completed in #479
