### ISSUE TITLE
Add Profile: Sambit-Mondal

### ISSUE THREAD

**Issue by Sambit-Mondal** [recodehive/awesome-github-profiles#467]
## Profile Submission

https://github.com/user-attachments/assets/4a2b2f38-f378-4996-8702-d2f972a7eab9

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [x] <span class="tag">Dynamic 🔄</span>
- [x] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [x] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [ ] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 ``@all-contributors please add @<username> for review``

**Comment by Sambit-Mondal** [comment]
@Sambit-Mondal Please review my profile.

**Comment by dinxsh** [comment]
@all-contributors please add @Sambit-Mondal for review

**Comment by dinxsh** [comment]
@all-contributors please add @Sambit-Mondal for review
