### ISSUE TITLE
Error:  The json object should contain profile details on one person in .all-contributorsrc file.

### ISSUE THREAD

**Issue by vishanurag** [recodehive/awesome-github-profiles#47]
### Describe the Error

- These two profiles are in the same object.
- There should be one object per profile in .all-contributorsrc file.
- This error need to be resolved.

![Screenshot_2024-08-04-18-18-50-825_com android chrome-edit](https://github.com/user-attachments/assets/ec9c1605-5c19-42ee-93dc-371d0d252880)

### Expected behavior

- These profiles should be stored in different objects.

### Additional context

@sanjay-kv  sir Please assign this issue to me under GSSoC'24

**Comment by sanjay-kv** [comment]
it happened due to merge conflicts

**Comment by vishanurag** [comment]
I will resolve this.
