### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by naikmubashir** [recodehive/awesome-github-profiles#472]
### Missing .gitignore File

**Description:**

The repository currently lacks a `.gitignore` file, which can lead to unnecessary or sensitive files being committed to version control. It's important to add a `.gitignore` file to exclude files that should not be tracked by Git, such as system files, editor settings, and potential build artifacts.

**Benefit:**

Adding a `.gitignore` file will help keep the repository clean by preventing irrelevant or platform-specific files from being committed. It will also improve collaboration by ensuring everyone has the same exclusions in place, making the repository more maintainable.

**Comment by sanjay-kv** [comment]
good note you can add the same.
