### ISSUE TITLE
Add Profile: 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#477]
## Profile Submission

![screencapture-github-Jisha-tr-2024-09-08-15_32_59](https://github.com/user-attachments/assets/2a4e9fa3-8a1b-4fa2-8944-15930b843538)

### Profile Category
Please select one or more categories for your profile:

- [ ] <span class="tag">Badge 🎖️</span>
- [ ] <span class="tag">Minimalistic ✨</span>
- [ ] <span class="tag">Dynamic 🔄</span>
- [ ] <span class="tag">Icons 🎯</span>
- [ ] <span class="tag">Backgrounds 😎</span>
- [ ] <span class="tag">GIFS 🖼️</span>
- [ ] <span class="tag">Game Mode 🚀</span>
- [x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information, please comment below:

 @all-contributors please add @Jisha-tr for review

**Comment by dinxsh** [comment]
@all-contributors please add @Jisha-tr for review
