### ISSUE TITLE
Need a page named videos

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#509]
A page named videos which is similar to https://gssoc.girlscript.tech/gssoc_academy

**Comment by Jisha-tr** [comment]
i love to work on this can you assign me?

**Comment by iitzIrFan** [comment]
Nice profile, Also would like to take guidance from you for my contributions in GGSOC and build a healthy proessional relationship with you sir

**Comment by dinxsh** [comment]
@Jisha-tr any update?

**Comment by sanjay-kv** [comment]
@dinxsh jisha is my secondary account, i made a demo while making video I will assign to @iitzIrFan

**Comment by coderKrysio** [comment]
hey @sanjay-kv 
can I work on this issue if this is available?

**Comment by coderKrysio** [comment]
hey @dinxsh, a few doubts:
- can you confirm whether I have to make the same UI for the videos page as it has been provided above?
- also the name for the route should be videos or tutorials?
- lastly I have forked the repo but was only able to fork the main branch and since all the code is in gh-pages, should I clone this branch first and then commit in my forked repo?

can you just please help me out

**Comment by sanjay-kv** [comment]
Module 1: Get Start with Git and GitHub
1. What is git and github: https://youtu.be/bFHwtm6FQ4c
2. How to start with GitHub: https://youtu.be/GrTV59Y84S8
3.Understanding the GitHub Flow. https://youtu.be/jE8nqWSbUQs

Module 2: How to make your first commit
4  How to create github repo: https://youtu.be/XWjx-RjmhRM
5. Create repo using command line: https://youtu.be/DO38CZcw5pg
6. How to do your first opensource : https://youtu.be/R7NReLBCT_8
7. How to create opensource commit via CLI: https://youtu.be/QlTrHXmr-JI

Module 3: customise your Github Proofile
8.Make custom github readme page: https://youtu.be/3dnQ2lDNeGI
9.How to customize GitHub profiles:https://youtu.be/ILccFNnQr9s

Module 4: How to get Github Achievments badges
10.How to get github achievements: https://youtu.be/sbyXpflAXkQ
11. How to get Pull shark badge on GitHub: https://youtu.be/7uKMWBFN2jQ
12. How to get Galaxy Brain badge on GitHub: https://youtu.be/v2Pai1TY_Lg
13. How to get Starstruck badge on GitHub: https://youtu.be/P-P3L7YzlyE
14. How to get Quick Draw badge on GitHub: https://youtu.be/BNKSlT8jLQ0
15. How to get Yolo badge on GitHub: https://youtu.be/GnHNScuGKrg
16. How to get pair on GitHub: https://youtu.be/ZoNO_e8PjiM

Module 5: How to activate sponsership on GitHub
17. How to Sponsor developers on GitHub: https://youtu.be/krgKPvWNPLQ
18. How to get GitHub Sponser: https://youtu.be/RSR5E1bhu5Y
19. How to setup GitHub sponser: https://youtu.be/z579SrLdk2I

Module 6:Trouble shoot on account suspension: 
20. GitHub account suspended: https://youtu.be/TvQ1OYRJUe0

21. How to get sponsership Badge" https://youtu.be/dcdpkD7lYDg
22. Understanding GitHub as a Dev Product: https://youtu.be/SLdOYby72LQ
23. How to apply for student developer pack: https://youtu.be/knr5gBv-c9c
24: Hands on GitHub Copilot: AI Assistant on GitHub: https://youtu.be/4JX-SIkM3uk
25: Understanding Github Codespace: https://youtu.be/akz9xHL1RQo
26: How to delete a project repo: https://youtu.be/oyi86CljSk4
27: How to manage a project on github: https://youtu.be/7BL6eInh7qo
28: Inner source and opensource: https://youtu.be/V2nvZYe_q7g
29: GitHub Security : https://youtu.be/DmYe2itxSQA
30: GitHub Administration: https://youtu.be/xdjZ0HXADjE

**Comment by sanjay-kv** [comment]
can u research some gamified ui?

**Comment by coderKrysio** [comment]
> can u research some gamified ui?

this can serve as the module division 
![image](https://github.com/user-attachments/assets/1fd02d9d-9717-4bf7-8cd7-8bc08256f6b2)

and each video can be made into such cards to give clean, modern and easy to use experience
![image](https://github.com/user-attachments/assets/d7d662b4-19a6-45a0-b561-348fee1e0384)

if find these suggestions good then let me know, otherwise I will search for more UI

**Comment by coderKrysio** [comment]
any updates @sanjay-kv ?

**Comment by sanjay-kv** [comment]
https://gssoc.girlscript.tech/postmanChallenge

can we do something like this

**Comment by coderKrysio** [comment]
> https://gssoc.girlscript.tech/postmanChallenge
> 
> can we do something like this
Yeah surely that can be done 
But I will ask for updates and modifications, as it's a page design

Also do I push the code in the gh-pages?

**Comment by sanjay-kv** [comment]
yes

**Comment by coderKrysio** [comment]
hey @sanjay-kv 
https://www.loom.com/share/d240d5d719b1409eb8c45ca8124688a3?sid=da3796ed-9aa5-47e4-ae0b-02b909bf241d
first draft
is this how you want the page?

**Comment by sanjay-kv** [comment]
@coderKrysio This should be fine

**Comment by coderKrysio** [comment]
> @coderKrysio This should be fine

Hey @sanjay-kv,
I am working on the issue, but due to some network problem in my area I was not able to update you
I will follow this design and create the whole UI
And will inform you about the updates soon

**Comment by coderKrysio** [comment]
hey @sanjay-kv 
https://www.loom.com/share/1de87d6fa3dc40ae8657625a80750093?sid=a3dc08b5-dbc0-41bc-9d4b-8386c7c2db55
here is the preview

I have added all the module videos as per given by you
now only styling the sidebar is left
if you want to make any recommendations or changes do let me know

and also do you want the sidebar according to the reference you have provided?
if yes then I will proceed according to that and will create a PR today

**Comment by sanjay-kv** [comment]
this is good.

**Comment by coderKrysio** [comment]
hey @sanjay-kv 
https://www.loom.com/share/03c236101f3c4cea81bd5eb70002488a?sid=581c0fc1-d340-47b0-b80f-03914dfe423d
the finished look
if you want any further changes then let me know
otherwise we can merge these changes
