### ISSUE TITLE
Idea #3: Any page under construction

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#510]
### Discussed in https://github.com/recodehive/awesome-github-profiles/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **sanjay-kv** August  7, 2024</sup>
https://webflow.com/made-in-webflow/website/Construction-Animation</div>

**Comment by vasudhawaman** [comment]
Do you want to add this animation under all pages which are under construction ? I can add a similiar animation .Which pages are currently under construction ?

**Comment by rounakdey6** [comment]
Please assign this issue to me sir

**Comment by Charul00** [comment]
i liked it can i work on this please assign  me sir

**Comment by janhavi7276** [comment]
i would love to work on this issue please assign it .

**Comment by kalyanshnu** [comment]
can you explain what we have to do, like what's the issue.

**Comment by sanjay-kv** [comment]
@vasudhawaman work on the gh-branch. the main code are in there

**Comment by vasudhawaman** [comment]
Sure! Will work on that branch!

**Comment by Shreya-Pandey-01** [comment]
Sir, please assign me this issue, I would love to work on it, and I will also complete it very timely.
