### ISSUE TITLE
Error: The Drop-down Menu [caret-down] don't hide automatically

### ISSUE THREAD

**Issue by FezanMuhammadAli** [recodehive/awesome-github-profiles#511]
**### Description of the Issue**
The drop-down menu on the landing page, with `id="caret-down"`, does not automatically hide when clicking outside of the menu. Currently, the drop-down only hides if the user clicks directly on the caret symbol, which is inconsistent with common behavior on most websites.

https://github.com/user-attachments/assets/bbc57bf7-b484-44cb-a333-46b732457baa

**### Expected Behavior**
The drop-down menu should hide when the user clicks anywhere on the page, whether it's a blank space or another element, ensuring a smoother and more intuitive user experience.

https://github.com/user-attachments/assets/2d447dff-e112-4dc4-88f6-824fd22187eb

Check the issue and expected solution

**Comment by sanjay-kv** [comment]
@sanjay-kv i would like to work on this issue

**Comment by abhip161** [comment]
hey @sanjay-kv  i would like to work on this can you  assign it to me

**Comment by kalyanshnu** [comment]
i would also like to work on this issue.

**Comment by sanjay-kv** [comment]
@FezanMuhammadAli i think the the profile has been crashed due to some issue. can u fix that. 

work on the gh-pages branch

**Comment by Lekkhasri** [comment]
@sanjay-kv i would like to work on this issue can you assign it to me

**Comment by FezanMuhammadAli** [comment]
@sanjay-kv this is a serious issue I just noticed all profiles are gone. you can roll back the deployments and hope it will be fixed.

**Comment by sanjay-kv** [comment]
@FezanMuhammadAli rollback should be last option, could you help me to find which bug making this issue
