### ISSUE TITLE
I want to imporve main page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#515]
the main page profiles are not visible. can you help me to figure it out.

**Comment by rounakdey6** [comment]
Please assign this issue to me . I'm a Full Stack Developer.

**Comment by dinxsh** [comment]
make your own versions of the changes list out what you'll work on individually and we'll work towards a pr @thakuratul2 @rounakdey6

**Comment by sanjay-kv** [comment]
@thakuratul2 https://docs.google.com/spreadsheets/d/1fNNXgLIqSfywHqFe7nVSHgm7FhaxAKi-acOfXjtDv_M/edit?usp=sharing

i dont see your name on the mentor list.

**Comment by thakuratul2** [comment]
@sanjay-kv search my atul Pratap Singh

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/7e44427f-fb39-4509-b669-cca09cb852d9)


i dont see your name on this repo
![image](https://github.com/user-attachments/assets/77188f71-a54b-49d2-9fe5-9bcfeee6f530)

**Comment by HimangshuSharma01** [comment]
@rounakdey6 @thakuratul2 any update regarding this?
