### ISSUE TITLE
Feature:  Add Sticky Navbar for Improved Navigation

### ISSUE THREAD

**Issue by grasyPatel** [recodehive/awesome-github-profiles#532]
### Is your feature request related to a problem? Please describe.

I would like to request the addition of a sticky navbar on the website. This feature would improve navigation by ensuring the menu remains visible at the top of the screen as users scroll down the page. This will enhance user experience, especially on long pages where access to navigation links is crucial.

### Describe the solution you'd like

I am willing to contribute by implementing this feature. The sticky behavior can be achieved using CSS properties such as position: sticky or with JavaScript for full compatibility across browsers.

### Additional context

Benefits of Sticky Navbar:
Provides constant access to important links.
Improves usability on both desktop and mobile devices.
Enhances the overall user experience by reducing the need to scroll back up for navigation.

Screenshot:
<img width="1448" alt="Screenshot 2024-10-01 at 8 41 56 PM" src="https://github.com/user-attachments/assets/96faf5aa-f8ef-4096-9131-9409f953e882">

**Comment by grasyPatel** [comment]
Could you please assign this task to me? I have experience working on similar issues in the past and would love to help resolve this one. Thank you!

**Comment by prachichoudhary2004** [comment]
I would like to work on this issue . i have a good hold on html , css and js and would like to implement it to make this better

**Comment by sanjay-kv** [comment]
@grasyPatel isnt the sticky nav bar already available?

**Comment by grasyPatel** [comment]
@sanjay-kv it's not , can I work on this ?

**Comment by grasyPatel** [comment]
im working on a repository and trying to contribute, but I’m confused by the structure. The project only contains folders like assets/, node_modules/, a screenshot/ folder, and a configure.js file. There’s no src/ or clear folder with the main source code.

I’ve reviewed the configure.js file and other available files but am still unsure where to contribute or what part of the code I should focus on. Could you help me
Understand the structure?
Identify where I can make my contributions?
Thank you in advance for your help!
<img width="378" alt="Screenshot 2024-10-02 at 11 08 28 PM" src="https://github.com/user-attachments/assets/c1ba9a45-c88d-4839-88cc-294ccc7ebce8">

**Comment by sanjay-kv** [comment]
us the branch gh-pages. i forgot to mention

**Comment by grasyPatel** [comment]
Could you please add the following labels to this PR?
Status: Completed or Closes
This will help ensure proper tracking under GSSoC'24-extd

**Comment by sanjay-kv** [comment]
done
