### ISSUE TITLE
Issue: Last merges caused some issue on the profiles display

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#539]
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/143f301e-7550-4033-8670-489697987332">

@dinxsh

**Comment by MrinmayiVerma** [comment]
I would like to work on this issue and give a proper result as soon as possible

**Comment by Jigyasa5** [comment]
i would like to work on this as a beginner pls assign it to me

**Comment by sanjay-kv** [comment]
its first come first serve basis assigned to @MrinmayiVerma
