### ISSUE TITLE
Need a footer similar to this. 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#54]
![image](https://github.com/user-attachments/assets/8e03bbfd-d943-4a17-b9d5-183f529e7813)

#53 code of conduct link
Contact us: link yet to done. 

Change the legal. to Explore 

- How to add your profile
- Be part of the organisation

I will provide the details about the recodehive

**Comment by Asymtode712** [comment]
@sanjay-kv Please assign this to me

**Comment by Asymtode712** [comment]
https://github.com/user-attachments/assets/6b9724f5-960a-424b-bea5-1b17dc889d76

@sanjay-kv Footer built so far, any suggestions??

**Comment by sanjay-kv** [comment]
good to go

**Comment by sanjay-kv** [comment]
Hi @Asymtode712 I was wondering when we do the merge , can we auto close issue respective to it. so we can reduce the clutter.

**Comment by Asymtode712** [comment]
> Hi @Asymtode712 I was wondering when we do the merge , can we auto close issue respective to it. so we can reduce the clutter.

Sure will create the workflow by EOD
