### ISSUE TITLE
Add Profile: Anupam-03

### ISSUE THREAD

**Issue by Anupam-03** [recodehive/awesome-github-profiles#543]
### Please, Add My Profile

![image](https://github.com/user-attachments/assets/5d0ed4ae-3de7-4784-8d11-1f518237ecc9)

**Comment by Anupam-03** [comment]
GitHub profile link: https://github.com/Anupam-03

**Comment by Anupam-03** [comment]
A pull request should be created from this issue if not kindly ping @dinxsh ⚠️

**Comment by sanjay-kv** [comment]
@dinxsh i think there is some issue with json can u look into it.
