### ISSUE TITLE
Improve Nav down bar

### ISSUE THREAD

**Issue by justynigam** [recodehive/awesome-github-profiles#547]
- there is gap better nav down bar and down 
![Screenshot 2024-10-02 154900](https://github.com/user-attachments/assets/4d17bfcd-f8ca-4a2c-8041-1d05595d89f7)
if we fix this then we can add item in main section

**Comment by sanjay-kv** [comment]
assigned you @justynigam make sure work on gh-pages branch

**Comment by justynigam** [comment]
Sure

**Comment by andleeb4898** [comment]
Can I contribute to this

**Comment by justynigam** [comment]
Already merged...

**Comment by andleeb4898** [comment]
oh okay ...
