### ISSUE TITLE
Issue: Social media icons overlapping text content

### ISSUE THREAD

**Issue by ishita-1305** [recodehive/awesome-github-profiles#548]
The social media icons on the right-hand side of the page overlap with the main text content, making it difficult to read the text properly.

![Screenshot 2024-10-02 155618](https://github.com/user-attachments/assets/a577f1f8-ad1f-4399-a380-26a5da7ec86b)
Expected Behavior : The social media icons should not obstruct any of the text on the page. There should be adequate spacing between the icons and the main content, ensuring all text is easily visible and readable.

**Comment by sanjay-kv** [comment]
@ishita-1305 good find assigned you
