### ISSUE TITLE
Feature: Enhancing readme.md by adding dropdowns

### ISSUE THREAD

**Issue by Aditijainnn** [recodehive/awesome-github-profiles#549]
The readme looks fine but its too long to read to so adding dropdown and go to top toggle
please assign me this under gssoc ext

**Comment by alo7lika** [comment]
assign me this work, I would love to contribute. Add labels gssoc and hacktoberfest

**Comment by sanjay-kv** [comment]
there is already simillar issue raised , so if you have specific new idea to implement comment below with sample . we will go with it
