### ISSUE TITLE
Error: node modules have been pushed into the folders, can i fix it?

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [recodehive/awesome-github-profiles#552]
node modules are pushed into the rep can i create a PR to remove it?

Ill add a gitignore files to prevent future errors.

**Comment by sanjay-kv** [comment]
Sure, you should work on gh-pages branch

**Comment by T-Rahul-prabhu-38** [comment]
sure sir , thank you.

**Comment by T-Rahul-prabhu-38** [comment]
i did remove the node modules but someone rejected it.

**Comment by T-Rahul-prabhu-38** [comment]
@sanjay-kv  my PR has been accepted but the level and gssoc tags are not added.
 can u please solve the issue sir.

**Comment by sanjay-kv** [comment]
there were something around 3500 file change. 
so I didn't approve the pr.

**Comment by T-Rahul-prabhu-38** [comment]
oh those were just node modules sir.

**Comment by sanjay-kv** [comment]
@dinxsh @nishant0708 can you help me here to understand this. we have some issue on profile list as well
