### ISSUE TITLE
Error: The font color of the subheading on the GitHub badge page is not suitable for light theme.

### ISSUE THREAD

**Issue by Rahilsamani** [recodehive/awesome-github-profiles#559]
### Describe the Error

The font color of the subheading on the GitHub badge page is difficult to read in the light theme, making it hard for users to distinguish it from the background.

### Expected behavior

The subheading font color should be clearly visible and easily readable in the light theme, providing good contrast against the background.

### Additional context

This issue may affect user experience for those using the light theme. Consider reviewing the color scheme for better accessibility.

<img width="926" alt="image" src="https://github.com/user-attachments/assets/518ba0d7-259f-4aad-9785-f5cbcd353266">

<img width="913" alt="image" src="https://github.com/user-attachments/assets/282f637f-4c0c-4178-8bd3-597913a104a6">

<img width="902" alt="image" src="https://github.com/user-attachments/assets/561ff30f-c258-42dc-85b5-ee27f84fdda8">

<img width="914" alt="image" src="https://github.com/user-attachments/assets/cc46e185-5a27-4944-b522-26baea3af83a">

**Comment by 4F24L** [comment]
Can I work on this issue ? @recodehive

please add gssoc24 and hactoberfest-accepted tag !

**Comment by sanjay-kv** [comment]
@Rahilsamani use the branch gh-pages to make commit

**Comment by Rahilsamani** [comment]
> @Rahilsamani use the branch gh-pages to make commit

Ok sir

**Comment by RanitDERIA** [comment]
I'd love to be assigned to issue #532  as I have the relevant experience in Web Dev and believe I can provide an efficient solution. Looking forward to contributing!

**Comment by Rahilsamani** [comment]
@HimangshuSharma01  Completed
