### ISSUE TITLE
Feature: Theme Mode Should Default to Device Settings if User Preferences Are Unchanged

### ISSUE THREAD

**Issue by mohit-2003** [recodehive/awesome-github-profiles#567]
### Is your feature request related to a problem? Please describe.
Currently, the app doesn't automatically match the device's theme (light or dark) when first opened. This can create a mismatch between the device settings and the app’s appearance, which might confuse users until they manually change the theme.

### Describe the solution you'd like

The app should detect and apply the device's default theme (light/dark) when first launched, as long as the user hasn't already selected a theme in the app. Once the user chooses a theme, their preference should override the system setting and be saved for future use.

**Comment by mohit-2003** [comment]
I would like to contribute by fixing this issue as part of my GSSoC Extd and Hacktoberfest participation. Kindly let me know the process for making this contribution.

**Comment by sanjay-kv** [comment]
@mohit-2003 this is good thought

**Comment by HimangshuSharma01** [comment]
@mohit-2003 any update regarding this issue? it was assigned to you

**Comment by HimangshuSharma01** [comment]
@sanjay-kv  sir can i work in this ?

**Comment by sanjay-kv** [comment]
@HimangshuSharma01 you can work on this

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 you can work on this

sir i did this already
