### ISSUE TITLE
Error: Alignment Issue Of Body And Footer

### ISSUE THREAD

**Issue by Mandy1200** [recodehive/awesome-github-profiles#570]
### Describe the Error

• Their Is A indentation/ Alignmnet error in the body , before the search bar
• The footer is looking unattractive

### Expected behavior

•  The Footer Can Be More Attractive
•  The Aligmnet of elements can be better

### Additional context

• Please can you add this issue to the hackOctober fest and GSSOC-extd 2024

**Comment by re-sha** [comment]
I would love to work on this issue!

**Comment by HimangshuSharma01** [comment]
@Mandy1200 Any update regarding this ? you were assigned to this.

**Comment by Mandy1200** [comment]
sorry bearer , i am unable to configure the yml files

**Comment by Mandy1200** [comment]
Bearer i'am unable to find any file for styles(like css or tailwind css) , it seems like the particular repo is hidden/privatized could you help me to find it and alter the issue i had mentioned in #570

**Comment by HimangshuSharma01** [comment]
> Bearer i'am unable to find any file for styles(like css or tailwind css) , it seems like the particular repo is hidden/privatized could you help me to find it and then i would alter the issue i had mentioned in #570

Check the gh branch you will find all CSS files there @Mandy1200
