### ISSUE TITLE
Add mini chatbot to the website 

### ISSUE THREAD

**Issue by rutikakengal** [recodehive/awesome-github-profiles#571]
add gssoc-ext,hactoberfest-accepted,level labels I like to work on it

**Comment by sanjay-kv** [comment]
follow the same implementation: 
https://machine-learning-repos.vercel.app/

https://github.com/recodehive/machine-learning-repos

**Comment by rutikakengal** [comment]
where is Html and css file is not there @sanjay-kv

**Comment by sanjay-kv** [comment]
@rutikakengal forgot to mention its in the branch gh-pages

**Comment by Peart-Guy** [comment]
I will work on this issue. Please assign this to me

**Comment by HimangshuSharma01** [comment]
@Peart-Guy Please provide samples if possible.

**Comment by Peart-Guy** [comment]
> @Peart-Guy Please provide samples if possible.


This is a basic sample to showcase what I can offer. The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

![image](https://github.com/user-attachments/assets/62ba9c8f-1a23-4191-9de9-d047af353073)

**Comment by sanjay-kv** [comment]
@Peart-Guy there is code base available in the ML repo on this same org. you can refer that,

**Comment by HimangshuSharma01** [comment]
> @Peart-Guy there is code base available in the ML repo on this same org. you can refer that, 

Yes sir I'm helping him with that.

**Comment by Peart-Guy** [comment]
> @Peart-Guy there is code base available in the ML repo on this same org. you can refer that,

Sure.

**Comment by Ankul8471** [comment]
I will work on this issue. Please assign this to me
