### ISSUE TITLE
we can add the search engine to see the github profile using api

### ISSUE THREAD

**Issue by adityalaxkar123** [recodehive/awesome-github-profiles#574]
i think their is another section where people can search the github profiles follower,following and repos

**Comment by adityalaxkar123** [comment]
me a gssoc'24 extended member can you assign it to me

**Comment by sanjay-kv** [comment]
When u raise PR added video recording to better understand. 
I didn't get clear idea where the implementation going to be

**Comment by adityalaxkar123** [comment]
I will give snapshot of this in 30 min

**Comment by adityalaxkar123** [comment]
I add the snapshot of this

**Comment by adityalaxkar123** [comment]
sorry i won't understand the yml code of your repos. i think this project is of html,css , js and node.js because you metioned this tech stack. i have created the code for github-search-engine but i unable to contribute on your project.here is the snapshot of this 
![Screenshot (970)](https://github.com/user-attachments/assets/7e7420c1-c775-44ca-8f4b-69d6ae73f0e8)
