### ISSUE TITLE
Feature: Want to Add View Count in each Profile

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#58]

**Comment by nishant0708** [comment]
hey @sanjay-kv sir can i use Firebase  for this ? because i need some storage to store count .

**Comment by sanjay-kv** [comment]
s3 bucket or firebase which one would be easy. 
I already have the account i will add you into the account.

**Comment by sanjay-kv** [comment]
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/535b374e-4fbd-417e-8682-38a7cb86b07d">

**Comment by nishant0708** [comment]
hey @sanjay-kv sir i guess firebase would be very much easier .For now i will use my credentials only .when done i will replace my credential with yours .

**Comment by sanjay-kv** [comment]
Alright that works can go ahead with fire base
