### ISSUE TITLE
Error: Extra margin at bottom

### ISSUE THREAD

**Issue by vinodM09** [recodehive/awesome-github-profiles#586]
### Describe the Error

The home page have extra margin for which we have to scroll more to get to the bottom/footer of the page.

### Expected behavior

Removing it will make the website less confusing, good looking and easy to navigate.

![Screenshot 2024-10-04 231341](https://github.com/user-attachments/assets/1f368e46-ea00-4a1e-9003-9e39abb8d9e5)

**Comment by coderKrysio** [comment]
hey @sanjay-kv,
if this issue is available, can I work on it

**Comment by HimangshuSharma01** [comment]
@vinodM09 any update regarding the issue it was assigned to you

**Comment by HimangshuSharma01** [comment]
> hey @sanjay-kv, if this issue is available, can I work on it

its solved
