### ISSUE TITLE
Error: Youtube url is incorrect

### ISSUE THREAD

**Issue by re-sha** [recodehive/awesome-github-profiles#588]
### Describe the Error

Youtube icon when clicked, points to youtube.com

### Expected behaviour

When the youtube icon is clicked, it should point to recode hive's youtube channel

**Comment by re-sha** [comment]
Please assign me this issue

**Comment by sanjay-kv** [comment]
can u put link to https://stream.recodehive.com/github

**Comment by re-sha** [comment]
Sure @sanjay-kv, Thank you!
