### ISSUE TITLE
Feature: Implement Advanced Search Features for GitHub Profiles

### ISSUE THREAD

**Issue by vprathap21** [recodehive/awesome-github-profiles#598]
### Is your feature request related to a problem? Please describe.  
The existing search only works based on names, limiting its usefulness for visitors seeking inspiration from GitHub profiles without knowing specific names. Users typically search based on interests or expertise areas, such as “JavaScript developers” or “Data Scientists.”

### Describe the solution you'd like  
Enhance the search to filter profiles by technologies (e.g., Python) or roles (e.g., Software Developer).

### Describe alternatives you've considered  
Currently, the only option is name-based search, which limits discoverability. Alternatives like keyword search or tag filtering could be considered, but they still fall short of allowing specific technology or role searches.

### Additional context  
This improvement will make the repository more user-friendly and accessible.

**Comment by vprathap21** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by vprathap21** [comment]
@sanjay-kv, I was thinking about how to implement this feature. We could collect input from users in the form of tags that represent their roles or tech stacks. Then, we can associate those tags with each user profile, which would let us filter profiles based on the selected tags. What do you think?

**Comment by sanjay-kv** [comment]
We already doing that. 
try to add your profile then you will be able to see this. 

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/5cdff052-bcc9-4f68-9a41-62c5de7cfe9b">

**Comment by HimangshuSharma01** [comment]
@vprathap21 Any update regarding this?
