### ISSUE TITLE
Feature: Want to add custom loader to website

### ISSUE THREAD

**Issue by 17arindam** [recodehive/awesome-github-profiles#600]
### Additional context
![image](https://github.com/user-attachments/assets/fba02357-436e-41fd-afb3-1e788771df68)

![Uploading Screenshot 2024-10-05 153610.png…]()

**Comment by 17arindam** [comment]
i will Add to Every Page

**Comment by sanjay-kv** [comment]
is it like a pre-loader animation?

**Comment by 17arindam** [comment]
Yaa

**Comment by HimangshuSharma01** [comment]
@17arindam any update regarding this ?you were assigned to this.

**Comment by Peart-Guy** [comment]
@sanjay-kv  @HimangshuSharma01 

I would appreciate the opportunity to address this issue and contribute to the project. If possible, could you please assign me to this task? Thank you for considering my request.

Here is a sample of what you can expect to receive from me. I hope it meets your expectations, and I look forward to your feedback! 
The logo text will be replaced by your "Recode Hive logo"


https://github.com/user-attachments/assets/97951129-e820-4cc9-8159-eaaeb4cd4bfe

**Comment by HimangshuSharma01** [comment]
> @sanjay-kv @HimangshuSharma01
> 
> I would appreciate the opportunity to address this issue and contribute to the project. If possible, could you please assign me to this task? Thank you for considering my request.
> 
> Here is a sample of what you can expect to receive from me. I hope it meets your expectations, and I look forward to your feedback! The logo text will be replaced by your "Recode Hive logo"
> 
>  Preloader.mp4

Try to make this as soon as possible @Peart-Guy
