### ISSUE TITLE
Error: Inconsistent Repository Name References

### ISSUE THREAD

**Issue by Sitambhra02** [recodehive/awesome-github-profiles#604]
### Describe the Error

 The repository is referred to as "Awesome GitHub Profiles" in some places and as "Awesome-Github-Profiles" in others (e.g., cloning instructions). This inconsistency might confuse users.
### Expected behavior

 I can fix this, Can you assign me this issue? 
### Additional context

 please add labels gssoc-extd, hacktoberfest-accepted and levels1/2/3

**Comment by Sitambhra02** [comment]
@sanjay-kv I have raised this issue. Then why did you assign this task to nishant0708 ? i deserve this

**Comment by sanjay-kv** [comment]
@Sitambhra02 mate it might have accidently went to Nishant. as I click on the assign, by default all the people with admin access pop up. its my mistake, I will fix it. 
He is one of the mentor for this project. 

 you could have maintained calm and ask about this.

**Comment by Sitambhra02** [comment]
thank you so much
