### ISSUE TITLE
Error: github link not working

### ISSUE THREAD

**Issue by solanki505** [recodehive/awesome-github-profiles#609]
### Describe the Error

![Screenshot 2024-10-05 214317](https://github.com/user-attachments/assets/65271c6b-00f9-43a7-a397-80b93e26a34e)
not redirecting to github page of this website
### Expected behavior
it should direct us to this repo of this project

**Comment by re-sha** [comment]
Can i work on this issue?

**Comment by re-sha** [comment]
Could you please add the following labels: [gssoc-ext](https://github.com/recodehive/awesome-github-profiles/labels/gssoc-ext) , [hacktoberfest-accepted](https://github.com/recodehive/awesome-github-profiles/labels/hacktoberfest-accepted) , [level1](https://github.com/recodehive/awesome-github-profiles/labels/level1) / [level2](https://github.com/recodehive/awesome-github-profiles/labels/level2) / [level3](https://github.com/recodehive/awesome-github-profiles/labels/level3)

**Comment by sanjay-kv** [comment]
dont work on issue before assign. It will create conflict with other developers. 

i hope you added my profile link @re-sha

**Comment by solanki505** [comment]
i wanted to work on this issue
