### ISSUE TITLE
Feature: Adding a up or down navigation option 

### ISSUE THREAD

**Issue by a-kkuuu** [recodehive/awesome-github-profiles#612]
### Is your feature request related to a problem? Please describe.

the website does'nt have up or down navigation option

### Describe the solution you'd like

I want to add  a up and down navigation option so that a user can easily navigate through the website  as it will make our website more user friendly.

**Comment by a-kkuuu** [comment]
please assign me this issue

**Comment by HimangshuSharma01** [comment]
@a-kkuuu This was assigned to you 
kindly update me with the progress.
