### ISSUE TITLE
Feature: Create FAQ Page

### ISSUE THREAD

**Issue by Vishwajeet594** [recodehive/awesome-github-profiles#613]
### Objective:
**Develop and implement a Frequently Asked Questions (FAQ) page on the website to help users quickly find answers to common questions and improve overall user experience.**

### Design:

**1. Create a simple, clean, and easy-to-navigate layout.
2. Ensure that the FAQ page follows the existing website's style and design patterns (fonts, colors, spacing).
3. Include a search bar at the top of the page for users to quickly search for keywords.
4. Consider using an accordion or expandable/collapsible sections for different categories of questions (if the FAQ list is long).**

**Comment by 4F24L** [comment]
Can I work on this ??

**Comment by sanjay-kv** [comment]
Im assigning @4F24L to work along, collaborate with @Vishwajeet594

**Comment by 4F24L** [comment]
Query: Keep FAQs on the landing page, or a new page should be created.

**Comment by sanjay-kv** [comment]
new page

<img width="768" alt="image" src="https://github.com/user-attachments/assets/711ba4e7-4915-4002-a733-bd07e571a61a">

we can put it over here

**Comment by 4F24L** [comment]
Okay !!

**Comment by Vishwajeet594** [comment]
I will submit by tomorrow my exam is going on

**Comment by Subham1** [comment]
pls assign me this task i will work on it

**Comment by HimangshuSharma01** [comment]
@4F24L @Vishwajeet594 Any update regarding this issue?
