### ISSUE TITLE
Error: Popup associated with topmate has got trailing icons below it

### ISSUE THREAD

**Issue by re-sha** [recodehive/awesome-github-profiles#619]
### Describe the Error

On selecting 'Learn' from navbar and scrolling to end, a popup comes up with multiple similar looking logos one below the other

### Expected behavior

Only the popup should be shown to the user, with no trailing large icons

### Additional context

I would greatly appreciate any further information on this and what was trying to be achieved.

Kindly assign this issue to me @sanjay-kv

**Comment by sanjay-kv** [comment]
@re-sha Is the PR done for this.

**Comment by re-sha** [comment]
The issue no longer exists when checking now, I have the current and old screenshots if needed
