### ISSUE TITLE
Feature: Enhancing Blog Interaction with Tag-Based Filtering

### ISSUE THREAD

**Issue by vprathap21** [recodehive/awesome-github-profiles#620]
### Is your feature request related to a problem? Please describe.
The current method of categorizing blogs lacks an interactive element, making it less engaging for users.

### Describe the solution you'd like
I suggest implementing a tag-based filtering system where categories are displayed as clickable tags. This will make it easier and more fun for users to filter blogs based on their interests.

### Describe alternatives you've considered
Alternatives could include using a dropdown menu, but this approach doesn't provide the same level of interactivity and visual appeal.

I’d love to work on this! If you like this idea, please assign the task to me. Thank you for your time and consideration!

**Comment by sanjay-kv** [comment]
Hows this going?

**Comment by vprathap21** [comment]
@sanjay-kv raised PR and it's merged #625
