### ISSUE TITLE
Feature: Sorting on the basis of names (lexicographic order) in compare section.

### ISSUE THREAD

**Issue by DhairyaKaithwar** [recodehive/awesome-github-profiles#623]
## There is a suggestion for a feature about sorting the names on the basis of lexicographic order so that one can find their profile easily if there are too much profiles in the upcoming time.

![Screenshot 2024-10-06 131115](https://github.com/user-attachments/assets/07f7692e-e7fd-4e2c-8aed-e2294d0901eb)

### and please add tag of HACKTOBERFEST on this feature :)

**Comment by sanjay-kv** [comment]
@DhairyaKaithwar how is it going.

**Comment by DhairyaKaithwar** [comment]
@sanjay-kv The work is ongoing, and hope it will be completed by the end of the day.

**Comment by DhairyaKaithwar** [comment]
I have raised PR kindly check...

**Comment by HimangshuSharma01** [comment]
> I have raised PR kindly check...

Please mention the issue no. in corresponding pr.
