### ISSUE TITLE
Error: Dark Mode Not Working on Saved Blogs Page

### ISSUE THREAD

**Issue by vprathap21** [recodehive/awesome-github-profiles#626]
### Describe the Error
The dark mode is not functioning properly on the saved blogs page. When toggling to dark mode, the background and text colors do not change as expected. 

![Screenshot from 2024-10-06 14-01-19](https://github.com/user-attachments/assets/56294a85-335e-497a-a7d6-2e98043362c7)

@sanjay-kv Please assign this issue to me.

**Comment by Akanshaku** [comment]
I would like to work on this issue @sanjay-kv

**Comment by sanjay-kv** [comment]
@vprathap21 could you check again, its working for me.
