### ISSUE TITLE
Feature: Sidebar Navigation Menu

### ISSUE THREAD

**Issue by archanasingh11** [recodehive/awesome-github-profiles#628]
**Description:**

The website would benefit from the addition of a **collapsible sidebar navigation menu** to improve the user experience. A collapsible sidebar provides users with easy access to different sections of the website while keeping the interface clean and uncluttered when not in use.

Suggested features for the collapsible sidebar:
- Expandable categories and subcategories for better content organization.
- A responsive design that adapts to different screen sizes (desktop and mobile).
- Smooth animations for collapsing and expanding the sidebar.
- An intuitive toggle button for users to show or hide the menu as needed.

Implementing this feature will streamline navigation, enhance accessibility, and provide a more modern, user-friendly design.

Please @sanjay-kv assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by sanjay-kv** [comment]
do u have sample image

**Comment by sanjay-kv** [comment]
@archanasingh11 I will update on this tomorrow

**Comment by archanasingh11** [comment]
Okay sure 
If u want i can make this using javascript and react.js and node.js for better adaptibility

**Comment by HimangshuSharma01** [comment]
@archanasingh11 Any update regarding this issue?
