### ISSUE TITLE
Error: Too many invalid hyperlinks posted in the documentation

### ISSUE THREAD

**Issue by yehiarasheed** [recodehive/awesome-github-profiles#635]
### Describe the Error

Upon inspection of the project documentation, I tested its features and literally on the second profile it gave me an invalid hyperlink, on `Mastan Sayyad`'s profile. I've found multiple accounts including `Vansh Chaurasiya`'s profile too and possibly even more profiles that I'd have to test one by one.

### Expected behavior

A working link should be posted linking his profile, if it is deactivated or otherwise it should be removed and added in the same place later on. At least ensuring that the project is working and usable at all times without faults.

### Screenshots
![image](https://github.com/user-attachments/assets/ceb67cf1-d2ae-4e69-950b-3c5dda865b00)
![image](https://github.com/user-attachments/assets/754aee2d-f454-479b-9e6a-e698789ed2d7)
![image](https://github.com/user-attachments/assets/d51dd586-2f79-4488-972d-ce452b673800)

I will follow up on this issue with a PR fixing it.

**Comment by sanjay-kv** [comment]
@yehiarasheed is the issue done

**Comment by yehiarasheed** [comment]
Yes it is.
