### ISSUE TITLE
Error: Youtube icon redirecting to Video playlist

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [recodehive/awesome-github-profiles#636]
### Describe the Error

The Youtube icon on the website redirects the users to the video playlist: Git & GitHub tutorials:
[https://www.youtube.com/watch?v=GrTV59Y84S8&list=PLrLTYhoDFx-kiuFiGQqVpYYZ56pIhUW63]
![image](https://github.com/user-attachments/assets/47b6b383-f615-4fed-bdfe-0190244c5c3c)

### Expected behavior

The Youtube icon should redirect to the Recode Hive youtube channel:
[https://www.youtube.com/@RecodeHive].

### Additional context

I would like to work on this issue to increase the usability of the website further.

**Comment by sanjay-kv** [comment]
no i want to redirect only to the playlist as its github tutorials

**Comment by rajdeepchakraborty-rc** [comment]
Ok sir
