### ISSUE TITLE
Error: social media icon are not updated 

### ISSUE THREAD

**Issue by Antima2004** [recodehive/awesome-github-profiles#645]
###update the social icons 
In the footer section there are social media icon but the twitter logo is not updated 
Here's the image of it:
![Screenshot_2024-10-07-15-46-22-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/12fc4b3b-5513-4227-b708-90daa3166653)
Please assign this to me and also add label

**Comment by rajdeepchakraborty-rc** [comment]
@Antima2004 This issue is already open and assigned to me under Issue #634. Please go through the existing Issues before submitting your issue. You can close this issue and find a new one if you want.

**Comment by Antima2004** [comment]
I have to close this issue or i can do @sanjay-kv

**Comment by sanjay-kv** [comment]
yes you can do

**Comment by Antima2004** [comment]
Ok
Thanks a lots

**Comment by Antima2004** [comment]
Hey 
@sanjay-kv 
Its already updated, twitter logo how can i add??
