### ISSUE TITLE
Improve footer section 

### ISSUE THREAD

**Issue by Pushpa472** [recodehive/awesome-github-profiles#649]
@sanjay-kv footer section can be improve  more for better appearance and footer bottom there are more space we should remove it..
please assign me and add labels
![image](https://github.com/user-attachments/assets/01a68634-7485-418a-8bd8-d7a64784a606)

**Comment by Pushpa472** [comment]
So, I can start the work..

**Comment by sanjay-kv** [comment]
you can work everything is assinged

**Comment by Pushpa472** [comment]
@sanjay-kv I search many time footer codebase but not found, about footer codebase where it's present in the repo.
please tell me..

**Comment by sanjay-kv** [comment]
forgot to mention you this is on `gh-pages` @Pushpa472

**Comment by Pushpa472** [comment]
@sanjay-kv there is no file gh-pages i search it.. where this repo exact

**Comment by sanjay-kv** [comment]
gh-page branch

**Comment by Pushpa472** [comment]
@sanjay-kv  where i make mistake...
![image](https://github.com/user-attachments/assets/b50002a2-2d93-4c51-9052-d0f3de8e7a7f)

**Comment by sanjay-kv** [comment]
@17arindam can you help her.

**Comment by RitikaMaha** [comment]
@sanjay-kv footer section can be improve more for better appearance and footer bottom there are more space we should remove it also the font-size should be increased a little bit to make it look attractive. Please do assign me this task @sanjay-kv. I can help to do necessary changes

**Comment by 17arindam** [comment]
@Pushpa472 fork the whole project instead of just main branch there you will get a gh-pages branch which contain code of the website and then raise pr to gh-pages branch to contribute

**Comment by Pushpa472** [comment]
@17arindam  I fork all repo , i click on gh-pages open in codespaces it not show and also do git checkout gh-pages even in main repo not show and i create my feature branch footer-section.... 
I want to contribute this project....
  ![image](https://github.com/user-attachments/assets/df419cf6-5468-4e5a-b9b9-a7327f979a94)

**Comment by HimangshuSharma01** [comment]
@Pushpa472 Is there any update regarding this Issue ?

**Comment by Pushpa472** [comment]
@HimangshuSharma01 I didn't receive this file.

**Comment by RitikaMaha** [comment]
@sanjay-kv Actually I can't download zip file of code at my end. Can you ol. suggest me an alternative method how to take code at my end

**Comment by sanjay-kv** [comment]
use the command line, we have writtern in the readme file

**Comment by Pushpa472** [comment]
@sanjay-kv @17arindam @HimangshuSharma01 please assign me my work , i want to contribute and I get gh-pages

**Comment by Pushpa472** [comment]
@sanjay-kv @HimangshuSharma01 I complete my work, can I raise pull request

**Comment by RitikaMaha** [comment]
RitikaMaha commented last week
@sanjay-kv footer section can be improve more for better appearance and footer bottom there are more space we should remove it also the font-size should be increased a little bit to make it look attractive. Please do assign me this task @sanjay-kv. I can help to do necessary changes
I will do the necessary changes from Readme file.
@sanjay-kv pl assign me the task

**Comment by sanjay-kv** [comment]
@RitikaMaha can work on it. 

@Pushpa472 you will be getting points for your PR

**Comment by RitikaMaha** [comment]
> @RitikaMaha can work on it.
> 
> @Pushpa472 you will be getting points for your PR

Thanks for assigning me the task
I am able to push changes but some of the files from my desktop are also getting copied on gitrepo
So @sanjay-kv can you pl. Guide me or tell me the command that I can apply to remove unnecessary files from my desktop?
And just copy the changed files pl. @sanjay-kv

**Comment by RitikaMaha** [comment]
@sanjay-kv some files from my desktop are getting copied after pushing it to repo..can you pl. give me command to how delete al those file? and just add only the files from code and then push it
Showing 460 changed files with 22,259 additions and 0 deletions

**Comment by sanjay-kv** [comment]
dont do git add *
