### ISSUE TITLE
Feature:  adding profile photos in the compare section

### ISSUE THREAD

**Issue by jyothimanoj12** [recodehive/awesome-github-profiles#653]
Visual Identity: A profile photo helps identify the individual behind the GitHub account. It personalizes the experience, allowing users to visually connect with the profile, making it more memorable.

User Engagement: Images create a more engaging and interactive experience. Users are more likely to engage with profiles that have photos, as they make the comparison visually appealing and professional.

Recognition: In the tech community, developers often build a reputation through their personal branding. A profile picture is a key part of this, as it helps with recognition at conferences, open-source contributions, or online interactions.

Credibility: A photo adds credibility to a profile. When comparing GitHub profiles, it can help differentiate between active, genuine developers and less active or spam profiles

**Comment by jyothimanoj12** [comment]
plz assign this to me under gsoc-ext level 2 , hacktoberfest-accepted tag

**Comment by HimangshuSharma01** [comment]
@jyothimanoj12 Hey is there any update regarding this issue ?

**Comment by HimangshuSharma01** [comment]
@sanjay-kv i can work in this
