### ISSUE TITLE
Add Profile: 

### ISSUE THREAD

**Issue by Akash-Gupta-git** [recodehive/awesome-github-profiles#656]
## Profile Submission 
![screencapture-github-Akash-Gupta-git-2024-10-08-03_18_47](https://github.com/user-attachments/assets/8358b1fb-10c8-4789-9631-115505469775)

### Profile Category
Please select one or more categories for you profile:

-[ ] <span class="tag">Badge </span>
-[ ] <span class="tag">Minimalistic ✨</span>
-[ ] <span class="tag">Dynamic 🔄</span>
-[ ] <span class="tag">Icons 🎯</span>
-[X] <span class="tag">Background 😎</span>
-[ ] <span class="tag">GIFS 🌆</span>
-[ ] <span class="tag">Game Mode 🚀</span>
-[x] <span class="tag">Code 👨‍💻</span>

### Next Steps

Once you've filled out the information please comment below:

@all-contributors please add @Akash-Gupta-git for review

**Comment by sanjay-kv** [comment]
@all-contributors please add @Akash-Gupta-git for review
