### ISSUE TITLE
Feature:ADD LOGIN SIGN UP OPTIONS 

### ISSUE THREAD

**Issue by HS202022** [recodehive/awesome-github-profiles#658]
### Is your feature request related to a problem? Please describe.

ADD LOGIN SIGN UP OPTIONS 

### Describe the solution you'd like

I CAN CREATE A COOL LOGIN AND SIGNUP PAGE 

### Additional context

SAMPLE
https://github.com/user-attachments/assets/844f3841-3383-4466-87d8-bf748e920ab0

**Comment by sanjay-kv** [comment]
This is cool. 

<img width="683" alt="image" src="https://github.com/user-attachments/assets/071ad9f4-2972-49dd-954f-d342243ae08e">
can u add new tab called login and only add github profile login. because we only focusing on github related thing. once login move the users to a new view called dashboard.

**Comment by sanjay-kv** [comment]
@HS202022 can u raise a new issue to remove this person from the profile 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/ae22d373-f4a7-4c97-bb2b-b041adcae53e">

**Comment by HS202022** [comment]
Sure

**Comment by sanjay-kv** [comment]
I have couple more issue raised, feel free to check on it

**Comment by HS202022** [comment]
hey 
![Screenshot 2024-10-08 104227](https://github.com/user-attachments/assets/78b13f6f-bf15-4205-bc8e-162c2a5f2fd2)
there is no html where can i get it?

**Comment by sanjay-kv** [comment]
@HS202022 check in gh-page branch. 

you can raise new issue to update this part in our readme page. 

to appreciate your effor i can help you getting github galaxy badge, 

https://github.com/recodehive/awesome-github-profiles/discussions/169
https://github.com/recodehive/awesome-github-profiles/discussions/577

just comment something on the above 2 discussions

**Comment by HS202022** [comment]
hey someone with hide password option deleted the login sign up switch
