### ISSUE TITLE
Add 2 more rows on the main page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#659]
<div>
    <a href="Enhancement- add two more rows - 8 October 2024 - Watch Video">
      <p>WindowManager - Gesture Blocking Overlay - 8 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/810a42ad422c4c6f83bc35f6145bae62">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/810a42ad422c4c6f83bc35f6145bae62-63e9a5588d97ae5b-full-play.gif">
    </a>
  </div>

**Comment by YooAshu** [comment]
Please Assign me for this

**Comment by Priyanshu1035** [comment]
Can you assign it to me? I have already done it just getting some permission required error.

**Comment by garimabhayanaa** [comment]
can you assign me this task?

**Comment by sanjay-kv** [comment]
@garimabhayanaa its already completed
