### ISSUE TITLE
Level 3: Bot is not working : help needed

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#660]
Please watch the video for detailed understanding: 

<div>
    <a href="https://www.loom.com/share/e84a08706c284aa190d5a036727e39cd">
      <p>WindowManager - Gesture Blocking Overlay - 8 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/e84a08706c284aa190d5a036727e39cd">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e84a08706c284aa190d5a036727e39cd-c5bfc2109dc215f5-full-play.gif">
    </a>
  </div>

**Comment by pandey-prince20** [comment]
hey i can help you in this.

**Comment by sanjay-kv** [comment]
@dinxsh can you also look into this

**Comment by dinxsh** [comment]
[reference issue](https://github.com/all-contributors/app/issues/315)
- will refactor ``.allcontributorsrc`` to fix this

**Comment by sanjay-kv** [comment]
@dinxsh Awesome, im adding one more maintainer to this project @HS202022

**Comment by dinxsh** [comment]
took bit longer than i expected to but works now @sanjay-kv 
![image](https://github.com/user-attachments/assets/1d5410be-9b11-46a2-9ae4-0bac1a63f5f2)

**Comment by sanjay-kv** [comment]
this is great bro. will sponsor you this week for this change

**Comment by sanjay-kv** [comment]
@dinxsh 
can we redeploy the repo. ? few changes are not reflecting I think its because of the deployment issues I changed the branches.
