### ISSUE TITLE
Footer Section Issue in fonts and space

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#663]
Watch the video:
<div>
    <a href="https://www.loom.com/share/200d666bc2f5495d9c527c2ba96c8987">
      <p>Awesome GitHub Profile READMEs - Google Chrome - 8 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/200d666bc2f5495d9c527c2ba96c8987">
      <img style="max-width:700px;" src="https://cdn.loom.com/sessions/thumbnails/200d666bc2f5495d9c527c2ba96c8987-1b47a875ef67386c-full-play.gif">
    </a>
  </div>

**Comment by MuKulsoop** [comment]
Can I work on this issue?

**Comment by JomanaMahmoud** [comment]
can you assign me this
