### ISSUE TITLE
Create a pop banner: 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#664]
watch this video

<div>
    <a href="https://www.loom.com/share/db2340b17e774425a6b8ed79e0991ede">
      <p>Awesome GitHub Profile READMEs - Google Chrome - 8 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/db2340b17e774425a6b8ed79e0991ede">
      <img style="max-width:900px;" src="https://cdn.loom.com/sessions/thumbnails/db2340b17e774425a6b8ed79e0991ede-26e91cacd6c0c677-full-play.gif">
    </a>
  </div>

**Comment by MuKulsoop** [comment]
Can I work on this issue as I had already done this type of functioning before.
