### ISSUE TITLE
Achievment page update: 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#665]
![image](https://github.com/user-attachments/assets/6c9df987-5950-40b2-9eb4-3238e55e312e)
on this link https://recodehive.github.io/awesome-github-profiles/pages/githubbadge.html
Under How to get: Mention like the below👇🏻

> Create a repository with a lot of stars. Sample repo: (https://github.com/sanjay-kv/Open-source-Practice)
> If you get the first 16 stars you will unlock the badge.
> Watch the Video Tutorial: https://youtu.be/v2Pai1TY_Lg

Note: hyperlink the above link.

**Comment by YooAshu** [comment]
Assign me if this is not done yet

**Comment by YooAshu** [comment]
@sanjay-kv i have made a PR for this issue the other issue #667 #668 #669 #672 are resolved by other contributor i was assigned on it as there is nothing do for the said issues please close them

**Comment by sanjay-kv** [comment]
@YooAshu please let me know. 

that other contributed raised PR for the issue I assigned to you?

it should not work that way, could you highlight the respective issue and PR

**Comment by YooAshu** [comment]
@sanjay-kv  a contributor solved all those issues assigned to me in a single PR, he made only one PR for all those issues

**Comment by sanjay-kv** [comment]
alright then that should be fine, i think it was a mistake from his side.
