### ISSUE TITLE
Error: nav bar problem in mobile view

### ISSUE THREAD

**Issue by YooAshu** [recodehive/awesome-github-profiles#673]
### Describe the Error

The Hamburger icon is not correct in mobile view
The nav menu should be sticky 
Search icon is misplaced in mobile view

![Screenshot_20241008_121512.jpg](https://github.com/user-attachments/assets/556aede5-8a7b-4470-82b3-7f1ae28fa3d5)

### Additional context

Assign me for this

**Comment by sanjay-kv** [comment]
good find, i raised few more issue worth level2. check It out
