### ISSUE TITLE
Feature:  ADD home button in Nav bar.

### ISSUE THREAD

**Issue by 05kaavya** [recodehive/awesome-github-profiles#680]
### Is your feature request related to a problem? Please describe.

 Yes. It might not be a completely new feature, but a necessary add on.

### Describe the solution you'd like

The navbar of the website doesn't contain a home button right now. It would be easier for navigation of main page from other pages using home button. I feel that the home button is a necessary add on.

### Additional context

![Screenshot 2024-10-08 154056](https://github.com/user-attachments/assets/b6ffc027-8c25-4bd7-a3c9-5c1289f6db81)

**Comment by sanjay-kv** [comment]
there is home navigation button available already
