### ISSUE TITLE
Feature: show/hide password 

### ISSUE THREAD

**Issue by 17arindam** [recodehive/awesome-github-profiles#699]
### Is your feature request related to a problem? Please describe.

currently if you enter a password you cant verify whether the password you enter is correct or not

### Describe the solution you'd like

I want to add a toggle to show and hide password by this user can verify that password they enter is not a typo

### Additional context

![image](https://github.com/user-attachments/assets/4783b6a0-fd02-4557-afbc-bc18beac4e41)

**Comment by 17arindam** [comment]
@sanjay-kv please assign me this issue

**Comment by sanjay-kv** [comment]
@17arindam I was planning to remove manual sign-on and keep only github. /
whats your thought on this. i mean these days even if someone create a login they dont come here often,

**Comment by 17arindam** [comment]
@sanjay-kv yeah i think only github would be better choice
