### ISSUE TITLE
Bug: Text repeating on badge page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#701]
![image](https://github.com/user-attachments/assets/b7a7f964-92ff-4ca2-adf9-5aa8837c8e39)

There is repetition , could you remove the extra information in red red-marked box

Link: https://recodehive.github.io/awesome-github-profiles/pages/githubbadge.html

**Comment by YooAshu** [comment]
Please assign me

**Comment by anchalchaturvedi08** [comment]
@sanjay-kv Can you assign this issue to me, Sir?

**Comment by Sahirrao8** [comment]
I want to solve this issue please assign it to me.

**Comment by Dishi-Gautam** [comment]
please assign me this issue if it is  not resolved yet @sanjay-kv
