### ISSUE TITLE
Feature: Want to change the effect and colour of the website

### ISSUE THREAD

**Issue by Dipanita45** [recodehive/awesome-github-profiles#703]
### Change the transition effect , font size, and colour

Thank you for viewing my issue

![Screenshot 2024-10-09 063454](https://github.com/user-attachments/assets/2348dfd8-429d-448f-9dde-bc53afdc18f5)

**Comment by sanjay-kv** [comment]
could you give me some sample or what effect and styling you plan to implement.

**Comment by Dipanita45** [comment]
I have no sample

**Comment by Dipanita45** [comment]
Please assign me
