### ISSUE TITLE
Still in discussion : add your idea Brainstrom on compare features

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#704]
### Discussed in https://github.com/recodehive/awesome-github-profiles/discussions/702

<div type='discussions-op-text'>

<sup>Originally posted by **sanjay-kv** October  9, 2024</sup>
here is the link: https://recodehive.github.io/awesome-github-profiles/pages/compare.html</div>

**Comment by AdibaNaushad** [comment]
assign me this i can do documentation

**Comment by sanjay-kv** [comment]
its not documentation, its a place to discuss if you have any idea can discuss there, and assign issue if its good
