### ISSUE TITLE
Error: insertion of hide password option deleted the login sign up switch 


### ISSUE THREAD

**Issue by HS202022** [recodehive/awesome-github-profiles#708]
![Screenshot 2024-10-09 093941](https://github.com/user-attachments/assets/11db8e85-e75a-4138-89a5-2d3c35c9ca9d)
u can assign me for this i will fix this as well as add the hide option
There is no option for going back to the home page and switching between login and sign up.

**Comment by HS202022** [comment]
It would be helpful if u can unmerge that pr for hide options of password

**Comment by sanjay-kv** [comment]
there is similar issue raised which is already assigned as well

**Comment by HS202022** [comment]
> there is similar issue raised which is already assigned as well
okay

**Comment by HS202022** [comment]
is it not done?
can i work on this?

**Comment by HS202022** [comment]
@sanjay-kv Sir please merge PR #727 in order to pull another request
