### ISSUE TITLE
Error:  Dark Mode toggle button is not working 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#71]
### Describe the Error

The dark mode toggling button is not working 
When i am clicking on it the the mode is not toggling 

### Expected behavior

The dark mode must change to light mode 

https://github.com/user-attachments/assets/ed762526-7733-43f9-9440-ca49fa8bf532

**Comment by sanjay-kv** [comment]
Its working for me.
