### ISSUE TITLE
Error: Social Media Icons Overlapping and Hidden Behind Profile Card in Mobile View

### ISSUE THREAD

**Issue by MohammedMusharraf11** [recodehive/awesome-github-profiles#714]
### Describe the Error

The social media icons are getting hidden behind the readmes and other UI elements when viewed on smaller screens or in mobile view.

### Expected behavior

The social media icons should be fully visible and positioned correctly to the right of the profile card without overlapping or getting obscured by other elements

### Additional context
The issue might be related to improper z-index stacking or the use of a flex/grid container that causes the icons to overlap.
Screenshot attached to illustrate the problem (see attached image for reference).

![image](https://github.com/user-attachments/assets/34a4e05a-682c-43de-b350-a7e9cccc695a)

Please Assign it to me 
I will fix this

**Comment by MohammedMusharraf11** [comment]
Please Assign it to me

**Comment by HS202022** [comment]
you can assign this to me

https://github.com/user-attachments/assets/0dfb287d-91a4-4b8f-827d-6fb6365289df
