### ISSUE TITLE
Event page is not working in small screens

### ISSUE THREAD

**Issue by Raj-Aditya-27** [recodehive/awesome-github-profiles#718]
Hi @sanjay-kv 

### Describe the Error

Event Page is properly working in desktop but not in small devices like mobile

### Expected behavior

It should be visible in small devices also

### Additional context

Video of bug:
[recording.webm](https://github.com/user-attachments/assets/24d004df-bb4b-41c3-b6e6-8b3433718688)

**Comment by HS202022** [comment]
assign this to  me

**Comment by Raj-Aditya-27** [comment]
Thanks for assigning this issue to me.
I will do it as soon as possible.

**Comment by sanjay-kv** [comment]
take your time.
