### ISSUE TITLE
Feature: ContactUs Form

### ISSUE THREAD

**Issue by Bhum-ika** [recodehive/awesome-github-profiles#722]
### Is your feature request related to a problem? Please describe.

When clicked on contactUs, it takes us to a page to "Scroll into see how to get most out of this website"

### Describe the solution you'd like
A contact form should be provided on the website for visitors to easily send messages in case of any issues. Additional information, such as your email address, can also be included.

### Additional context
I will create it
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by sanjay-kv** [comment]
its already there isnt it. at footer?

**Comment by Bhum-ika** [comment]
No, there is no contactUs form, although the link is there in the footer

Uploading Awesome GitHub Profile READMEs - Google Chrome 2024-10-10 16-32-51.mp4…

**Comment by RanjanaChirania** [comment]
I will be happy to help out in this issue

**Comment by sunidhi3** [comment]
I'm gssoc contributor so please assign me this issue.

**Comment by Bhum-ika** [comment]
Hi @sanjay-kv 
I am following all the steps that you have mentioned but after running command to navigate to 'gh-pages' branch , it is stating error that this doesn't exist.

Could you please suggest something?
Thank you
