### ISSUE TITLE
Enhance Login Page UI/UX and Add Sign-Up with Home Navigation Icon

### ISSUE THREAD

**Issue by ritiksingh-01** [recodehive/awesome-github-profiles#728]
### Is your feature request related to a problem? Please describe.

I will improve the design of the login page, making it more visually appealing and user-friendly. Additionally, I will create a new sign-up section and add an icon to both the login and sign-up pages that will allow users to navigate directly back to the home page. These enhancements will streamline the user flow and make the interface more intuitive.

### Describe the solution you'd like

I would like to enhance the user interface and experience of the login page by making the following improvements:

1. UI/UX Enhancement for Login Page:
Redesign the login page to make it more visually appealing and user-friendly. This will include improving layout, button styles, and overall aesthetics to ensure a modern and smooth experience.

2. Sign-Up Option on Login Page:
Add a sign-up option directly to the login page, allowing users to register without navigating to a separate page. This will streamline the user flow and make access easier.

3. Home Navigation Icon:
Introduce an icon on both the login and sign-up pages that will take users directly to the home page. This will provide easy navigation and enhance usability by giving users quick access to the main page.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

![Sign in](https://github.com/user-attachments/assets/fb3ee161-99eb-4d51-a0cd-71e9ebc663d6)

**Comment by sanjay-kv** [comment]
I need to do further discussion

**Comment by ritiksingh-01** [comment]
> I need to do further discussion

Yes sir ??

**Comment by RanjanaChirania** [comment]
Hey I can help you in this!

**Comment by ritiksingh-01** [comment]
I can design your login page like this, if you prefer.

![login](https://github.com/user-attachments/assets/fb289d15-fb07-42dd-8d04-58e9527de8b5)
