### ISSUE TITLE
Add Profile: Suvadip-sana

### ISSUE THREAD

**Issue by Suvadip-sana** [recodehive/awesome-github-profiles#733]
### A pull request should be created from this issue if not kindly ping @dinxsh ⚠️
I want to add my profile in this awesome platform.

**Comment by dinxsh** [comment]
@Suvadip-sana we're working on fixing the bot and will add your profile once it's done, until then please wait, thanks!

**Comment by Suvadip-sana** [comment]
@dinxsh 

Yes please do that.
I want to list my profile in recodhive

**Comment by Suvadip-sana** [comment]
@HimangshuSharma01  @sanjay-kv  @dinxsh 
Is the bot fixed? Am I able to add my profile?  Please let me know sir.

**Comment by sanjay-kv** [comment]
bot is not fixed. 

if you want to see https://github.com/recodehive/awesome-github-profiles/issues/660
