### ISSUE TITLE
Error: Search Icon over lapping on placeholder in small screen

### ISSUE THREAD

**Issue by Suvadip-sana** [recodehive/awesome-github-profiles#734]
### Describe the Error

In small screen like mobile the search bar the magnifying search icon overlapping the placeholder text, that's why it's hard to understand what this placeholder try to say to the user .
### Expected behavior

It supposed to be in big length for mobile screen, that's how the place holder view clearly for better understanding, also need some work with font size & padding like stuff.
### Additional context

https://github.com/user-attachments/assets/abf66456-5928-420a-bb17-dfb5ac6d6c24

![image](https://github.com/user-attachments/assets/aee42530-c21e-4bd9-b3e1-2e465ae26757)

@sanjay-kv  Please assign me this issue. i want to fix his prestigious open source project.

### Note 
 Please add necessary tags along with hacktoberfest, if you assign me this task.

**Comment by andleeb4898** [comment]
can i contribute to this issue
