### ISSUE TITLE
Error:  Locker Icon Misalignment and Enhancement for Password Visibility

### ISSUE THREAD

**Issue by ritiksingh-01** [recodehive/awesome-github-profiles#738]
### Describe the Error

The locker icon in the password field is not properly aligned, affecting the overall UI/UX consistency. I will realign the locker icon to ensure it appears correctly within the password field. Additionally, I will enhance the functionality by making the locker icon work similarly to the eye button, allowing users to toggle password visibility easily. This update will improve both the visual design and usability of the login and sign-up forms.

### Expected behavior

1. The locker icon should be properly aligned within the password field, ensuring a clean and professional appearance.
2. The locker icon should function as a toggle button, similar to the eye icon, allowing users to click it to show or hide the password.
3. Both the design and functionality should enhance the user experience, providing a visually appealing and easy-to-use feature for password input.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

![locker icon](https://github.com/user-attachments/assets/c50487a4-6d27-45f9-b751-44ec2e599e9d)

**Comment by ritiksingh-01** [comment]
Hi, @sanjay-kv 

Sorry to bother you, sir, but I need some help. I'm having trouble accessing the login.html file. Could you please help me figure out how to access it?

**Comment by sanjay-kv** [comment]
gh-page branch
