### ISSUE TITLE
Increase the size of logo

### ISSUE THREAD

**Issue by RitikaMaha** [recodehive/awesome-github-profiles#739]
@sanjay-kv The size of Recode Hive should be increased and also make it a bit of bold sized as the background color is dark the logo isn't clearly visible. So please @sanjay-kv Do assign me this task, I can do it from my side
![image](https://github.com/user-attachments/assets/c75bc8b9-0621-4901-aed7-7d7791efde10)

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.

**Comment by sanjay-kv** [comment]
this webstie you refer is not related to this repo
