### ISSUE TITLE
Error: GitHub Profiles Overlapping/Overriding Social Icons

### ISSUE THREAD

**Issue by priyachau12** [recodehive/awesome-github-profiles#743]
Describe the Error:
 In the current implementation, GitHub profile cards are suppressing the social icons on the main page. As a result, the profile cards cover the social icons, making them inaccessible and disrupting the intended layout.

Expected Behavior:
 The social icons should always appear on top of the GitHub profile cards, ensuring they remain visible and accessible regardless of the position of the profile cards.

Steps to Reproduce:
Navigate to the page where GitHub profiles and social icons are displayed together.
Scroll through the profiles and observe how the social icons are overlapped by the profile cards.

Proposed Solution:
Adjust the CSS z-index values to give the social icons a higher z-index compared to the profile cards.
Ensure both elements are positioned correctly (e.g., relative or absolute) to respect the stacking order.
Additional Context This issue affects the user experience, as social icons are meant to be always accessible. Resolving this would improve the usability and visual appeal of the interface.

![image](https://github.com/user-attachments/assets/1a041cca-049d-4026-83c0-704e766ff80d)
![image](https://github.com/user-attachments/assets/86b30b7d-3189-47e1-81df-3d04ab94bdb8)

**Comment by sanjay-kv** [comment]
I think someone raised issue on this.
