### ISSUE TITLE
Feature: Dedicated Contributions Page

### ISSUE THREAD

**Issue by priyachau12** [recodehive/awesome-github-profiles#744]
Is your feature request related to a problem? Please describe:
Currently, users lack a centralized page to view contributions, which makes it challenging to access all contributions in one place. This limits visibility for users who want to see the scope and details of contributions from various community members.

Describe the Solution You'd Like:
A dedicated "Contributions" page should be added, accessible from the main navigation, which displays:

->A list of recent contributions by all contributors.
->Sorting and filtering options (e.g., by contributor, date, or type of contribution).
->Details for each contribution, including timestamps, descriptions, and related comments.

### Additional context

![image](https://github.com/user-attachments/assets/f29ca734-ad15-4423-80bc-a8282e19649e)

**Comment by sanjay-kv** [comment]
no this is not required, we are highlighting them on the repo main page
