### ISSUE TITLE
Error: dark mode button animation does not work

### ISSUE THREAD

**Issue by yehiarasheed** [recodehive/awesome-github-profiles#756]
### Describe the Error

The dark mode button in the Navigation Menu does not toggle or change color and logo as it turns on and off.

### Expected behavior

The button should toggle back and forth, change color and logo according to whether it is now in light mode or dark mode.

### Screenshots
![image](https://github.com/user-attachments/assets/c75b91fc-0157-4221-9fc3-766edd41dba4)

**Comment by yehiarasheed** [comment]
I will also change the text `UnLiked` to `Unliked` as it should be written in **proper english**.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
