### ISSUE TITLE
Error: incorrect section linking in Nav Menu

### ISSUE THREAD

**Issue by yehiarasheed** [recodehive/awesome-github-profiles#757]
### Describe the Error

The hyperlinks in the Navigation Menu do not work as they should, there are two sections in the Menu `Blog` and `Learn` that point to the same blog page.

### Expected behavior

The presence of multiple sections in the Navigation Menu means that each section should point to a different page, there is no point in having redundant sections that confuse the users.

### Screenshots

![image](https://github.com/user-attachments/assets/017f1893-cd11-498c-8cbf-51b6cbbf340f)

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by HimangshuSharma01** [comment]
@yehiarasheed any update regarding this?

**Comment by yehiarasheed** [comment]
Yes, working on it. I'm thinking to implement this on a bigger scale, across all webpages.
