### ISSUE TITLE
Error: Bugs on Saved Blogs Page

### ISSUE THREAD

**Issue by Akshithsaai** [recodehive/awesome-github-profiles#763]
### Describe the Error

1. The Logo is not properly Routed to main page.
2. There is no Back to Blogs button .

### Expected behavior

1. Nav Bar should be correctly routed.
2. A Back to Blogs Button should be added and routed properly so that User can direct back easily.

### Additional context
I Would Like to work on this @sanjay-kv .

### Video Recording

https://github.com/user-attachments/assets/066b1259-033b-4451-aae7-c9027c8604f0

**Comment by Shariq2003** [comment]
@sanjay-kv sir, please look into discussion section, many of us have queries, please help us to resolve
