### ISSUE TITLE
Feature: Add Overlay behind Pop Up 

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#778]
![image](https://github.com/user-attachments/assets/ba90fa0f-5dd8-491f-813e-5e2f20022aa1)

Currently, when a pop-up appears on the screen, the elements behind it remain clickable, which can lead to unintended interactions. We need to add an overlay behind the pop-up to prevent users from clicking or interacting with any elements outside the pop-up.

**Comment by samar12-rad** [comment]
Can you assign me this issue @nishant0708 ?

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by samar12-rad** [comment]
I am working on it @sanjay-kv

**Comment by HimangshuSharma01** [comment]
@samar12-rad Any update regarding this issue ?

**Comment by samar12-rad** [comment]
@HimangshuSharma01 , I will push it today!
