### ISSUE TITLE
Feature: Theme Getting Change when we click on Saved blogs

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#779]
https://github.com/user-attachments/assets/c8f3e34d-c115-4bfc-9683-918fa1920919

See this Theme Change this should not happen

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/awesome-github-profiles/issues/660

I need help in look into this issue as well

**Comment by nishant0708** [comment]
hey @sanjay-kv sir i am just raising issues i dont want to work on it  .

**Comment by nishant0708** [comment]
I will look into all-contributors issue

**Comment by 17arindam** [comment]
@sanjay-kv please assign me this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
