### ISSUE TITLE
Feature: PopUp Overflow Issue

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#780]
![image](https://github.com/user-attachments/assets/e2780ac5-75f2-46c9-96a7-da320216799f)

See this popup in Blogs Page It is getting Overflowed  we Need to fix it

**Comment by 17arindam** [comment]
@sanjay-kv please assign me this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
