### ISSUE TITLE
Feature: Consistency in Navbar Click Events

### ISSUE THREAD

**Issue by nishant0708** [recodehive/awesome-github-profiles#782]
https://github.com/user-attachments/assets/d77cd7db-90ca-4cda-bb4e-5b8ac5bcf6bb

See When We are on Tools page and we click on tools page again it navigate us to top of the page smoothly. This Same Feature We Want in Events and Learn Page . Currently Events and learn pages are getting reloaded

**Comment by 17arindam** [comment]
@sanjay-kv please assign me this issue

**Comment by Arkyapatwa** [comment]
Hey @sanjay-kv i would like to work on this feature. You can assign it to me.
