### ISSUE TITLE
Error: overlapping icons in mobile or small screens

### ISSUE THREAD

**Issue by HS202022** [recodehive/awesome-github-profiles#787]
### Describe the Error

Overlapped icons
![Screenshot 2024-10-12 204824](https://github.com/user-attachments/assets/3cfda821-30bc-4e42-8ad5-6ba51b69ce87)

assign me this the previous issue in which i comment and  asked to assign me has been deleted

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by HS202022** [comment]
> you can assign this task to me... 

It's already done
