### ISSUE TITLE
Add the blog page details 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#79]
There is a blog page over the nav bar, now the idea is people already added the profile. so whats next for them, 
<img width="239" alt="image" src="https://github.com/user-attachments/assets/a0400706-934a-4dc2-ad12-40ab83a15c8c">

It shouldnt be something like add the profile and abadnded the site. its should be a learning source. 

So i already have a website which teach github from scrarch,  link given below, 

https://recodehive.com/github-tutorials/

Now in the new page i need to have a similar box designs , but when user click it will redirect to main page particular post. 

-----------

Maybe in future if i add a new post realted to github, if we can add a functionality to fetch automatically and display it over here . that would be great. we can ignore if its too difficult to implement.

**Comment by nishant0708** [comment]
hey @sanjay-kv sir i want to work on it

**Comment by nishant0708** [comment]
![image](https://github.com/user-attachments/assets/a7e3b843-9602-480e-b369-9ef65d3eac3a)
hey @sanjay-kv sir like You want this blog design and when someone click on it. lets say what is Github? then it should redirect him to https://recodehive.com/what-is-github-guide-to-beginner/ this page ?

**Comment by sanjay-kv** [comment]
Exactly , we do redirect,

**Comment by nishant0708** [comment]
so when You made RecordHive (tutorial) website there must be one Get Api right .can i get that or its github repo will be fine too

**Comment by sanjay-kv** [comment]
otherwise we ignore this api thing. 

lets the traditional approach , as of now i think those blogs will do for beginner. we can add it manually.

**Comment by nishant0708** [comment]
> otherwise we ignore this api thing.
> 
> lets the traditional approach , as of now i think those blogs will do for beginner. we can add it manually.

okay i will make them manually

**Comment by sanjay-kv** [comment]
awesome
