### ISSUE TITLE
Enhancing the font and size the heading and menu bar

### ISSUE THREAD

**Issue by Janmejai24** [recodehive/awesome-github-profiles#794]
The heading text and menu bar text on the website could be improved by changing it's font it is very basic , increasing its font size, weight, and contrast to enhance readability and visual hierarchy. Modernizing the font style and adjusting spacing will create a cleaner, more organized look, improving overall user experience and accessibility.
Please assign this issue to me under gssoc-extd and hacktoberfest
![image](https://github.com/user-attachments/assets/5196cf4c-48c9-43fe-97cc-fd83e159f650)

**Comment by sanjay-kv** [comment]
i think you should work on footer. heading looks fine

**Comment by Janmejai24** [comment]
okay I will work on footer.Please assign this issue to me under gssoc-extd and hacktoberfest

**Comment by sanjay-kv** [comment]
@Janmejai24 make sure only footer change

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...  i can do this tonight..

**Comment by Janmejai24** [comment]
after cloning how to start the project like what to do npm run start or any other command

**Comment by HimangshuSharma01** [comment]
@Janmejai24 You can find the html css part in the gh branch
