### ISSUE TITLE
Odd profiles

### ISSUE THREAD

**Issue by aasritha-24** [recodehive/awesome-github-profiles#796]
Some profiles are odd and different from others

![image](https://github.com/user-attachments/assets/6e39fee8-1fd0-46aa-a342-6f6c55e6c8bd)

Assign me this issue under gssoc-extd label

**Comment by sanjay-kv** [comment]
you can remove this.

**Comment by HimangshuSharma01** [comment]
@aasritha-24 Are you working in this?
