### ISSUE TITLE
Issue: Microphone not visible in dark mode

### ISSUE THREAD

**Issue by ishita-1305** [recodehive/awesome-github-profiles#804]
Description:
The microphone icon is not visible when using the application in dark mode. Due to the dark background, the icon blends in and becomes hard to distinguish, which affects the user experience.

https://github.com/user-attachments/assets/36ca6524-abe2-49e2-bd03-0a565199e806

**Comment by this-is-pooja** [comment]
can you please assign it to me under gssoc-ext ,hacktoberfest-accepted and level label
