### ISSUE TITLE
Error: Not responsive in Mobile Screen

### ISSUE THREAD

**Issue by Jainpaswan** [recodehive/awesome-github-profiles#808]
Navbar do not scale up to cover the full width while in mobile screen mode ...
same goes for  Footer too

their width should be full for better User interface
![Screenshot 2024-10-14 000420](https://github.com/user-attachments/assets/4446c96a-68d2-41d1-ad63-5c5f2ba0cfa1)

**Comment by Jainpaswan** [comment]
Thank you for assigning me ...

**Comment by HimangshuSharma01** [comment]
@Jainpaswan any update regarding this issue?

**Comment by Jainpaswan** [comment]
Apology for the late reply...
But currently I'm dealing with health issues...
Not able to continue to gssoc...
Therefore I am requesting to unassigned this task from me...
About the updates I already made 2 pull request but they were declined due
to "merge and too much changes"...
Again sorry for informing this late to you....
