### ISSUE TITLE
Feature:  Want to create a seperate 404 not found page when link now found 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [recodehive/awesome-github-profiles#81]
### Is your feature request related to a problem? Please describe.

I want to make a seperate 404 error page and add an option to go back so that user can visit the home page from their 

![image](https://github.com/user-attachments/assets/efe28ca4-a55c-4a62-8f09-8cd812c40155)

**Comment by sanjay-kv** [comment]
I think we are fixing it on another issue,
