### ISSUE TITLE
Error: x logo is not visible

### ISSUE THREAD

**Issue by Adinath-j** [recodehive/awesome-github-profiles#819]
![x logo](https://github.com/user-attachments/assets/e0866fbd-5161-4147-b0e3-798ab7fe367a)

the x logo or icon is not displayed in the website

**Comment by Adinath-j** [comment]
I can solve this issue. Please assign me.

**Comment by RishabxBhardwaj** [comment]
\assign

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue; please assign this issue to me.

**Comment by sanjay-kv** [comment]
@AsmitaMishra24 sorry its already assigned to @Adinath-j
