### ISSUE TITLE
Need to change the text on footer

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#82]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/48741c75-de98-4e64-b9e2-af20e878b450">

We focus on quality content for the right people at the right time⏱️. What we are trying to do is help you to brand personal skills through GitHub readme.md, So we listing the best profiles & opportunity to list your profile to the world.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir i want to work on it

**Comment by sanjay-kv** [comment]
put the world emoji at the end

**Comment by nishant0708** [comment]
can i work on this ?
