### ISSUE TITLE
Unlinked "Tools" Item in Navbar – Suggest Removal for Better User Experience

### ISSUE THREAD

**Issue by anshxika** [recodehive/awesome-github-profiles#822]
### Describe the Error
tools heading is not properly attached to any page, on clicking it doesn't do anything

### Expected behavior
it should redirect me to the tools page on clicking it if there is any.

### Additional context
I noticed that the "Tools" section in the navbar isn't linked to any page or content on the site. If there's no file or content planned for this section, it might be beneficial to remove it to avoid confusion for users. This would help clean up the interface and improve the overall user experience.
@sanjay-kv Please let me know if you'd like me to help with this and assign this issue to me under gssoc-ext'24 and hacktoberfest and a level if you may. thanks

**Comment by sanjay-kv** [comment]
instead add tool to other pages

**Comment by anshxika** [comment]
@sanjay-kv sorry didn't get you here, what do you mean by adding tools to other pages ?
