### ISSUE TITLE
Feature: Want to add twitter icon

### ISSUE THREAD

**Issue by Mansi07sharma** [recodehive/awesome-github-profiles#823]
### Is your feature request related to a problem? Please describe.

Twitter icon is not there I want to add it.

Kindly assign it to me @sanjay-kv 

![image](https://github.com/user-attachments/assets/aaabfdda-157d-4f37-a315-a4d24b12bd06)
 
After hovering

![image](https://github.com/user-attachments/assets/145e6231-1ee4-4521-a855-c016b44a0933)

**Comment by nishant0708** [comment]
This issue already exist
