### ISSUE TITLE
'X' profile icon missing 

### ISSUE THREAD

**Issue by anshxika** [recodehive/awesome-github-profiles#824]
### Describe the Error
there's no icon for your X profile.
![Screenshot 2024-10-14 203440](https://github.com/user-attachments/assets/d2ee7c05-22a7-4588-b848-419b2db86b15)

### Expected behavior
a profile icon like for the rest of the socials.

### Additional context
@sanjay-kv please assign me this issue under gssoc and hacktoberfest. thankyou

**Comment by nishant0708** [comment]
This issue already exist.
