### ISSUE TITLE
Suggestion: Change YouTube Link to Direct Users to Channel

### ISSUE THREAD

**Issue by anshxika** [recodehive/awesome-github-profiles#825]
I would like to suggest that the YouTube link associated with each profile should redirect users to the respective channel rather than a specific video on how to use GitHub. This change would provide users with more options to explore other content from the channel, enhancing their experience and potentially increasing engagement with the creators.

https://github.com/user-attachments/assets/cbccac45-084e-425c-8620-f76cd4bfa71d

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by anshxika** [comment]
@biswa2005 i am assigned to it and have already resolved this issue and pulled request as well.

**Comment by biswa2005** [comment]
ok
