### ISSUE TITLE
Feature: Firebase backend for github authentication 

### ISSUE THREAD

**Issue by 17arindam** [recodehive/awesome-github-profiles#831]
### Is your feature request related to a problem? Please describe.

Currently there is no backend for github authentication 
### Describe the solution you'd like
i want to use firebase to enable github authentication in the website

### Additional context
![image](https://github.com/user-attachments/assets/07ecf112-ee4e-4c4c-a6ba-5bae14ece18a)

**Comment by HimangshuSharma01** [comment]
@17arindam Any update regarding this?

**Comment by HimangshuSharma01** [comment]
@sanjay-kv can i Work in this?
