### ISSUE TITLE
Error: Twitter Logo not Visible

### ISSUE THREAD

**Issue by inkerton** [recodehive/awesome-github-profiles#835]
### Describe the Error
![image](https://github.com/user-attachments/assets/dd55a591-14b0-4b75-9db1-87d436261031)

### Expected behavior
It Should be visible like other Logos

**Comment by nagajaideep** [comment]
i would like to work on this issue can you please assign me this @inkerton

**Comment by sanjay-kv** [comment]
already assigned this issue before
