### ISSUE TITLE
Feature: Add no of pr and no of issue in compare page 

### ISSUE THREAD

**Issue by 17arindam** [recodehive/awesome-github-profiles#836]
### Is your feature request related to a problem? Please describe.

currently the compare page dont have no of pr and no of issue 

### Describe the solution you'd like

i want to add them in compare section 

### Additional context
![image](https://github.com/user-attachments/assets/790bdc24-082b-431d-8542-e900c4db0b34)

**Comment by HimangshuSharma01** [comment]
@17arindam any update regarding this?

**Comment by HimangshuSharma01** [comment]
@sanjay-kv Can i work in this?

**Comment by HimangshuSharma01** [comment]
@sanjay-kv  i can work in this
