### ISSUE TITLE
Need a Social badge on the side. 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#84]
<img width="138" alt="image" src="https://github.com/user-attachments/assets/aff81356-d68f-4049-bdb8-fc2a5fa6c0e7">

This i took it from the gssoc website, may be we ca integrate this .

I will be providiing the link on new issue

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work on it

**Comment by Asymtode712** [comment]
@sanjay-kv Can I work on this

**Comment by Asymtode712** [comment]
@sanjay-kv Do we have to keep this social icon container on every page??

**Comment by sanjay-kv** [comment]
Just home page will do

**Comment by Asymtode712** [comment]
@sanjay-kv Sure, raising a PR for fixing the spacing in mobile view

**Comment by sanjay-kv** [comment]
![WhatsApp Image 2024-08-06 at 00 11 52_ec8330b3](https://github.com/user-attachments/assets/e86c99da-9ca8-43b6-85f3-2a1fa207d614)


In the mobile view is bad , so we can reduce the width a bit and match the color of the background. so it will blend to the page.

**Comment by Asymtode712** [comment]
@sanjay-kv Ok, I have already fixed the width, will fix the bg now
