### ISSUE TITLE
Can we add this simillar scroll to bottom

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#85]
<img width="176" alt="image" src="https://github.com/user-attachments/assets/46466863-02b5-4e83-816d-2ba1080fbcf0">

adapted idea from the gssoc website.

**Comment by nishant0708** [comment]
hey @sanjay-kv sir i can work on this

**Comment by MastanSayyad** [comment]
Hi @sanjay-kv, I would like to work on this issue. Hey Would it be alright if I take it on this issue, @nishant0708? as you already have some other assigned issues.

**Comment by sanjay-kv** [comment]
@MastanSayyad you can work on, i need to finish this asap. so can make perfect before launching wed for contributor.

**Comment by MastanSayyad** [comment]
@thevijayshankersharma Already made it brother
