### ISSUE TITLE
Missing contact page

### ISSUE THREAD

**Issue by Subham1** [recodehive/awesome-github-profiles#853]
### Missing "Contact Us" Page on Website

A "Contact Us" link has been added to the website's navigation, but clicking the link does not lead to a functional contact page. The page is either missing or not populated with any content, leaving users unable to reach out.

### Expected behavior

The "Contact Us" page should include:

1.A contact form for users to submit their messages
2.Email or phone contact details
3.Links to social media or other communication channels

### Additional context

As this issue is being raised as could you please assign the gssoc extnd label to this issue

**Comment by sanjay-kv** [comment]
its already there isnt it, new issue?

**Comment by HimangshuSharma01** [comment]
> ### Missing "Contact Us" Page on Website
> A "Contact Us" link has been added to the website's navigation, but clicking the link does not lead to a functional contact page. The page is either missing or not populated with any content, leaving users unable to reach out.
> 
> ### Expected behavior
> The "Contact Us" page should include:
> 
> 1.A contact form for users to submit their messages 2.Email or phone contact details 3.Links to social media or other communication channels
> 
> ### Additional context
> As this issue is being raised as could you please assign the gssoc extnd label to this issue

![image](https://github.com/user-attachments/assets/6cacaf8a-50c3-4255-a725-c309077fb998)
Please check the issue before raising it contact us page is already there in the footer @Subham1
