### ISSUE TITLE
Error: change unLiked text using proper english

### ISSUE THREAD

**Issue by yehiarasheed** [recodehive/awesome-github-profiles#854]
### Describe the Error

Following up on issue #756, I did not yet change the text that shows up when you like and unlike a profile on the website to `unlike`. I will create a separate branch for it

### Expected behavior

text should be `You unliked a profile` as it should be in proper english.

**Comment by sanjay-kv** [comment]
next time, wait for to assign, because u might end up conflicts with other developers
