### ISSUE TITLE
Feature:  Clink button then text select 

### ISSUE THREAD

**Issue by YasirKhan231** [recodehive/awesome-github-profiles#857]
### Is your feature request related to a problem? Please describe.

When we click on the button then the text are get select 

### Describe the solution you'd like

use the tailwind css property of select -none 

### Describe alternatives you've considered

No alternative then this 

### Additional context

![Screenshot 2024-10-15 185327](https://github.com/user-attachments/assets/6fb13af4-28fa-48be-805a-452b420f4b34)

**Comment by sanjay-kv** [comment]
not something we looking for
