### ISSUE TITLE
Add Explore More Page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#86]
https://gssoc.girlscript.tech/codeofconduct

You might have noticed the explore button on footer.
<img width="319" alt="image" src="https://github.com/user-attachments/assets/54b76ad2-461c-4631-bd40-49ac8a18e727">

Make an Explore button the nav bar as well. 

content i will update on upcoming issues.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv i want to try it

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir should i have to create that page same as you have given in the link

**Comment by sanjay-kv** [comment]
yes. with matching theme of current website
