### ISSUE TITLE
Twitter logo is not displaying properly.

### ISSUE THREAD

**Issue by varma-101** [recodehive/awesome-github-profiles#860]
![image](https://github.com/user-attachments/assets/35f3ba93-f3b5-416f-9b29-5f9d494bda1d)

**Comment by sahare-mayur-0071** [comment]
Twitter is not visible properly 

![twitter is not visible](https://github.com/user-attachments/assets/cc6ed2e1-f19a-4b19-979c-7833d3e945b3)

 I won't to work on it. so assign this issue.

**Comment by HimangshuSharma01** [comment]
> Twitter is not visible properly @sanjay-kv
> 
> ![twitter is not visible](https://private-user-images.githubusercontent.com/184800556/376962043-cc6ed2e1-f19a-4b19-979c-7833d3e945b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODE1NjEsIm5iZiI6MTcyOTA4MTI2MSwicGF0aCI6Ii8xODQ4MDA1NTYvMzc2OTYyMDQzLWNjNmVkMmUxLWYxOWEtNGIxOS05NzljLTc4MzNkM2U5NDViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxMjIxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjA2NGQ1MGUwNTdiYmJlYmQ1ZDU5MmM1MTYzYzJjODczMmE2ZjU2YjYyNTE0ZGZiMjAxZTg1OTY4NGNkNWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oQs-ePHXGfCri-M1g7Ap-cb_kynh9UWRnj6DvXPgT8k)
> 
> I won't to work on it. so assign this issue.

its already assigned @sahare-mayur-0071

**Comment by varma-101** [comment]
Hello sir i can't able to understand where i have to change the code.please help me for this.

**Comment by HimangshuSharma01** [comment]
> Hello sir i can't able to understand where i have to change the code.please help me for this.

You can find the HTML and CSS in the gh branch.

**Comment by varma-101** [comment]
@sanjay-kv 
@HimangshuSharma01 
sir please review my pr #929  in which i've added screenshots of changes made.
