### ISSUE TITLE
Add Profile: rajdeepchakraborty-rc

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [recodehive/awesome-github-profiles#862]
### A pull request should be created from this issue if not kindly ping @dinxsh ⚠️

Profile link: https://github.com/rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
@dinxsh Since no PR was created, I pinged you.

**Comment by dinxsh** [comment]
we're working on fixing the bot and will add your profile once its done, until then please wait, thanks!

**Comment by rajdeepchakraborty-rc** [comment]
Sure. Thanks for the reply.

**Comment by rajdeepchakraborty-rc** [comment]
@dinxsh just wanted to follow up on the status of the bot fix. Is it resolved?
