### ISSUE TITLE
Error:  UI Enhancement of Compare page 

### ISSUE THREAD

**Issue by Peart-Guy** [recodehive/awesome-github-profiles#863]
### Describe the Error

Enhancing the UI/UX of Compare page for better user experience

**Comment by HimangshuSharma01** [comment]
Can you elaborate what kind of changes you want to make and do you have any sample?

**Comment by Peart-Guy** [comment]
> Can you elaborate what kind of changes you want to make and do you have any sample? @Peart-Guy


@HimangshuSharma01 
1. Typography Enhancements
2. Form Styling
3. Background and Colors
4. Spacing and Layout
5. Icons and Visuals
6. Final touch to maintain the theme and aesthetic
etc.
