### ISSUE TITLE
Event page simillar to the gssoc.

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#87]
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/217305b4-25d5-4ceb-9906-a9245a3fbdeb">

just make sure to be match our current theme. contents will be add in  the future .

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  sir i want to work on it

**Comment by Asymtode712** [comment]
@sanjay-kv Can I work on this

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i want to work on it

**Comment by Asymtode712** [comment]
Sorry @Ayushmaanagarwal1211 , as you have been already assigned 2 tasks previously so I thought maybe I could go for this one but if @sanjay-kv sir assigns you then too no issues

**Comment by Ayushmaanagarwal1211** [comment]
@Asymtode712 bro actually i already did one issue only one issue is left and will also complete by today afternoon
Hope You Understand

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv Sir can i try this one

**Comment by sanjay-kv** [comment]
Lets make it shared contribution, as this is priority work. we want to to get it done fast. i could see that I have assigned you more task in last couple of issue. there is more issue coming up so don't worry

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir i will try to do fast but if asymtode done it bofore then no issues

**Comment by sanjay-kv** [comment]
i will add more issues now . I'm organising requirements. if you have some idea can raise the issue, if its matching with my requirement I will assign to you

**Comment by Asymtode712** [comment]
@sanjay-kv Please check this page design....


https://github.com/user-attachments/assets/0768a8b7-9d99-4fef-8c68-615002bfa378
