### ISSUE TITLE
Feature: ADD  Tools PAGE IN YOUR WEBSITE

### ISSUE THREAD

**Issue by Darshan3690** [recodehive/awesome-github-profiles#873]
### Is your feature request related to a problem? Please describe.
 Tool page are missing.

 i want add tool page

### Describe the solution you'd like

Tools Page Concept:

The Tools page will provide a collection of useful resources and tools for GitHub users, developers, and open-source enthusiasts.

### Describe alternatives you've considered
Tools Page Structure:

1. Introduction
2. Categories
3. Tool Listings
4. Search Bar (optional)
5. Filtering (optional)

 please assign me under gssoc'24 and hacktoberfest 24

**Comment by Darshan3690** [comment]
#873 issues

**Comment by HimangshuSharma01** [comment]
@Darshan3690 any update regarding this?

**Comment by Darshan3690** [comment]
@HimangshuSharma01 I already created the tool page but I have a one problem in PR

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 I already created the tool page but I have a one problem in PR

tell me the issue

**Comment by Darshan3690** [comment]
@HimangshuSharma01  i add my code in gh-pages repository. i have problem to create a pr in main repository.

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01  i add my code in gh-pages repository. i have problem to create a pr in main repository.

Please attach a screenshot so that I can understand better.

**Comment by Darshan3690** [comment]
![image](https://github.com/user-attachments/assets/f9187255-3ac6-4109-aa56-d47092c9a01d)

@HimangshuSharma01

**Comment by sanjay-kv** [comment]
you must fork the project.

**Comment by Darshan3690** [comment]
add tool page #1  @sanjay-kv 
![image](https://github.com/user-attachments/assets/4f9274ba-6ebd-411a-8bff-790516b79521)

**Comment by Darshan3690** [comment]
ADD TOOL PAGE #942 PR @sanjay-kv
