### ISSUE TITLE
Error:  Resize Choose Language Box and Adjust Font Size

### ISSUE THREAD

**Issue by Rahilsamani** [recodehive/awesome-github-profiles#874]
### Describe the Error

The choose language box is currently oversized, both in terms of dimensions and font size. This affects the overall aesthetics of the page and makes it less user-friendly.

### Expected behavior

The choose language box should have a more appropriate size, with a font size that is consistent with the rest of the UI, ensuring a cohesive design.

### Additional context

Adjusting the size and font of the choose language box will enhance user experience and improve visual balance. Consider reviewing other dropdowns in the application for consistency.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/10644dd7-5ead-495f-a5ed-0072dc914ebd">

<img width="935" alt="image" src="https://github.com/user-attachments/assets/780cc440-3717-451c-ba19-5096f0236e1a">

**Comment by HimangshuSharma01** [comment]
@Rahilsamani Any update regarding this issue ?

**Comment by Rahilsamani** [comment]
@HimangshuSharma01 
Working on it
