### ISSUE TITLE
Feature: UI improvement of GitHub Contributor Comparison

### ISSUE THREAD

**Issue by Roshn1** [recodehive/awesome-github-profiles#878]
### Is your feature request related to a problem? Please describe.

we can enhance the ui of the GitHub Contributor Comparison , like the selection field is too long , and the width of the submit button is also more.

### Describe the solution you'd like

i can improve the ui of this section so that it will look good and clean. So please assign this work to me.

### Additional context
![Screenshot 2024-10-16 232551](https://github.com/user-attachments/assets/bdb5615e-3e2f-4e61-8f7f-1487b1ca970f)

**Comment by HimangshuSharma01** [comment]
@sanjay-kv Sir i can work in this
