### ISSUE TITLE
Error: Social icon bug

### ISSUE THREAD

**Issue by satyamra1** [recodehive/awesome-github-profiles#880]
### Describe the Error
Twitter icon is not visible in socials .

### Expected behavior

Twitter icon will also be displayed

### Additional context

![image](https://github.com/user-attachments/assets/71dd5dc6-cbab-4ca2-8d0f-d60d8dade79a)

**Comment by HimangshuSharma01** [comment]
Already Assigned in issue and he completed it in PR ##929
