### ISSUE TITLE
Feature:- Add Comment Feature to Awesome GitHub Profile Section

### ISSUE THREAD

**Issue by arpita205** [recodehive/awesome-github-profiles#886]
Issue Type: Feature Request

Summary: I would like to request the addition of a comment feature to the Awesome GitHub profile section, alongside the existing like button. This feature will enhance user interaction by allowing users to leave comments and feedback on profiles.

Detailed Description: The Awesome GitHub profile section currently allows users to show appreciation by liking profiles. Adding a comment feature would further enhance the functionality by enabling users to leave remarks, suggestions, or feedback. This could be beneficial for networking, collaboration, and community building.

Proposed Solution:

UI/UX Design:

Add a comment icon/button next to the like button.
Design a comment input box that can expand to show multiple lines of text.
Display comments in a scrollable section beneath the profile details.
Backend Implementation:

Create a new API endpoint for submitting comments.
Store comments in a database associated with the user's profile.
Implement moderation features to manage inappropriate comments (e.g., flagging, reporting, and deleting comments).
Notifications:

Send notifications to profile owners when new comments are added.
Option to enable or disable comment notifications.

**Comment by arpita205** [comment]
I have joined the community.

**Comment by arpita205** [comment]
I have code which can be added to it


In your profile section HTML, add a comment button next to the like button:

1)html code

<div class="profile-actions">
  <button class="like-button">Like</button>
  <button class="comment-button">Comment</button>
</div>


#Create a comment input box that can expand:


<div class="comment-section">
  <textarea class="comment-input" placeholder="Write a comment..."></textarea>
  <button class="submit-comment">Submit</button>
</div>



#Display comments in a scrollable section:


<div class="comments-display">
  <div class="comment">
    <p><strong>User1:</strong> Great profile!</p>
  </div>
  
</div>

2) CSS


.profile-actions {
  display: flex;
  justify-content: space-between;
}

.comment-section {
  margin-top: 10px;
}

.comment-input {
  width: 100%;
  height: 50px;
  resize: none;
}

.comments-display {
  max-height: 200px;
  overflow-y: auto;
  margin-top: 10px;
  border-top: 1px solid #ccc;
  padding-top: 10px;
}

3) Backend Implementation

#Create API Endpoint


const express = require('express');
const router = express.Router();
const Comment = require('../models/Comment'); // Mongoose model for comments

// POST endpoint to add a comment
router.post('/profiles/:profileId/comments', async (req, res) => {
  const { profileId } = req.params;
  const { userId, commentText } = req.body;

  try {
    const comment = new Comment({
      profileId,
      userId,
      commentText,
      createdAt: new Date(),
    });

    await comment.save();
    res.status(201).send(comment);
  } catch (error) {
    res.status(500).send(error);
  }
});

module.exports = router;


#Store Comments in Database


const mongoose = require('mongoose');

const commentSchema = new mongoose.Schema({
  profileId: { type: mongoose.Schema.Types.ObjectId, ref: 'Profile', required: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  commentText: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
});

const Comment = mongoose.model('Comment', commentSchema);

module.exports = Comment;

 3. Frontend Integration

# Submitting Comments



javascript

document.querySelector('.submit-comment').addEventListener('click', async () => {
  const commentText = document.querySelector('.comment-input').value;
  const profileId = 'PROFILE_ID_HERE'; // Replace with actual profile ID

  const response = await fetch(`/profiles/${profileId}/comments`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      userId: 'USER_ID_HERE', // Replace with actual user ID
      commentText,
    }),
  });

  if (response.ok) {
    const comment = await response.json();
    // Display the new comment
    const commentDisplay = document.querySelector('.comments-display');
    const newComment = document.createElement('div');
    newComment.classList.add('comment');
    newComment.innerHTML = `<p><strong>${comment.userId}:</strong> ${comment.commentText}</p>`;
    commentDisplay.appendChild(newComment);
    document.querySelector('.comment-input').value = ''; // Clear input
  }
});


 4. Notifications

#Send Notifications

Use a library like `nodemailer` for email notifications 

javascript

const nodemailer = require('nodemailer');

const sendNotification = async (profileOwnerEmail, commentText) => {
  let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: 'your-email@gmail.com',
      pass: 'your-email-password',
    },
  });

  let mailOptions = {
    from: 'your-email@gmail.com',
    to: profileOwnerEmail,
    subject: 'New Comment on Your Profile',
    text: `You have a new comment: ${commentText}`,
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log('Error: ' + error);
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
};

// Call sendNotification function when a new comment is added
router.post('/profiles/:profileId/comments', async (req, res) => {
  const { profileId } = req.params;
  const { userId, commentText } = req.body;

  try {
    const comment = new Comment({
      profileId,
      userId,
      commentText,
      createdAt: new Date(),
    });

    await comment.save();

    // Fetch profile owner's email (assuming you have a Profile model with owner info)
    const profile = await Profile.findById(profileId).populate('owner');
    sendNotification(profile.owner.email, commentText);

    res.status(201).send(comment);
  } catch (error) {
    res.status(500).send(error);
  }
});


This implementation is for adding a comment feature to the Awesome GitHub profile section. we can expand on this by adding features like comment editing, deleting, and reporting as needed.

**Comment by HimangshuSharma01** [comment]
> I have code which can be added to it
> 
> In your profile section HTML, add a comment button next to the like button:
> 
> 1)html code
> 
> Like Comment
> #Create a comment input box that can expand:
> 
> <textarea class="comment-input" placeholder="Write a comment..."></textarea> Submit
> #Display comments in a scrollable section:
> 
> **User1:** Great profile!
> 
> 2. CSS
> 
> .profile-actions { display: flex; justify-content: space-between; }
> 
> .comment-section { margin-top: 10px; }
> 
> .comment-input { width: 100%; height: 50px; resize: none; }
> 
> .comments-display { max-height: 200px; overflow-y: auto; margin-top: 10px; border-top: 1px solid #ccc; padding-top: 10px; }
> 
> 3. Backend Implementation
> 
> #Create API Endpoint
> 
> const express = require('express'); const router = express.Router(); const Comment = require('../models/Comment'); // Mongoose model for comments
> 
> // POST endpoint to add a comment router.post('/profiles/:profileId/comments', async (req, res) => { const { profileId } = req.params; const { userId, commentText } = req.body;
> 
> try { const comment = new Comment({ profileId, userId, commentText, createdAt: new Date(), });
> 
> ```
> await comment.save();
> res.status(201).send(comment);
> ```
> 
> } catch (error) { res.status(500).send(error); } });
> 
> module.exports = router;
> 
> #Store Comments in Database
> 
> const mongoose = require('mongoose');
> 
> const commentSchema = new mongoose.Schema({ profileId: { type: mongoose.Schema.Types.ObjectId, ref: 'Profile', required: true }, userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, commentText: { type: String, required: true }, createdAt: { type: Date, default: Date.now }, });
> 
> const Comment = mongoose.model('Comment', commentSchema);
> 
> module.exports = Comment;
> 
> 3. Frontend Integration
> 
> # Submitting Comments
> javascript
> 
> document.querySelector('.submit-comment').addEventListener('click', async () => { const commentText = document.querySelector('.comment-input').value; const profileId = 'PROFILE_ID_HERE'; // Replace with actual profile ID
> 
> const response = await fetch(`/profiles/${profileId}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json', }, body: JSON.stringify({ userId: 'USER_ID_HERE', // Replace with actual user ID commentText, }), });
> 
> if (response.ok) { const comment = await response.json(); // Display the new comment const commentDisplay = document.querySelector('.comments-display'); const newComment = document.createElement('div'); newComment.classList.add('comment'); newComment.innerHTML = `<p>\<strong\>${comment.userId}:\</strong\> ${comment.commentText}</p>`; commentDisplay.appendChild(newComment); document.querySelector('.comment-input').value = ''; // Clear input } });
> 
> 4. Notifications
> 
> #Send Notifications
> 
> Use a library like `nodemailer` for email notifications
> 
> javascript
> 
> const nodemailer = require('nodemailer');
> 
> const sendNotification = async (profileOwnerEmail, commentText) => { let transporter = nodemailer.createTransport({ service: 'gmail', auth: { user: '[your-email@gmail.com](mailto:your-email@gmail.com)', pass: 'your-email-password', }, });
> 
> let mailOptions = { from: '[your-email@gmail.com](mailto:your-email@gmail.com)', to: profileOwnerEmail, subject: 'New Comment on Your Profile', text: `You have a new comment: ${commentText}`, };
> 
> transporter.sendMail(mailOptions, (error, info) => { if (error) { console.log('Error: ' + error); } else { console.log('Email sent: ' + info.response); } }); };
> 
> // Call sendNotification function when a new comment is added router.post('/profiles/:profileId/comments', async (req, res) => { const { profileId } = req.params; const { userId, commentText } = req.body;
> 
> try { const comment = new Comment({ profileId, userId, commentText, createdAt: new Date(), });
> 
> ```
> await comment.save();
> 
> // Fetch profile owner's email (assuming you have a Profile model with owner info)
> const profile = await Profile.findById(profileId).populate('owner');
> sendNotification(profile.owner.email, commentText);
> 
> res.status(201).send(comment);
> ```
> 
> } catch (error) { res.status(500).send(error); } });
> 
> This implementation is for adding a comment feature to the Awesome GitHub profile section. we can expand on this by adding features like comment editing, deleting, and reporting as needed.

Its not the way of adding sample add a screen shot or video
