### ISSUE TITLE
Feature: enhancing interface of compare page

### ISSUE THREAD

**Issue by Jashwanth-rit** [recodehive/awesome-github-profiles#888]
### Describe the solution you'd like

Enhancing UI , make it look better and attractive.

### Additional context

![Screenshot 2024-10-17 192620](https://github.com/user-attachments/assets/100303ee-bd2e-4720-a3fe-db40f502b0f8)

**Comment by HimangshuSharma01** [comment]
@jashwanth look for the existing issue before creating a new one #878 has already been assign
