### ISSUE TITLE
Feature: Adding validation for Signup page and redirecting to login page.

### ISSUE THREAD

**Issue by Jashwanth-rit** [recodehive/awesome-github-profiles#889]
### Is your feature request related to a problem? Please describe.

Currently, the signup page does not implement any validation for user input, which can lead to erroneous or incomplete submissions. This issue aims to add form validation to the signup page and redirect users to the login page upon successful signup.
### Describe the solution you'd like

Form Validation:

- Add validation logic to the signup form.
- Display error messages for invalid inputs below each respective field.
- Prevent form submission if validation fails.

Redirect Logic:

- On successful form submission, redirect the user to the login page.
- Optionally, display a message indicating that the signup was successful and they can now log in.

User Experience:

- Ensure the validation messages are clear and easily noticeable.
- Test the redirect functionality to confirm that users arrive at the login page correctly.
-

**Comment by thebraudalf** [comment]
Ok, i will i do it assign this to me.

**Comment by Jashwanth-rit** [comment]
No bro , i am working on it.

**Comment by thebraudalf** [comment]
Ok, you can take help from me without any hesitation.

**Comment by sidgureja7803** [comment]
> No bro , i am working on it.

hey @Jashwanth-rit, what's the update ??
You will be integrating the firebase features as well, for Google and Github authentication and OTP verification for email ??
