### ISSUE TITLE
Feature: Implimentation of login Verification , using Signup info .

### ISSUE THREAD

**Issue by Jashwanth-rit** [recodehive/awesome-github-profiles#891]
### Is your feature request related to a problem? Please describe.

Currently, there is no mechanism to verify user login using the data provided during signup. This issue focuses on implementing a login verification system that ensures only registered users can log in by validating their credentials against the stored signup information.

### Describe the solution you'd like

Backend Logic:

- Create a login endpoint (e.g., /login) in the backend to validate user credentials.
- Retrieve signup data from the database for verification.
- Implement password hashing (e.g., bcrypt) and comparison logic for security.

Frontend Logic:

- Create a login form where users input their credentials.
- On form submission, send the data to the backend for verification.
- Display success or failure messages based on the response.

State Management:

- Store user authentication status (e.g., using Redux, Context API, or local storage).
- Update the Navbar and other UI elements accordingly (e.g., show "Logout" when logged in).

Testing:

- Test with both valid and invalid credentials to ensure login works as expected.
- Ensure secure storage of passwords and tokens if implemented.

**Comment by HimangshuSharma01** [comment]
@Jashwanth-rit Any  update regarding this issue ?
