### ISSUE TITLE
Error: Bug on Hover near search button , visible of mic button , on hover near search button

### ISSUE THREAD

**Issue by Jashwanth-rit** [recodehive/awesome-github-profiles#892]
### Describe the Error

When hovering near the search button, an unexpected microphone (mic) button becomes visible. This behavior is unintended and creates a poor user experience. The mic button should either remain hidden unless required or appear in a controlled manner without being triggered on hover near the search button.

Steps to Reproduce

- Navigate to the page containing the search bar.
- Move the cursor near or around the search button.
- Notice the mic button becomes visible unexpectedly upon hover.

### Expected behavior

The mic button should only appear when explicitly triggered (e.g., via click on the search input, if voice search is enabled).
Hovering near the search button should not cause any unintended UI changes.

### Additional context

https://github.com/user-attachments/assets/394de6f1-e952-4b5f-ac0f-d9a9ebaa17f5

**Comment by HimangshuSharma01** [comment]
@Jashwanth-rit assigning this to you make sure you complete this fast ,its just not visible in dark mode only fix that

**Comment by Jashwanth-rit** [comment]
Sure

**Comment by Jashwanth-rit** [comment]
where does index.html file exists in this project structure.

**Comment by HimangshuSharma01** [comment]
> where does index.html file exists in this project structure.
> 

Go to the gh branch you will find it there sorry I forgot to mention

**Comment by Jashwanth-rit** [comment]
it's okay , fine.

**Comment by HimangshuSharma01** [comment]
> it's okay , fine.

you made a pull request for a wrong branch kindly resolve it.

**Comment by Jashwanth-rit** [comment]
@HimangshuSharma01 could please clearly specify, on which branch I should work

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 could please clearly specify, on which branch I should work

On the gh branch I mentioned it

**Comment by Akshithsaai** [comment]
@Jashwanth-rit Is this issue fixed ? Because its not reflecting changes for me. 

![image](https://github.com/user-attachments/assets/debba6ba-fe79-474b-a800-ee5cfdd68be2)
