### ISSUE TITLE
Error: Overflow of Theme Toggling Button

### ISSUE THREAD

**Issue by Shariq2003** [recodehive/awesome-github-profiles#897]
![image](https://github.com/user-attachments/assets/03edf3ce-6566-4ea3-8ab4-0b1c241afff3)

![image](https://github.com/user-attachments/assets/702de87b-22d7-4830-902a-3f767a8b940c)

**Comment by HimangshuSharma01** [comment]
https://github.com/user-attachments/assets/5ac6f05e-4ba5-4573-ad0f-5dcf0f2b77eb

I cant see it over flowing can you tell me how to reproduce what you have mentioned

**Comment by Shariq2003** [comment]
> Blogs.-.Google.Chrome.2024-10-17.22-15-15.mp4 
> I cant see it over flowing can you tell me how to reproduce what you have mentioned @Shariq2003


https://github.com/user-attachments/assets/8a5025db-1bd7-4585-9f88-661e1b4c5fef

Look in this, its showing here, in my laptop, even though in the deployment of the website too.

**Comment by Shariq2003** [comment]
@HimangshuSharma01 Sorry, actually my branch was 2 commits behind

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 Sorry, actually my branch was 2 commits behind

👍
