### ISSUE TITLE
reduce the profile display

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#905]
![image](https://github.com/user-attachments/assets/424353bc-8059-46c4-a2ab-e9bc1282f9b6)

watch the below video
[New Issue · recodehive/awesome-github-profiles - Google Chrome - 18 October 2024 - Watch Video](https://www.loom.com/share/01fcca66275046bda4b54ae1d479ad15)

**Comment by JomanaMahmoud** [comment]
Assign me if still available
