### ISSUE TITLE
Workflow for automcomment after raising issue

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#906]
<div>
    <a href="https://www.loom.com/share/e9c73efe1f7349c58572b4358273e500">
      <p>[Feature Request]: Add some more charts for better understanding for Job Satisfaction Analysis · Issue #390 · recodehive/Stackoverflow-Analysis - Google Chrome - 18 October 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/e9c73efe1f7349c58572b4358273e500">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e9c73efe1f7349c58572b4358273e500-4dc2fae0ae1ed547-full-play.gif">
    </a>
  </div>
  
  
  the below is the comment need to add..👇🏻
  

```
Thank you for creating this issue! 🎉 We'll look into it asap and assign you based on FCFS

- [ ] In the meantime, please make sure to Join recode org [Invite link](https://github.com/recodehive/Support/issues/new?assignees=&labels=invite+me+to+the+community&projects=&template=invitation.yml&title=Please+invite+me+to+the+Recode-Hive+GitHub+Community+Organization).
- [ ] The main code file is located in gh-pages branch
- [ ] Watch the complete youtube [GitHub Tutorial](https://stream.recodehive.com/github) 

Your contributions are highly appreciated! 😊 Don't forgot to follow me @sanjay-kv 
`More surprise when you raise PR`

```

**Comment by HimangshuSharma01** [comment]
@sanjay-kv I can work in this

**Comment by HimangshuSharma01** [comment]
i did this sir

**Comment by sanjay-kv** [comment]
i changed the main directory to `gh-pages` will this impact the workflow.

**Comment by HimangshuSharma01** [comment]
> i changed the main directory to `gh-pages` will this impact the workflow. 

In the recent issue there is no comment I will try to fix it after college

**Comment by HimangshuSharma01** [comment]
@sanjay-kv Sir I have looked into this its pretty confusing we have the same files and same codes still its not working I need help in this.

**Comment by sanjay-kv** [comment]
no worries, i will look into it.

**Comment by HimangshuSharma01** [comment]
> no worries, i will look into it.

okay sir

**Comment by HimangshuSharma01** [comment]
> no worries, i will look into it.

Sir please let me know what was the solution once you figure it out, i want to learn because i might face similar issues in future. thank you sir.

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me
