### ISSUE TITLE
Twitter Icon not working

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#908]
![image](https://github.com/user-attachments/assets/92751ed2-e67d-40bb-816b-3d8a5c1cdd74)

**Comment by sanskaryo** [comment]
I believe this issue is straightforward, and I am confident I can resolve it. Could you please assign it to me?

**Comment by Abhijeet14d** [comment]
If this issue still available, assign this to me

**Comment by SKG24** [comment]
If this issue is still unresolved, I would be happy to assist. Please feel free to assign it to me.
