### ISSUE TITLE
Footer change background

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#91]
![image](https://github.com/user-attachments/assets/aae91e94-258b-4056-8030-fb4483c96338)

There is a light change should be done on white theme. 

![image](https://github.com/user-attachments/assets/09ce7382-e8e9-4012-ad46-ac1288dec513)
maybe a bit grey color helps to differentiate

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv Sir i want to work on that

**Comment by Ayushmaanagarwal1211** [comment]
![image](https://github.com/user-attachments/assets/8d970d07-ea1f-48cc-b391-8f7b561a257b)
@sanjay-kv sir is color okay

**Comment by sanjay-kv** [comment]
Yes

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir so i am creating pr
