### ISSUE TITLE
Quickdraw link missing 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#912]
on page: https://recodehive.github.io/awesome-github-profiles/pages/githubbadge.html
![image](https://github.com/user-attachments/assets/7c9910d3-5f1a-47da-94d2-89b696d60033)

[Watch the video Tutorial](https://youtu.be/BNKSlT8jLQ0)

**Comment by Jayesh-Waghmare** [comment]
@sanjay-kv sir, Could you please assign me the issue? I can fix it. ... Thank you

**Comment by JomanaMahmoud** [comment]
Assign me if still available
