### ISSUE TITLE
More details to compare page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#913]
on compare page: add the below details. https://recodehive.github.io/awesome-github-profiles/pages/compare.html

![image](https://github.com/user-attachments/assets/d114255f-afc9-46d1-8f8f-89f17b066cc7)

**Comment by Akshithsaai** [comment]
Hi @sanjay-kv I want to work on this issue.

**Comment by JomanaMahmoud** [comment]
Assign me if still available

**Comment by Akshithsaai** [comment]
@sanjay-kv 

I have added the details you mentioned in the description. Please check and suggest changes , if any, 

![image](https://github.com/user-attachments/assets/8fc7995b-b980-40fa-b53e-e0c353354aeb)

**Comment by Akshithsaai** [comment]
@sanjay-kv Should I do any changes before I raise a PR ?

**Comment by sanjay-kv** [comment]
@Akshithsaai This looks fine
