### ISSUE TITLE
remove this from the Learn page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#916]
![image](https://github.com/user-attachments/assets/1453f4f8-c883-4224-9144-c6b5a94782c0)

i dont want the highlighted buttons so you can remove this

**Comment by PreetSharma-12** [comment]
Hello @sanjay-kv Sir, i can fix this issue, can you please assign me the same?

**Comment by PreetSharma-12** [comment]
Thanks for assigning me this issue, I'm working on it and adding my PR asap. @sanjay-kv

**Comment by PreetSharma-12** [comment]
@sanjay-kv Sir, could you please tell me where is the code of the blog.html page

**Comment by sanjay-kv** [comment]
branch `gh-pages`
