### ISSUE TITLE
make the logo big in the footer

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#918]
![image](https://github.com/user-attachments/assets/1f477725-c366-44c7-9d26-61ec83695577)

**Comment by Jayesh-Waghmare** [comment]
Hi @sanjay-kv sir, can you please assign me this issue? ... Thank you

**Comment by PreetSharma-12** [comment]
Hello @sanjay-kv sir, i can fix this issue, would you please assign me the same?

**Comment by JomanaMahmoud** [comment]
Assign me if still available

**Comment by sidgureja7803** [comment]
@sanjay-kv assign this issue to me please, if available

**Comment by Jayesh-Waghmare** [comment]
I can access this page http://127.0.0.1:5500/awesome-github-profiles/tool.html after cloning.
Is this the correct page?
And do I have to make the logo and text bigger in the footer of the above mentioned page that I have access to?

**Comment by HimangshuSharma01** [comment]
> Hi @sanjay-kv sir. I can access this page http://127.0.0.1:5500/awesome-github-profiles/tool.html after cloning. Is this the correct page? Do I have to make changes to this? As the image you have provided is not from this page There's no gh-pages branch found when I forked.

the link which sent is in your local server
others cant see this better record a video and then send

**Comment by Jayesh-Waghmare** [comment]
This one...

https://github.com/user-attachments/assets/c93aa3f7-87dc-44f3-8f8d-a36eba714381

**Comment by HimangshuSharma01** [comment]
> Hi @sanjay-kv sir. I can access this page http://127.0.0.1:5500/awesome-github-profiles/tool.html after cloning. Is this the correct page? Do I have to make changes to this? As the image you have provided is not from this page There's no gh-pages branch found when I forked.



> This one...
> 
>  Video2.mp4

no u need to work on the gh poges

**Comment by Jayesh-Waghmare** [comment]
when i forked on the repo, the gh-pages was not found in the branch

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 sir, when I forked on the repo, the gh-pages were not found in the branch

![image](https://github.com/user-attachments/assets/44f2814b-22ba-4cc6-8e01-2ecba65e983e)
untick that when u fork to get all the branches

**Comment by Jayesh-Waghmare** [comment]
Is this ok?  @sanjay-kv  @HimangshuSharma01 
I have increase the size of the logo as well as the text beside it
![image](https://github.com/user-attachments/assets/6055c90f-3137-46a8-b099-50caa339fa9c)
