### ISSUE TITLE
Hyper link on the footer

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#919]
add hyper link to the footer
![image](https://github.com/user-attachments/assets/a8e5bb10-4358-49d4-b5a9-12e1bd60eb25)

add the link https://stream.recodehive.com/github

**Comment by Jayesh-Waghmare** [comment]
Hi @sanjay-kv sir, I can fix the issue. Can you please assign me this issue?

**Comment by JomanaMahmoud** [comment]
Assign me if still available

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
