### ISSUE TITLE
Explore us page not working

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#920]
![image](https://github.com/user-attachments/assets/2df0341c-1fa1-40bb-ac22-19bd5f09dd63)

this page is linked to code of conduct ,. link to proper explore page

**Comment by Jayesh-Waghmare** [comment]
Hi @sanjay-kv sir, Can you please assign me this issue?
Also, tell me more descriptions to where the explore page should redirect to.

**Comment by JomanaMahmoud** [comment]
Assign me if still available

**Comment by sanjay-kv** [comment]
https://stream.recodehive.com/github
