### ISSUE TITLE
Add more details to compare page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#921]
In the compare page make an option to search github users
https://recodehive.github.io/awesome-github-profiles/pages/compare.html

sample: 
https://githubprofilecompare.netlify.app/gitfind

![image](https://github.com/user-attachments/assets/82357f42-6f9f-4847-93ad-d3c9c4e02811)

**Comment by Akshithsaai** [comment]
@sanjay-kv So whenever a user enters a github profile name, a github API call should fetch the results ?

**Comment by sanjay-kv** [comment]
@Akshithsaai yes

**Comment by sidgureja7803** [comment]
@sanjay-kv assign this issue to me
i can work on it

**Comment by Akshithsaai** [comment]
@sanjay-kv 

Please Check it and suggest any changes. 


https://github.com/user-attachments/assets/41d5541e-a85f-4f83-b000-aad6b3fef313

**Comment by Akshithsaai** [comment]
@sanjay-kv Can I proceed to PR? Please suggest any changes.

**Comment by sanjay-kv** [comment]
this is great.
