### ISSUE TITLE
Updating the latest twitter logo on the icons list.

### ISSUE THREAD

**Issue by PreetSharma-12** [recodehive/awesome-github-profiles#926]
The twitter logo doesn't appear on the right side icons. The third circle is empty and it should be filled with the current twitter logo. I can fix this problem, please assign me this issue. @sanjay-kv 
![x](https://github.com/user-attachments/assets/d0b1177c-24a8-48e3-8178-3c9689583189)

**Comment by Panchadip-128** [comment]
Can i be assigned this task? The twitter X logo must be placed at appropriate position to avoid hindrance
![x_img](https://github.com/user-attachments/assets/42dacd4b-6b54-4e3e-9e7c-9c5e7b46da76)

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by ChimeraElixir** [comment]
can i be assigned this task , also the new x logo is not showing in the website ,both on dark and light mode
@sanjay-kv
