### ISSUE TITLE
The languages button size should be small.

### ISSUE THREAD

**Issue by PreetSharma-12** [recodehive/awesome-github-profiles#927]
The language choosing button on the left bottom side of the screen should be a bit smaller, the size is too big and is looking odd. Please assign me this issue so that i can fix it. @sanjay-kv 
![Screenshot of website(gssoc)](https://github.com/user-attachments/assets/bff3197f-80d3-4206-a5a8-967b801ad2c7)

**Comment by MuKulsoop** [comment]
Can I work on this issue

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
