### ISSUE TITLE
90 points issue: Postman challenge related. 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#93]
https://www.loom.com/share/a4f093cb62904d58817e8b54e72d1391?sid=bebec814-46a1-4098-9030-c14d226940eb
watch the video

https://github.com/GSSoC24/Postman-Challenge/blob/main/campus-ambassador.md

File to edit

https://gssoc24.github.io/Postman-Challenge/campus-ambassador.html output link.

CA leaderboard: https://discord.com/channels/@me/1245741118293803170/1269464397047398553

bit slow it is

Work might help gssoc program a lot, you will be impacting 1000+ users to get certificate

**Comment by Hemu21** [comment]
@sanjay-kv  can you please assign me.
