### ISSUE TITLE
Error: Improve Signup/Email Validation and Login Functionality

### ISSUE THREAD

**Issue by sidgureja7803** [recodehive/awesome-github-profiles#935]
###Describe the Error
1- After signing up on the website, the Login button remains visible, indicating the user is not logged in.
2- There is no email validation during the signup process, which can result in users signing up with invalid email addresses.
3- When trying to log in after signing up, the login function displays "incorrect data", even with correct credentials.
4 - Additionally, GitHub login is non-functional as Firebase Authentication for GitHub is not enabled.

###Expected Behavior
1- After signing up, the Login button should be hidden, and the user should be redirected to the dashboard or their profile page.
2- The system should verify the user's email by sending an OTP during signup, which must be entered to complete the process.
3- The login function should work as expected, allowing users to log in with valid credentials.
4- GitHub login should be enabled via Firebase Authentication, allowing users to sign in with their GitHub accounts.

###Additional Context
1 - Firebase Authentication needs to be configured to enable GitHub login.
2- Consider integrating an email service provider to send OTPs for email verification during the signup process.
3- The login issue might be related to incorrect credential handling on the backend.

**Comment by sidgureja7803** [comment]
@sanjay-kv assign this issue to me
i will Github / Google authentication using firebase and will also add email validity check via OTP
and will ensure no two user have the same username ( just like Instagram and Twitter ).

**Comment by sanjay-kv** [comment]
its already assigned

**Comment by sidgureja7803** [comment]
> its already assigned
@sanjay-kv sir, you assigned this to a person day before yestarday,
@Jashwanth-rit are you working on features like Firebase integration and OTP verification sending features for email validity and changing the user-Model, so that no two people have the same username ???
if you are not working on these features and just simply form validation, then kindly let me work on this, because these features will be implemented using Backend, but the code-base is completely written in frontend only.

**Comment by Jashwanth-rit** [comment]
Nope,

**Comment by sidgureja7803** [comment]
> Nope,

okay, so i will work on these features
