### ISSUE TITLE
Twitter icon is displayed blank 

### ISSUE THREAD

**Issue by AnishaDevi** [recodehive/awesome-github-profiles#946]
![image](https://github.com/user-attachments/assets/f4ed5471-424e-4bd8-9c98-5c77586b1c10)

The third icon does not contain icon of twitter
@iamkanhaiyakumar
I would like to update so please assign me with the same

- [x] gsoc contributor
- [x] hacktoberfest contributor

**Comment by sanjay-kv** [comment]
this is already done
