### ISSUE TITLE
Error: Dark mode enhancement

### ISSUE THREAD

**Issue by saumyayadav25** [recodehive/awesome-github-profiles#951]
### Describe the Error
In dark mode, placeholder text is not clearly visible
In footer, black heading is not visible in dark mode in any of the pages.

<img width="866" alt="Screenshot 2024-10-19 at 6 34 10 PM" src="https://github.com/user-attachments/assets/c1bf02af-4b12-4241-a647-cddcf1363bb7">
<img width="1086" alt="Screenshot 2024-10-19 at 6 34 22 PM" src="https://github.com/user-attachments/assets/1874619d-d94d-497c-8d69-01d8325413b6">

### Expected behavior

Lighter color should be used in dark mode for better visibility.

**Comment by snehaamujri** [comment]
@sanjay-kv assign this issue to me I am interested  under gssoc extd and hacktoberfest

**Comment by leocodeio** [comment]
@sanjay-kv  assign this issue to me, want to work up on gssoc extd and hacktoberfest

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
