### ISSUE TITLE
Error: Missing Instagram Logo in Social Media Links

### ISSUE THREAD

**Issue by priyanshu5ingh** [recodehive/awesome-github-profiles#983]
### Describe the Error

There is a blank space in the social media links section on the right side of the page where the Instagram logo should be. This missing logo affects the visual consistency and user experience, as users might not realize they can follow us on Instagram.

### Expected behavior

 The Instagram logo should be present alongside other social media icons that link to our Instagram profile. 
<img width="219" alt="{6D951FAF-151E-4074-953F-9D6BCD595D3D}" src="https://github.com/user-attachments/assets/09996399-a200-4b7e-ad80-6525920c17ee">

### Additional context

Including the Instagram logo will enhance our social media presence and make it easier for users to connect with us on all platforms.

kindly assign it to me under gssoc'24 ext

**Comment by Satishmirjan** [comment]
assign me this , i already solved similar problems.

**Comment by sourav349** [comment]
Hey, @priyanshu5ingh I am interested in this issue, can you assign this issue too me..
There is a gap in the social media links section on the right side of the page where the Instagram logo should be. This absence affects visual consistency and user experience, as users may not realize they can follow us on Instagram. Adding the logo will enhance engagement and clarity. Also we can improve the hover section. 

 I believe these changes will significantly enhance the overall user experience.

**Comment by CreativitySayan** [comment]
Can I get assigned to this issue as I can sort the issue of missing Instagram logo in social media links

**Comment by sanjay-kv** [comment]
we can skip insta
