### ISSUE TITLE
Error: footer not properly aligned 

### ISSUE THREAD

**Issue by Theboycut05** [recodehive/awesome-github-profiles#984]
### Describe the Error

The text on the footer is not properly located it's taking too much space and doesn't look well
### Expected behavior
 The content should be aligned properly to make it look perfect

That text content can be aligned below the area where  the space is blank 
### Additional context

![Uploading Screenshot_20241020_210203.jpg…]()

**Comment by Theboycut05** [comment]
![Uploading Screenshot_20241020_210203.jpg…]()

**Comment by Theboycut05** [comment]
![Screenshot_20241020_210203](https://github.com/user-attachments/assets/dc40a0f6-e638-41c8-9664-5e7c55b4a636)

**Comment by Satishmirjan** [comment]
assign me this , i already solved similar problems.

**Comment by Theboycut05** [comment]
ive sloved this issue and did pr you can close this issue
